### ISSUE TITLE
Error in session secret generation

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#1042]
@spinolacastro ran into this when they had set `openshift_master_session_auth_secrets` and `openshift_master_session_encryption_secrets` in their hosts file. It skips the generation but then for some reason it's falling into the default() where we expect the output from the openssl commands.

```
TASK: [Install OpenSSL package] ***********************************************
ok: [master0]

TASK: [Generate session authentication key] ***********************************
skipping: [master0] => (item=1)

TASK: [Generate session encryption key] ***************************************
skipping: [master0] => (item=1)

TASK: [set_fact ] *************************************************************
fatal: [master0] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1013, in _executor_internal_inner
    complex_args = template.template(self.basedir, complex_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 12, in root
  File "/home/azureuser/openshift-ansible/filter_plugins/oo_filters.py", line 83, in oo_collect
    retval = [FilterModule.get_attr(d, attribute) for d in data]
  File "/home/azureuser/openshift-ansible/filter_plugins/oo_filters.py", line 42, in get_attr
    ptr = ptr[attr]
KeyError: 'stdout'

FATAL: all hosts have already failed -- aborting
```

https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-master/config.yml#L238-L267

**Comment by sdodson** [comment]
@spinolacastro what version of ansible is this?

**Comment by spinolacastro** [comment]
Hi, i'ts ansible 1.9.4

2015-12-09 13:56 GMT-03:00 Scott Dodson <notifications@github.com>:

**Comment by abutcher** [comment]
@spinolacastro Can you try the attached PR out?

**Comment by spinolacastro** [comment]
@abutcher Working as expected with this patch. Thank you!

**Comment by abutcher** [comment]
Cool

**Comment by abutcher** [comment]
@brenton This one can be closed.
