### ISSUE TITLE
README_AWS needs more details re ec2_vpc_subnet config setting

### ISSUE THREAD

**Issue by ryanj** [openshift/openshift-ansible#1053]
I'm not sure how to configure this setting, and leaving it unconfigured returns the following error:

```
TASK: [Launch instance(s)] **************************************************** 
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/ryanj/.ansible/tmp/ansible-tmp-1449789386.18-6964540182561/ec2", line 3070, in <module>
    main()
  File "/home/ryanj/.ansible/tmp/ansible-tmp-1449789386.18-6964540182561/ec2", line 1249, in main
    (instance_dict_array, new_instance_ids, changed) = create_instances(module, ec2, vpc)
  File "/home/ryanj/.ansible/tmp/ansible-tmp-1449789386.18-6964540182561/ec2", line 792, in create_instances
    vpc_id = vpc.get_all_subnets(subnet_ids=[vpc_subnet_id])[0].vpc_id
  File "/usr/lib/python2.7/site-packages/boto/vpc/__init__.py", line 1153, in get_all_subnets
    return self.get_list('DescribeSubnets', params, [('item', Subnet)])
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidSubnetID.NotFound</Code><Message>The subnet ID 'example' does not exist</Message></Error></Errors><RequestID>de6c4fee-de52-4d26-b578-60b4f0a770d6</RequestID></Response>


FATAL: all hosts have already failed -- aborting
```

**Comment by ryanj** [comment]
oops, accidentally posted to the wrong repo. This issue was for [2015-Middleware-Keynote/demo-ansible](https://github.com/2015-Middleware-Keynote/demo-ansible)

**Comment by detiber** [comment]
@ryanj The ec2_vpc_subnet needs to be a pre-existing subnet id (subnet-xxxxxxxx). It should not be needed if using ec2 classic or if your account is configured with a default vpc though. 

I'm not sure where the value `example` is coming from on your invocation though.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
