### ISSUE TITLE
Unexpected Exception (in 'get openshift_current_version' task) using atomic installer v3.11.0

### ISSUE THREAD

**Issue by alanbchristie** [openshift/openshift-ansible#10626]
#### Description

Installing a fresh 3.11.0 on AWS using the atomic installer (using the very latest pushed image for v3.11.0) I am unable to get past the following ansible-playbook exception thrown from the `get openshift_current_version` task in the `prerequisites` play.

Same problem with v3.11.1 although that container image is much older than v3.11.0.

```
ERROR! Unexpected Exception, this is probably a bug: update expected at most 1 arguments, got 2
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 156, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 292, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 323, in run
    results += self._wait_on_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 674, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 117, in inner
    results = func(self, iterator, one_pass=one_pass, max_passes=max_passes)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 606, in _process_pending_results
    self._variable_manager.set_host_facts(target_host, result_item['ansible_facts'].copy())
  File "/usr/lib/python2.7/site-packages/ansible/vars/manager.py", line 597, in set_host_facts
    self._fact_cache.update(host.name, facts)
TypeError: update expected at most 1 arguments, got 2
```
##### Version

Please put the following version information in the code block
indicated below.

```
ansible 2.6.7
  config file = None
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### Steps To Reproduce
1. Run the atomic installer for the prerequisites as documented in the official page (https://docs.openshift.com/container-platform/3.11/install/running_install.html). specifically..

```
atomic install --system \
    --storage=ostree \
    --set INVENTORY_FILE=/home/centos/orchestrator/openshift/inventories/aws-frankfurt-3-11/inventory \
    --set PLAYBOOK_FILE=/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml \
    --set OPTS="-vvv" \
    docker.io/openshift/origin-ansible:v3.11.0
```

##### Expected Results
I do not expect to see playbook exceptions.

##### Observed Results
I see a playbook exception.

```
ERROR! Unexpected Exception, this is probably a bug: update expected at most 1 arguments, got 2
```

##### Additional Information
The output of the task is:

```
task path: /usr/share/ansible/openshift-ansible/playbooks/init/cluster_facts.yml:10
Wednesday 07 November 2018  15:27:29 +0000 (0:00:04.534)       0:00:18.789 **** 
Using module file /usr/share/ansible/openshift-ansible/roles/lib_utils/library/get_current_openshift_version.py
Using module file /usr/share/ansible/openshift-ansible/roles/lib_utils/library/get_current_openshift_version.py
<ip-10-0-1-4.eu-central-1.compute.internal> ESTABLISH SSH CONNECTION FOR USER: centos
<ip-10-0-1-21.eu-central-1.compute.internal> ESTABLISH SSH CONNECTION FOR USER: centos
<ip-10-0-1-21.eu-central-1.compute.internal> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r ip-10-0-1-21.eu-central-1.compute.internal '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-pluckhfxwhrovormizjchpyfvuwpgadg; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<ip-10-0-1-4.eu-central-1.compute.internal> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r ip-10-0-1-4.eu-central-1.compute.internal '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-eagbhqeeohwcdlsnmeuvolkajkjrjxef; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Using module file /usr/share/ansible/openshift-ansible/roles/lib_utils/library/get_current_openshift_version.py
Using module file /usr/share/ansible/openshift-ansible/roles/lib_utils/library/get_current_openshift_version.py
<ip-10-0-1-18.eu-central-1.compute.internal> ESTABLISH SSH CONNECTION FOR USER: centos
<ip-10-0-1-17.eu-central-1.compute.internal> ESTABLISH SSH CONNECTION FOR USER: centos
<ip-10-0-1-17.eu-central-1.compute.internal> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r ip-10-0-1-17.eu-central-1.compute.internal '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-htuueuzsftnvjwyqvokrjbxdrlrlgvyi; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<ip-10-0-1-18.eu-central-1.compute.internal> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r ip-10-0-1-18.eu-central-1.compute.internal '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-epyqymrckfgkwbwvjxiaypbnjizohqvk; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
Escalation succeeded
Escalation succeeded
Escalation succeeded
<ip-10-0-1-18.eu-central-1.compute.internal> (0, '\n{"invocation": {"module_args": {"deployment_type": "origin"}}, "changed": false, "ansible_facts": {}}\n', '')
<ip-10-0-1-17.eu-central-1.compute.internal> (0, '\n{"invocation": {"module_args": {"deployment_type": "origin"}}, "changed": false, "ansible_facts": {}}\n', '')
ERROR! Unexpected Exception, this is probably a bug: update expected at most 1 arguments, got 2
```

**Comment by alanbchristie** [comment]
OK, still stuck on 3.9 and returned to trying to install 3.11 today and I'm still getting this error and therefore cannot install 3.11 on AWS. As a brief reminder I get this error at the **get openshift_current_version** playbook stage on a clean/new cluster: -

`ERROR! Unexpected Exception, this is probably a bug: update expected at most 1 arguments, got 2`

Clearly there is no _current_ version so can _anyone_ suggest a solution to this?

**Comment by eelcoh** [comment]
Same here. Same output at Task get openshift_current_version for containers 3.11, 3.11.0 and also 4.0.0.

**Comment by ffroggy** [comment]
I'm getting this error as well on RHEL 7.5 using the atomic installer

**Comment by phlbrz** [comment]
I'm looking for a similar problem.

* Playbook:

`sudo ansible-playbook -i inventory.ini /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_11/upgrade_nodes.yml -vvvv`

* Error Log:

```
Failure summary:
  1. Hosts:    host.domain.com
     Play:     Verify masters are already upgraded
     Task:     fail
     Message:  The conditional check 'not (openshift_current_version | default('0.0') is match(openshift_version))' failed. The error was: Unexpected templating type error occurred on ({% if not (openshift_current_version | default('0.0') is match(openshift_version)) %} True {% else %} False {% endif %}): first argument must be string or compiled pattern
               
               The error appears to have been in '/usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/upgrades/pre/config.yml': line 59, column 5, but may
               be elsewhere in the file depending on the exact syntax problem.
               
               The offending line appears to be:
               
                 tasks:
                 - fail: msg="Master running {{ openshift_current_version }} must be upgraded to {{ openshift_version }} before node upgrade can be run."
                   ^ here
               We could be wrong, but this one looks like it might be an issue with
               missing quotes.  Always quote template expression brackets when they
               start a value. For instance:
               
                   with_items:
                     - {{ foo }}
               
               Should be written as:
               
                   with_items:
                     - "{{ foo }}"
```

**Comment by phlbrz** [comment]
> I'm looking for a similar problem.
> 
> * Playbook:
> 
> `sudo ansible-playbook -i inventory.ini /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_11/upgrade_nodes.yml -vvvv`
> 
> * Error Log:
> 
> ```
> Failure summary:
>   1. Hosts:    host.domain.com
>      Play:     Verify masters are already upgraded
>      Task:     fail
>      Message:  The conditional check 'not (openshift_current_version | default('0.0') is match(openshift_version))' failed. The error was: Unexpected templating type error occurred on ({% if not (openshift_current_version | default('0.0') is match(openshift_version)) %} True {% else %} False {% endif %}): first argument must be string or compiled pattern
>                
>                The error appears to have been in '/usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/upgrades/pre/config.yml': line 59, column 5, but may
>                be elsewhere in the file depending on the exact syntax problem.
>                
>                The offending line appears to be:
>                
>                  tasks:
>                  - fail: msg="Master running {{ openshift_current_version }} must be upgraded to {{ openshift_version }} before node upgrade can be run."
>                    ^ here
>                We could be wrong, but this one looks like it might be an issue with
>                missing quotes.  Always quote template expression brackets when they
>                start a value. For instance:
>                
>                    with_items:
>                      - {{ foo }}
>                
>                Should be written as:
>                
>                    with_items:
>                      - "{{ foo }}"
> ```

Hello all, 
I managed the problem changing some var in my inventory. 
I didn't find anything and the example in documentation and github aren't specific about it.

My inventory was:
openshift_release=3.11
openshift_version=3.11
openshift_image_tag=v3.11
openshift_pkg_version=-3.11.*

I added ' ' to the values:
openshift_release='3.11'
openshift_version='3.11'
openshift_image_tag='v3.11'
openshift_pkg_version='-3.11.*'

It solved my problem.
