### ISSUE TITLE
byo 3.7 to 3.9 upgrade results in origin-master 3.10 rpm installed which breaks upgrade

### ISSUE THREAD

**Issue by cameronbraid** [openshift/openshift-ansible#10773]
running playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade.yml results in upgrading the first master to origin-master-3.10 which then fails to restart causing the upgrade to halt.  

This should instead upgrade to origin-master 3.9 rpm.

**linux version**
CentOS Linux release 7.5.1804 (Core) 

**docker version**
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-75.git8633870.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      8633870/1.13.1
 Built:           Fri Sep 28 19:45:08 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-75.git8633870.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      8633870/1.13.1
 Built:           Fri Sep 28 19:45:08 2018
 OS/Arch:         linux/amd64
 Experimental:    false

**oc version**
oc v3.7.2+cd74924-1
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://node04-2018:8443
openshift v3.7.2+cd74924-1
kubernetes v1.7.6+a08f5eeb62

**Ansible version**
v2.4.6.0-1

**openshift-ansible version** 
3.9.54-1

*inventory file*
```
[OSEv3:children]
masters
etcd
nodes
glusterfs

[OSEv3:vars]
openshift_master_upgrade_pre_hook=/root/origin-cluster/upgade-pre_master.yml
openshift_master_upgrade_post_hook=/root/origin-cluster/upgade-post_master.yml
ansible_ssh_user=root
deployment_type=origin
docker_version=1.13.1
openshift_enable_service_catalog=false
os_firewall_use_firewalld=True
osn_storage_plugin_deps=['glusterfs']
osm_cluster_network_cidr=10.128.0.0/14
openshift_hosted_manage_router=false
openshift_logging_install_logging=false
openshift_master_cluster_method=native
openshift_master_cluster_hostname=master-private-2018-456.drivenow.com.au
openshift_master_cluster_public_hostname=master-2018-456.drivenow.com.au
osm_controller_lease_ttl=10
openshift_master_named_certificates=[{"certfile":"/root/origin-cluster-2018/drivenow.com.au.crt","keyfile":"/root/origin-cluster-2018/drivenow.com.au.key", "cafile":"/root/origin-cluster-2018/thawte_Primary_Root_CA.pem", "names": ["*.drivenow.com.au", "drivenow.com.au"]}]
openshift_master_overwrite_named_certificates=true
openshift_master_identity_providers=[removed]
openshift_master_htpasswd_users=[removed]
openshift_master_default_subdomain=drivenow.com.au
openshift_metrics_install_metrics=true
openshift_metrics_hawkular_hostname=hawkular-metrics-2018-456.drivenow.com.au
openshift_install_examples=false
openshift_examples_load_db_templates=false
openshift_examples_load_quickstarts=false
openshift_examples_load_centos=false
openshift_examples_load_rhel=false
openshift_node_kubelet_args={'image-gc-high-threshold': ['80'], 'image-gc-low-threshold': ['60']}

[masters]
node04-2018
node05-2018
node06-2018

[etcd]
node04-2018
node05-2018
node06-2018

[nodes]
node04-2018 node=True storage=True master=True openshift_ip=10.118.56.23 openshift_hostname=node04-2018 openshift_public_hostname=node04-2018.drivenow.com.au openshift_public_ip=168.1.85.42 openshift_schedulable=true openshift_node_labels="{'region':'primary', 'node':'node04'}"
node05-2018 node=True storage=True master=True openshift_ip=10.118.56.13 openshift_hostname=node05-2018 openshift_public_hostname=node05-2018.drivenow.com.au openshift_public_ip=168.1.85.37 openshift_schedulable=true openshift_node_labels="{'region':'primary', 'node':'node05'}"
node06-2018 node=True storage=True master=True openshift_ip=10.118.56.4 openshift_hostname=node06-2018 openshift_public_hostname=node06-2018.drivenow.com.au openshift_public_ip=168.1.85.46 openshift_schedulable=true openshift_node_labels="{'region':'primary', 'node':'node06'}"

[glusterfs]
node04-2018 glusterfs_devices="[ '/dev/xvdc2' ]"
node05-2018 glusterfs_devices="[ '/dev/xvdc2' ]"
node06-2018 glusterfs_devices="[ '/dev/xvdc2' ]"

[app-nodes]
node04-2018
node05-2018
node06-2018
```

I tried the same upgrade after adding the following vars :

```
[OSEv3:vars]
openshift_release=3.9
openshift_pkg_version=3.9
openshift_image_tag=3.9
```

However that resulted in the playbook failing with 

```
  1. Hosts:    node04-2018, node05-2018, node06-2018
     Play:     OpenShift Health Checks
     Task:     Run health checks (upgrade)
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               expected a character buffer object
               Traceback (most recent call last):
                 File "/root/openshift-ansible/roles/openshift_health_checker/action_plugins/openshift_health_check.py", line 222, in run_check
                   result = check.run()
                 File "/root/openshift-ansible/roles/openshift_health_checker/openshift_checks/docker_image_availability.py", line 108, in run
                   required_images = self.required_images()
                 File "/root/openshift-ansible/roles/openshift_health_checker/openshift_checks/docker_image_availability.py", line 172, in required_images
                   required.add(image_url.replace("${component}", suffix).replace("${version}", image_tag))
               TypeError: expected a character buffer object
```

I then tried with just the original inventor plus

```
[OSEv3:vars]
openshift_release=3.9
```

and get this error
```
fatal: [node04-2018]: FAILED! => {"changed": false, "failed": true, "msg": "Package 'origin-3.8*' not found"}
```

Which kind of makes sense.

Is there a way to cause the upgrader to ignore 3.10 rpms ?

**Comment by cameronbraid** [comment]
I found a workaround

copy `CentOS-OpenShift-Origin39.repo.j2` over `CentOS-OpenShift-Origin.repo.j2` and edit `CentOS-OpenShift-Origin.repo.j2` to change 39 to 38

**Comment by cameronbraid** [comment]
Another workaround is to exclude origin-3.10 from yum on all nodes before running the upgrade playbook

*/etc/yum.conf*
```exclude=  origin-*3.10* ```
