### ISSUE TITLE
OpenShift Install uses MD5 for hawkular metrics

### ISSUE THREAD

**Issue by jvitray** [openshift/openshift-ansible#10949]
#### Description

When a STIG is applied to the node instances which does not support MD5, the deploy_cluster playbook fails at TASK [openshift_metrics : generate htpasswd file for hawkular metrics].

This issue is a request to support SHA256 for this encryption.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### Steps To Reproduce
1.ansible-playbook -i ansible-hosts-3.11.16 /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

##### Expected Results
Describe what you expected to happen.

```
Success
```

##### Observed Results
Describe what is actually happening.

```
**Error Message:**
TASK [openshift_metrics : generate htpasswd file for hawkular metrics] *********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
fatal: [ip-172-16-31-225.ec2.internal -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ObQ7NI/ansible_module_htpasswd.py\", line 102, in <module>\n    from passlib.apache import HtpasswdFile, htpasswd_context\n  File \"/usr/lib/python2.7/site-packages/passlib/apache.py\", line 17, in <module>\n    from passlib.hash import htdigest\n  File \"/usr/lib/python2.7/site-packages/passlib/registry.py\", line 37, in __getattr__\n    handler = get_crypt_handler(attr, None)\n  File \"/usr/lib/python2.7/site-packages/passlib/registry.py\", line 340, in get_crypt_handler\n    mod = __import__(modname, fromlist=[modattr], level=0)\n  File \"/usr/lib/python2.7/site-packages/passlib/handlers/digests.py\", line 73, in <module>\n    hex_md5     = create_hex_hash(hashlib.md5,      \"md5\")\n  File \"/usr/lib/python2.7/site-packages/passlib/handlers/digests.py\", line 56, in create_hex_hash\n    h = hash()\nValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

PLAY RECAP *********************************************************************
ip-172-16-30-219.ec2.internal : ok=121  changed=63   unreachable=0    failed=0   
ip-172-16-30-22.ec2.internal : ok=121  changed=63   unreachable=0    failed=0   
ip-172-16-30-244.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
ip-172-16-30-45.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
ip-172-16-30-52.ec2.internal : ok=304  changed=150  unreachable=0    failed=0   
ip-172-16-31-166.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
ip-172-16-31-191.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
ip-172-16-31-206.ec2.internal : ok=121  changed=63   unreachable=0    failed=0   
ip-172-16-31-225.ec2.internal : ok=773  changed=346  unreachable=0    failed=1   
ip-172-16-31-74.ec2.internal : ok=122  changed=63   unreachable=0    failed=0   
ip-172-16-32-228.ec2.internal : ok=121  changed=63   unreachable=0    failed=0   
ip-172-16-32-235.ec2.internal : ok=121  changed=63   unreachable=0    failed=0   
ip-172-16-32-29.ec2.internal : ok=304  changed=150  unreachable=0    failed=0   
ip-172-16-32-30.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
ip-172-16-32-76.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
localhost                  : ok=12   changed=0    unreachable=0    failed=0   

INSTALLER STATUS ***************************************************************
Initialization               : Complete (0:01:49)
Health Check                 : Complete (0:00:24)
Node Bootstrap Preparation   : Complete (0:06:14)
etcd Install                 : Complete (0:01:18)
Master Install               : Complete (0:06:22)
Master Additional Install    : Complete (0:01:01)
Node Join                    : Complete (0:01:31)
GlusterFS Install            : Complete (0:10:19)
Hosted Install               : Complete (0:01:13)
Cluster Monitoring Operator  : Complete (0:01:19)
Web Console Install          : Complete (0:00:35)
Console Install              : Complete (0:00:29)
Metrics Install              : In Progress (0:00:26)
	This phase can be restarted by running: playbooks/openshift-metrics/config.yml

Failure summary:

  1. Hosts:    ip-172-16-31-225.ec2.internal
     Play:     OpenShift Metrics
     Task:     generate htpasswd file for hawkular metrics
     Message:  MODULE FAILURE
Failure: Running deploy_cluster playbook!

**Verbose Error Message:**

TASK [openshift_metrics : generate htpasswd file for hawkular metrics] *********
task path: /usr/share/ansible/openshift-ansible/roles/openshift_metrics/tasks/generate_hawkular_certificates.yaml:27
Using module file /usr/lib/python2.7/site-packages/ansible/modules/web_infrastructure/htpasswd.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible__qN2Lw/ansible_module_htpasswd.py", line 102, in <module>
    from passlib.apache import HtpasswdFile, htpasswd_context
  File "/usr/lib/python2.7/site-packages/passlib/apache.py", line 17, in <module>
    from passlib.hash import htdigest
  File "/usr/lib/python2.7/site-packages/passlib/registry.py", line 37, in __getattr__
    handler = get_crypt_handler(attr, None)
  File "/usr/lib/python2.7/site-packages/passlib/registry.py", line 340, in get_crypt_handler
    mod = __import__(modname, fromlist=[modattr], level=0)
  File "/usr/lib/python2.7/site-packages/passlib/handlers/digests.py", line 73, in <module>
    hex_md5     = create_hex_hash(hashlib.md5,      "md5")
  File "/usr/lib/python2.7/site-packages/passlib/handlers/digests.py", line 56, in create_hex_hash
    h = hash()
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
fatal: [ip-172-16-30-76.ec2.internal -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible__qN2Lw/ansible_module_htpasswd.py\", line 102, in <module>\n    from passlib.apache import HtpasswdFile, htpasswd_context\n  File \"/usr/lib/python2.7/site-packages/passlib/apache.py\", line 17, in <module>\n    from passlib.hash import htdigest\n  File \"/usr/lib/python2.7/site-packages/passlib/registry.py\", line 37, in __getattr__\n    handler = get_crypt_handler(attr, None)\n  File \"/usr/lib/python2.7/site-packages/passlib/registry.py\", line 340, in get_crypt_handler\n    mod = __import__(modname, fromlist=[modattr], level=0)\n  File \"/usr/lib/python2.7/site-packages/passlib/handlers/digests.py\", line 73, in <module>\n    hex_md5     = create_hex_hash(hashlib.md5,      \"md5\")\n  File \"/usr/lib/python2.7/site-packages/passlib/handlers/digests.py\", line 56, in create_hex_hash\n    h = hash()\nValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

PLAY RECAP *********************************************************************
ip-172-16-30-125.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
ip-172-16-30-172.ec2.internal : ok=121  changed=63   unreachable=0    failed=0   
ip-172-16-30-177.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
ip-172-16-30-22.ec2.internal : ok=121  changed=63   unreachable=0    failed=0   
ip-172-16-30-76.ec2.internal : ok=774  changed=346  unreachable=0    failed=1   
ip-172-16-31-240.ec2.internal : ok=121  changed=63   unreachable=0    failed=0   
ip-172-16-31-33.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
ip-172-16-31-4.ec2.internal : ok=121  changed=63   unreachable=0    failed=0   
ip-172-16-31-55.ec2.internal : ok=304  changed=150  unreachable=0    failed=0   
ip-172-16-31-90.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
ip-172-16-32-140.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
ip-172-16-32-165.ec2.internal : ok=117  changed=61   unreachable=0    failed=0   
ip-172-16-32-245.ec2.internal : ok=121  changed=63   unreachable=0    failed=0   
ip-172-16-32-40.ec2.internal : ok=121  changed=63   unreachable=0    failed=0   
ip-172-16-32-91.ec2.internal : ok=304  changed=150  unreachable=0    failed=0   
localhost                  : ok=12   changed=0    unreachable=0    failed=0   

INSTALLER STATUS ***************************************************************
Initialization               : Complete (0:02:04)
Health Check                 : Complete (0:00:25)
Node Bootstrap Preparation   : Complete (0:07:10)
etcd Install                 : Complete (0:01:28)
Master Install               : Complete (0:06:53)
Master Additional Install    : Complete (0:01:01)
Node Join                    : Complete (0:01:39)
GlusterFS Install            : Complete (0:10:20)
Hosted Install               : Complete (0:01:22)
Cluster Monitoring Operator  : Complete (0:01:19)
Web Console Install          : Complete (0:00:38)
Console Install              : Complete (0:00:28)
Metrics Install              : In Progress (0:00:26)
	This phase can be restarted by running: playbooks/openshift-metrics/config.yml

Failure summary:

  1. Hosts:    ip-172-16-30-76.ec2.internal
     Play:     OpenShift Metrics
     Task:     generate htpasswd file for hawkular metrics
     Message:  MODULE FAILURE
Failure: Running deploy_cluster playbook!

```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* RHEL 7.2
* Inventory file:

```
# This is an OpenShift-Ansible host inventory


[OSEv3:children]
masters
etcd
nodes
glusterfs
glusterfs_registry
compute #custom group
infra #custom group
#new_nodes

[OSEv3:vars]
###############################################################################
# Common/ Required configuration variables follow                             #
###############################################################################
# Specify the deployment type. Valid values are origin and openshift-enterprise.
openshift_deployment_type=openshift-enterprise
#openshift_deployment_type=origin

# Default subdomain to use for exposed routes, you should have wildcard dns
# for *.apps.example.com that points at your infra nodes which will run
# your router.  The installer we verify the wildcard DNS entry
openshift_master_default_subdomain=ocp-james-apps.ampsight.lan

# Set cluster_hostname to point at your Internal load balancer
# Used internally for node to master communications
openshift_master_cluster_hostname=internal-ocp-james-OpenShif-V6I5DCHBMG26-2120571363.us-east-1.elb.amazonaws.com

# Set to the DNS CNAME of the master public ELB,
# Used to external access the web conole URL
openshift_master_cluster_public_hostname=ocp-james-masters.ampsight.lan

# SSH user, this user should allow ssh based auth without requiring a
# password.
ansible_ssh_user=ansible

# Ansible_become must be set to true and the
# useris configured via cloud-init for passwordless sudo on all nodes
ansible_become=true

###############################################################################
# Additional configuration variables follow                                   #
###############################################################################
# Debug level for all OpenShift components (Defaults to 2)
# 0 to log errors and warnings only
# 2 to log normal information (This is the default level.)
# 4 to log debugging-level information
# 6 to log API-level debugging information (request / response)
# 8 to log body-level API debugging information
debug_level=2

# Specify an exact container image tag to install or configure.
# WARNING: This value will be used for all hosts in containerized environments, even those that have another version installed.
# This could potentially trigger an upgrade and downtime, so be careful with modifying this value after the cluster is set up.
openshift_image_tag=v3.11.16

# Cluster Image Source (bootstrap registry) configuration
# openshift-enterprise default is 'registry.redhat.io/openshift3/ose-${component}:${version}'
# origin default is 'docker.io/openshift/origin-${component}:${version}'
# Need to set to the  boot-strap registry for a disconnected installation
oreg_url='172.16.30.27:5000/openshift3/ose-${component}:${version}'

# If oreg_url points to a registry other than registry.redhat.io we can
# modify image streams to point at that registry by setting the following to true
openshift_examples_modify_imagestreams=true

# If oreg_url points to a registry requiring authentication, provide the following:
# oreg_auth_user=some_user
# oreg_auth_pass should be generated from running docker login.
# oreg_auth_password='*****'

# Add insecure and blocked registries to global docker configuration
openshift_docker_insecure_registries='172.16.30.27:5000'
openshift_docker_blocked_registries='registry.access.redhat.com'

# Specify a list of block devices to be formatted and mounted on the nodes
# during prerequisites.yml. For each hash, "device", "path", "filesystem" are
# required. To add devices only on certain classes of node, redefine
# container_runtime_extra_storage as a group var.
#container_runtime_extra_storage='[{"device":"/dev/vdc","path":"/var/lib/origin/openshift.local.volumes","filesystem":"xfs","options":"gquota"}]'

# Cloud Provider Configuration
openshift_cloudprovider_kind=aws

# This variable is a cluster identifier unique to the AWS Availability Zone.
# Using this avoids potential issues in Amazon Web Services (AWS) with
# multiple zones or multiple clusters
openshift_clusterid=ocp-james

# Configure the multi-tenant SDN plugin (default is 'redhat/openshift-ovs-subnet')
os_sdn_network_plugin_name=redhat/openshift-ovs-multitenant

# Firewall Configuration
os_firewall_use_firewalld=True

###############################################################################
# Master Node configuration variables follow                                  #
###############################################################################

# Native high availbility cluster method with ELB.
# Installer assumes that a load balancer has
# been preconfigured and is healthly. For installation the value of
# openshift_master_cluster_hostname must resolve to the load balancer
openshift_master_cluster_method=native


# Authentication via GEOAxIS,  RH SSO,  & htpasswd
openshift_master_identity_providers=[{'name':'GEOAxIS', 'login':'true', 'challenge':'false', 'mappingMethod':'add', 'kind':'OpenIDIdentityProvider', 'client_id':'openshift', 'client_secret':'a123bb4c-5d67-8901-2345-67ee8fg90h12', 'urls':{'authorize':'https://sso.ocp.ampsight.io/auth/realms/OpenShift/protocol/openid-connect/auth?kc_idp_hint=saml', 'token':'https://sso.ocp.ampsight.io/auth/realms/OpenShift/protocol/openid-connect/token', 'userInfo':'https://sso.ocp.ampsight.io/auth/realms/OpenShift/protocol/openid-connect/userinfo'}, 'claims':{'id':['sub'], 'preferredUsername':['preferred_username'], 'name':['name'], 'email':['email']}},  {'name':'RHSSO', 'login':'true', 'challenge':'false', 'mappingMethod':'add', 'kind':'OpenIDIdentityProvider', 'client_id':'openshift', 'client_secret':'a123bb4c-5d67-8901-2345-67ee8fg90h12', 'urls':{'authorize':'https://sso.ocp.ampsight.io/auth/realms/OpenShift/protocol/openid-connect/auth', 'token':'https://sso.ocp.ampsight.io/auth/realms/OpenShift/protocol/openid-connect/token', 'userInfo':'https://sso.ocp.ampsight.io/auth/realms/OpenShift/protocol/openid-connect/userinfo'}, 'claims':{'id':['sub'], 'preferredUsername':['preferred_username'], 'name':['name'], 'email':['email']}},  {'name': 'htpasswd', 'login':'true', 'challenge':'true', 'kind':'HTPasswdPasswordIdentityProvider'}]

openshift_master_openid_ca_file=/etc/ssl/certs/ca-bundle.crt
# so the CA cert files at the autogenerated paths
#     /etc/origin/master/<OpenID provider name>_openid_ca.crt
#   are created & can be used to verify the OpenID IdP HTTPS certificate

openshift_master_htpasswd_users={'admin':'$2y$05$za.EyUP7JWvY0Jb3yUFcde7Gt9Vjzl5Caeq8ed.KqmaoILyEy5JOa'}


# Override the default oauth tokenConfig settings:
# openshift_master_access_token_max_seconds=86400
# openshift_master_auth_token_max_seconds=500

# Configure master API and console ports.
openshift_master_api_port=443
openshift_master_console_port=443

# Session options
# openshift_master_session_name=ssn
# openshift_master_session_max_seconds=3600

# Enable API service auditing
# openshift_master_audit_config={"enabled": true}

# In case you want more advanced setup for the auditlog you can
# use this line.
# The directory in "auditFilePath" will be created if it's not
# exist
openshift_master_audit_config={"enabled": true, "auditFilePath": "/var/lib/origin/audit-ocp.log", "maximumFileRetentionDays": "14", "maximumFileSizeMegabytes": "500", "maximumRetainedFiles": "5"}

# This variable enables TLS bootstrapping auto approval,
# which allows nodes to automatically join the cluster
# when provided a bootstrap credential.
# Set to true if you will enable the cluster auto-scaler
# on an Amazon Web Services (AWS) cluster. The default value is false.
# openshift_master_bootstrap_auto_approve=true

# masterConfig.volumeConfig.dynamicProvisioningEnabled enabled by default
openshift_master_dynamic_provisioning_enabled=True

# Configurate the web console to log the user out automatically
# after a period of inactivity. Must be a whole number greater
# than or equal to 5, or 0 to disable the feature. Defaults to 0 (disabled).
openshift_web_console_inactivity_timeout_minutes=10

# Sets extensions.stylesheetURLs in the web console configuration.
# See Loading Extension Scripts and Stylesheets for details. Example value:
# ['https://example.com/styles/logo.css','https://example.com/styles/custom-styles.css']
#openshift_web_console_extension_stylesheet_urls


###############################################################################
# CNS variables follow                                                        #
###############################################################################
osn_storage_plugin_deps=['ceph','glusterfs']

# TODO Is this needed since we don't version the images?
openshift_storage_glusterfs_image="172.16.30.27:5000/rhgs3/rhgs-server-rhel7"
openshift_storage_glusterfs_block_image="172.16.30.27:5000/rhgs3/rhgs-gluster-block-prov-rhel7"
openshift_storage_glusterfs_s3_image="172.16.30.27:5000/rhgs3/rhgs-s3-server-rhel7"
openshift_storage_glusterfs_heketi_image="172.16.30.27:5000/rhgs3/rhgs-volmanager-rhel7"


openshift_storage_glusterfs_name=storage
openshift_storage_glusterfs_namespace=app-storage
openshift_storage_glusterfs_storageclass=true
# TODO should this be true ?
openshift_storage_glusterfs_storageclass_default=false
openshift_storage_glusterfs_block_deploy=true
openshift_storage_glusterfs_block_host_vol_create=true
openshift_storage_glusterfs_block_host_vol_size=200
openshift_storage_glusterfs_block_storageclass=true
openshift_storage_glusterfs_block_storageclass_default=false

# When heketi is native, this sets the hostname portion of the final heketi route URL
# openshift_storage_glusterfs_heketi_url

# Deploy gluster-s3 service
# openshift_storage_glusterfs_s3_deploy=true

# NOTE: glusterfs_registry is storage for Infra-Nodes
# the name is a misnomor ?

# TODO change to infra
openshift_storage_glusterfs_registry_name=registry
openshift_storage_glusterfs_registry_namespace=infra-storage
openshift_storage_glusterfs_registry_storageclass=false
openshift_storage_glusterfs_registry_storageclass_default=false
openshift_storage_glusterfs_registry_block_deploy=true
openshift_storage_glusterfs_registry_block_host_vol_create=true
openshift_storage_glusterfs_registry_block_host_vol_size=200
openshift_storage_glusterfs_registry_block_storageclass=true
openshift_storage_glusterfs_registry_block_storageclass_default=false


###############################################################################
# OpenShift Registry variables follow                                         #
###############################################################################
# Manage the OpenShift Registry
openshift_hosted_manage_registry=true

# The route contains either a name that resolves to an infrastructure node
# where a router manages communication or the subdomain that you set as the
# default application subdomain wildcard value
# openshift_hosted_registry_routehost

openshift_hosted_registry_storage_kind=object
openshift_hosted_registry_storage_provider=s3
openshift_hosted_registry_storage_s3_bucket=jaguar-dev-open-shift-registry
openshift_hosted_registry_storage_s3_region=us-east-1
openshift_hosted_registry_storage_s3_chunksize=26214400
openshift_hosted_registry_storage_s3_rootdirectory=/ocp-james
openshift_hosted_registry_pullthrough=true
openshift_hosted_registry_acceptschema2=true
openshift_hosted_registry_enforcequota=true
#openshift_hosted_registry_storage_s3_regionendpoint=https://myendpoint.example.com/


# Manage the OpenShift Registry Console
openshift_hosted_manage_registry_console=true
# Override the console image prefix - TODO is this needed since its the default?
openshift_cockpit_deployer_prefix='172.16.30.27:5000/openshift3/'
# Override image version, defaults to latest for origin, vX.Y product version for enterprise
openshift_cockpit_deployer_version='v3.11.16'


###############################################################################
# Metrics variables follow                                                    #
###############################################################################
openshift_metrics_install_metrics=true
openshift_metrics_server_install=true

# Override metricsPublicURL in the master config for cluster metrics
# Defaults to "hawkular-metrics.{{openshift_master_default_subdomain}}"
#openshift_metrics_hawkular_hostname=hawkular-metrics.example.com

# cassandra_storage_type Use emptydir for ephemeral storage (for testing),
# pv to use persistent volumes (which need to be created before the installation)
# or dynamic for dynamic persistent volumes.
openshift_metrics_cassandra_storage_type=dynamic
openshift_metrics_storage_volume_size=20Gi

# Specify the StorageClass to be used for Metrics.
# This name is generated from the name of the target GlusterFS cluster
# (e.g., glusterfs-<name>-block).
openshift_metrics_cassandra_pvc_storage_class_name="glusterfs-registry-block"


openshift_metrics_hawkular_nodeselector={"node-role.kubernetes.io/infra":"true"}
openshift_metrics_cassandra_nodeselector={"node-role.kubernetes.io/infra":"true"}
openshift_metrics_heapster_nodeselector={"node-role.kubernetes.io/infra":"true"}

#  How many days metrics should be stored for.
#openshift_metrics_duration: 7
# How often metrics should be gathered.
#openshift_metrics_resolution: 30s

# openshift_metrics_hawkular_cert: ""
# openshift_metrics_hawkular_key: ""
# openshift_metrics_hawkular_ca: ""


###############################################################################
# Logging variables follow                                                    #
###############################################################################
openshift_logging_install_logging=true

openshift_logging_es_cluster_size=3
openshift_logging_es_nodeselector={"node-role.kubernetes.io/infra":"true"}
openshift_logging_kibana_nodeselector={"node-role.kubernetes.io/infra":"true"}
openshift_logging_curator_nodeselector={"node-role.kubernetes.io/infra":"true"}
openshift_logging_es_number_of_replicas=1


openshift_logging_es_pvc_dynamic=true
openshift_logging_es_pvc_size=10Gi
# Specify the StorageClass to be used for Logging.
# This name is generated from the name of the target GlusterFS cluster
# (e.g., glusterfs-<name>-block).
openshift_logging_es_pvc_storage_class_name="glusterfs-registry-block"


# Configure loggingPublicURL in the master config for aggregate logging, defaults
# to kibana.{{ openshift_master_default_subdomain }}
#openshift_logging_kibana_hostname=logging.apps.example.com


###############################################################################
# Service Catalog variables follow                                            #
###############################################################################
# Enable service catalog
openshift_enable_service_catalog=true

# Enable template service broker (requires service catalog to be enabled, above)
# template_service_broker_install=true
# openshift_service_catalog_image="registry.redhat.io/openshift3/ose-service-catalog:{{ openshift_image_tag }}"

###############################################################################
# Customize Console Banner                                                          #
###############################################################################
# Configure extension scripts for web console customization
# See: https://docs.openshift.com/enterprise/latest/install_config/web_console_customization.html#loading-custom-scripts-and-stylesheets
# openshift_web_console_extension_script_urls=['https://s3.amazonaws.com/jaguar-dev-james/open-shift/banner/topsecret.js']

# # Configure a custom login template in the master config
# # See: https://docs.openshift.com/enterprise/latest/install_config/web_console_customization.html#customizing-the-login-page
# openshift_master_oauth_templates={'login': '/etc/origin/master/login-template.html'}

###############################################################################
# Misc variables follow                                                       #
###############################################################################

# to enable custom certificates
# openshift_master_named_certificates=[{"certfile": "/root/letsencrypt/live/ocp.rhtps.io/cert.pem", "keyfile": "/root/letsencrypt/live/ocp.rhtps.io/privkey.pem", "names": ["ocp.rhtps.io","ocp-master.rhtps.io"], "cafile": "/root/letsencrypt/live/apps.rhtps.io/fullchain.pem"}]
# openshift_master_overwrite_named_certificates=true
# openshift_hosted_router_certificate={"certfile": "/root/letsencrypt/live/apps.rhtps.io/cert.pem", "keyfile": "/root/letsencrypt/live/apps.rhtps.io/privkey.pem", "cafile": "/root/letsencrypt/live/apps.rhtps.io/fullchain.pem"}

# to disable safety checks.
# openshift_disable_check=memory_availability,package_version,disk_availability

# PersistentLocalStorage
# If Persistent Local Storage is wanted, this boolean can be defined to True.
# This will create all necessary configuration to use persistent storage on nodes.
# openshift_persistentlocalstorage_enabled=False
# openshift_persistentlocalstorage_classes=[]
# openshift_persistentlocalstorage_path=/mnt/local-storage
# openshift_persistentlocalstorage_provisionner_image=quay.io/external_storage/local-volume-provisioner:v1.0.1

###############################################################################
# CloudForms Deployment                                                       #
###############################################################################
openshift_management_install_management=true
openshift_management_app_template=cfme-template

# if you change openshift_management_project you must also
# change the project name create above to ensure the images
# are available in the right location
openshift_management_project=cloudforms46
openshift_management_storage_class=cloudprovider
openshift_management_username=admin
openshift_management_password=******

# Over ride all the image streams referenced in the templates
openshift_management_template_parameters={"MEMCACHED_IMG_NAME":"172.16.30.27:5000/cloudforms46/cfme-openshift-memcached","FRONTEND_APPLICATION_IMG_NAME":"172.16.30.27:5000/cloudforms46/cfme-openshift-app-ui","BACKEND_APPLICATION_IMG_NAME":"172.16.30.27:5000/cloudforms46/cfme-openshift-app","POSTGRESQL_IMG_NAME":"172.16.30.27:5000/cloudforms46/cfme-openshift-postgresql","ANSIBLE_IMG_NAME":"172.16.30.27:5000/cloudforms46/cfme-openshift-embedded-ansible","HTTPD_IMG_NAME":"172.16.30.27:5000/cloudforms46/cfme-openshift-httpd"}

openshift_node_groups=[{'name': 'node-config-master', 'labels': ['node-role.kubernetes.io/master=true']}, {'name': 'node-config-infra', 'labels': ['node-role.kubernetes.io/infra=true']}, {'name': 'node-config-compute', 'labels': ['node-role.kubernetes.io/compute=true']}, {'name': 'node-config-compute-storage', 'labels': ['node-role.kubernetes.io/storage=true']}, {'name': 'node-config-infra-storage', 'labels': ['node-role.kubernetes.io/storage=true']}]

[masters]
ip-172-16-30-214.ec2.internal
ip-172-16-31-215.ec2.internal


ip-172-16-32-177.ec2.internal

[etcd]
ip-172-16-30-214.ec2.internal
ip-172-16-31-215.ec2.internal


ip-172-16-32-177.ec2.internal

[nodes]
ip-172-16-30-214.ec2.internal openshift_node_group_name='node-config-master' openshift_schedulable=true
ip-172-16-31-215.ec2.internal openshift_node_group_name='node-config-master' openshift_schedulable=true
ip-172-16-32-177.ec2.internal openshift_node_group_name='node-config-master' openshift_schedulable=true
ip-172-16-32-137.ec2.internal openshift_node_group_name='node-config-infra'
ip-172-16-31-29.ec2.internal openshift_node_group_name='node-config-infra'
ip-172-16-30-93.ec2.internal openshift_node_group_name='node-config-infra'
ip-172-16-32-101.ec2.internal openshift_node_group_name='node-config-compute'
ip-172-16-30-25.ec2.internal openshift_node_group_name='node-config-compute'
ip-172-16-31-207.ec2.internal openshift_node_group_name='node-config-compute'
ip-172-16-31-248.ec2.internal openshift_node_group_name='node-config-infra-storage'
ip-172-16-30-98.ec2.internal openshift_node_group_name='node-config-infra-storage'
ip-172-16-32-165.ec2.internal openshift_node_group_name='node-config-infra-storage'
ip-172-16-32-127.ec2.internal openshift_node_group_name='node-config-compute-storage'
ip-172-16-31-200.ec2.internal openshift_node_group_name='node-config-compute-storage'
ip-172-16-30-139.ec2.internal openshift_node_group_name='node-config-compute-storage'


[infra]


ip-172-16-32-137.ec2.internal
ip-172-16-31-29.ec2.internal
ip-172-16-30-93.ec2.internal

[compute]

ip-172-16-32-101.ec2.internal

ip-172-16-30-25.ec2.internal
ip-172-16-31-207.ec2.internal

[glusterfs]
ip-172-16-32-127.ec2.internal glusterfs_devices='["/dev/xvdd","/dev/xvde"]'
ip-172-16-31-200.ec2.internal glusterfs_devices='["/dev/xvdd","/dev/xvde"]'
ip-172-16-30-139.ec2.internal glusterfs_devices='["/dev/xvdd","/dev/xvde"]'


[glusterfs_registry]
ip-172-16-31-248.ec2.internal glusterfs_devices='["/dev/xvdd","/dev/xvde"]'
ip-172-16-30-98.ec2.internal glusterfs_devices='["/dev/xvdd","/dev/xvde"]'
ip-172-16-32-165.ec2.internal glusterfs_devices='["/dev/xvdd","/dev/xvde"]'

```

**Comment by spacedan** [comment]
Fixed by https://github.com/openshift/openshift-ansible/pull/11809
