### ISSUE TITLE
Metrics won't start. Java Runtime Error

### ISSUE THREAD

**Issue by fmq** [openshift/openshift-ansible#11022]
#### Description

Enabling cluster Metrics in OKD 3.11 gives java error on startup of pods.

##### Version

Please put the following version information in the code block
indicated below.

 ```
[root@originm ~]# ansible --version
ansible 2.6.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[root@originm ~]# 


[root@originm openshift-ansible]# git describe
openshift-ansible-3.11.66-1
[root@originm openshift-ansible]# 

```

##### Steps To Reproduce
1. Configure and install OKD v3.11
2. Configure metrics vars in /etc/ansible/hosts

```
## METRICS
openshift_metrics_install_metrics=true
openshift_metrics_duration=10
openshift_metrics_hawkular_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_metrics_cassandra_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_metrics_heapster_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_metrics_cassandra_limits_memory=2Gi
openshift_metrics_cassandra_storage_type=dynamic
openshift_metrics_cassandra_pvc_size=20Gi
openshift_metrics_hawkular_limits_memory=2Gi
openshift_metrics_heapster_limits_memory=2Gi
openshift_metrics_storage_kind=dynamic
openshift_metrics_storage_volume_size=100Gi
openshift_metrics_cassandra_pvc_storage_class_name="glusterfs-app-storage"
```
3. execute metrics playbook 
```
ansible-playbook playbooks/openshift-metrics/config.yml
```

##### Expected Results
Metrics installation should finish and all pod's should start

##### Observed Results
All metrics pod fail and hawkular-cassandra pod shows Java error

here is full log.. 
https://gist.github.com/fmq/8c4654089d68dced2a406e60bbb43ff9

This is pertinent part of the log..
```
The MAX_HEAP_SIZE envar is not set. Basing the MAX_HEAP_SIZE on the available memory limit for the pod (2147483648).
The memory limit is less than 2GB. Using 1/2 of available memory for the max_heap_size.
The MAX_HEAP_SIZE has been set to 1024M
The HEAP_NEWSIZE envar is not set. Setting the HEAP_NEWSIZE to one third the MAX_HEAP_SIZE: 341M
About to generate seeds
Trying to access the Seed list [try #1]
Trying to access the Seed list [try #2]
Trying to access the Seed list [try #3]
Setting seeds to be hawkular-cassandra-1-lw55b
.........
INFO  [main] 2019-01-16 17:18:05,370 ColumnFamilyStore.java:391 - Initializing system_schema.types
INFO  [main] 2019-01-16 17:18:05,385 ColumnFamilyStore.java:391 - Initializing system_schema.functions
INFO  [main] 2019-01-16 17:18:05,405 ColumnFamilyStore.java:391 - Initializing system_schema.aggregates
INFO  [main] 2019-01-16 17:18:05,420 ColumnFamilyStore.java:391 - Initializing system_schema.indexes
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007f7256783a50, pid=1, tid=0x00007f722e847700
#
# JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x15ba50]  __memmove_ssse3_back+0x2110
#
# Core dump written. Default location: /opt/jboss/core or core.1
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log

```

**Comment by fmq** [comment]
Just in case Java version is

```
sh-4.2$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
sh-4.2$ command terminated with non-zero exit code: Error executing in Docker Container: 137
disconnected

```

**Comment by fmq** [comment]
Just some more info, I sometimes get a different error log with the java error (https://gist.github.com/fmq/6f7d641c0d14f87f5ee8f6aeb0b32681) 

EG:

```
INFO  [main] 2019-01-16 17:36:18,318 ColumnFamilyStore.java:391 - Initializing system_schema.indexes
ERROR [CompactionExecutor:1] 2019-01-16 17:36:18,853 CassandraDaemon.java:207 - Exception in thread Thread[CompactionExecutor:1,1,main]
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at net.jpountz.util.SafeUtils.checkLength(SafeUtils.java:38) ~[lz4-1.3.0.jar:na]
	at net.jpountz.util.ByteBufferUtils.checkRange(ByteBufferUtils.java:11) ~[lz4-1.3.0.jar:na]
	at net.jpountz.lz4.LZ4JNIFastDecompressor.decompress(LZ4JNIFastDecompressor.java:48) ~[lz4-1.3.0.jar:na]
	at org.apache.cassandra.io.compress.LZ4Compressor.uncompress(LZ4Compressor.java:113) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.compress.CompressedRandomAccessReader.reBufferMmap(CompressedRandomAccessReader.java:183) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.util.RandomAccessReader.reBuffer(RandomAccessReader.java:111) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.util.RandomAccessReader.seek(RandomAccessReader.java:302) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner.seekToCurrentRangeStart(BigTableScanner.java:213) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner.access$200(BigTableScanner.java:52) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner$KeyScanningIterator.computeNext(BigTableScanner.java:313) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner$KeyScanningIterator.computeNext(BigTableScanner.java:293) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.AbstractIterator.hasNext(AbstractIterator.java:47) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner.hasNext(BigTableScanner.java:272) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.MergeIterator$Candidate.advance(MergeIterator.java:369) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.MergeIterator$ManyToOne.advance(MergeIterator.java:189) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.MergeIterator$ManyToOne.computeNext(MergeIterator.java:158) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.AbstractIterator.hasNext(AbstractIterator.java:47) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.partitions.UnfilteredPartitionIterators$2.hasNext(UnfilteredPartitionIterators.java:144) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.transform.BasePartitions.hasNext(BasePartitions.java:92) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.compaction.CompactionIterator.hasNext(CompactionIterator.java:227) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.compaction.CompactionTask.runMayThrow(CompactionTask.java:190) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.compaction.CompactionTask.executeInternal(CompactionTask.java:89) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.compaction.AbstractCompactionTask.execute(AbstractCompactionTask.java:61) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.compaction.CompactionManager$BackgroundCompactionCandidate.run(CompactionManager.java:264) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:79) [apache-cassandra-3.0.15.jar:3.0.15]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
ERROR [CompactionExecutor:2] 2019-01-16 17:36:19,095 CassandraDaemon.java:207 - Exception in thread Thread[CompactionExecutor:2,1,main]
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at net.jpountz.util.SafeUtils.checkLength(SafeUtils.java:38) ~[lz4-1.3.0.jar:na]
	at net.jpountz.util.ByteBufferUtils.checkRange(ByteBufferUtils.java:11) ~[lz4-1.3.0.jar:na]
	at net.jpountz.lz4.LZ4JNIFastDecompressor.decompress(LZ4JNIFastDecompressor.java:48) ~[lz4-1.3.0.jar:na]
	at org.apache.cassandra.io.compress.LZ4Compressor.uncompress(LZ4Compressor.java:113) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.compress.CompressedRandomAccessReader.reBufferMmap(CompressedRandomAccessReader.java:183) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.util.RandomAccessReader.reBuffer(RandomAccessReader.java:111) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.util.RandomAccessReader.seek(RandomAccessReader.java:302) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner.seekToCurrentRangeStart(BigTableScanner.java:213) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner.access$200(BigTableScanner.java:52) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner$KeyScanningIterator.computeNext(BigTableScanner.java:313) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner$KeyScanningIterator.computeNext(BigTableScanner.java:293) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.AbstractIterator.hasNext(AbstractIterator.java:47) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.io.sstable.format.big.BigTableScanner.hasNext(BigTableScanner.java:272) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.MergeIterator$Candidate.advance(MergeIterator.java:369) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.MergeIterator$ManyToOne.advance(MergeIterator.java:189) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.MergeIterator$ManyToOne.computeNext(MergeIterator.java:158) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.AbstractIterator.hasNext(AbstractIterator.java:47) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.partitions.UnfilteredPartitionIterators$2.hasNext(UnfilteredPartitionIterators.java:144) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.transform.BasePartitions.hasNext(BasePartitions.java:92) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.compaction.CompactionIterator.hasNext(CompactionIterator.java:227) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.compaction.CompactionTask.runMayThrow(CompactionTask.java:190) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.compaction.CompactionTask.executeInternal(CompactionTask.java:89) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.compaction.AbstractCompactionTask.execute(AbstractCompactionTask.java:61) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at org.apache.cassandra.db.compaction.CompactionManager$BackgroundCompactionCandidate.run(CompactionManager.java:264) ~[apache-cassandra-3.0.15.jar:3.0.15]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:79) [apache-cassandra-3.0.15.jar:3.0.15]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
#
# A fatal error has been detected by the Java Runtime Environment:
```

**Comment by fmq** [comment]
One more thing, if I use ephemeral storage everything works fine

```
## METRICS
openshift_metrics_install_metrics=true
openshift_metrics_duration=10
openshift_metrics_hawkular_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_metrics_cassandra_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_metrics_heapster_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_metrics_cassandra_limits_memory=2Gi
openshift_metrics_hawkular_limits_memory=2Gi
openshift_metrics_heapster_limits_memory=2Gi
openshift_metrics_storage_kind=emptydir
#openshift_metrics_storage_kind=dynamic
#openshift_metrics_storage_volume_size=100Gi
```

We are using GlusterFS as storage class

**Comment by vrutkovs** [comment]
Please file an issue at https://github.com/openshift/origin-metrics
