### ISSUE TITLE
'unicode' object has no attribute 'iteritems' when deploy logging on 3.11

### ISSUE THREAD

**Issue by vanloswang** [openshift/openshift-ansible#11362]
#### Description
failed to install logging on okd 3.11 in a shell environment with UTF-8 encoding.

##### Version
* Your ansible version per `ansible --version`
```bash
# ansible --version
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 21 2018, 14:37:48) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

* The output of `rpm -q openshift-ansible`
3.11.82

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. install okd 3.11
2. run following command to install logging
```bash
ansible-playbook -i ~/hosts /usr/share/ansible/openshift-ansible/playbooks/openshift-logging/config.yml -e openshift_logging_install_logging=True -e openshift_logging_es_nodeselector='{"node-role.kubernetes.io/infra":"true"}' -e openshift_logging_es_pvc_dynamic=true
```

##### Expected Results
no such error.

##### Observed Results
```bash
TASK [openshift_control_plane : Retrieve list of schedulable nodes matching selector] *************************************************************************************
fatal: [192.168.1.2]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ openshift_logging_es_nodeselector | map_to_pairs }}'. Error was a <type 'exceptions.AttributeError'>, original message: 'unicode' object has no attribute 'iteritems'"}
```

##### Additional Information
* CentOS 7.5

After tracing the code, I found the problem is in roles/lib_utils/filter_plugins/oo_filters.py with function map_to_pairs. I test the code as following:
```
# python
Python 2.7.5 (default, Aug 21 2018, 14:37:48) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ansible.module_utils.six import iteritems, string_types, u
>>> print(','.join(["{}{}{}".format(key, "=", value) for key, value in iteritems({"node-role.kubernetes.io/infra":"true"})]))
node-role.kubernetes.io/infra=true
>>> print(','.join(["{}{}{}".format(key, "=", value) for key, value in iteritems(u'{"node-role.kubernetes.io/infra":"true"}')]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py", line 610, in iteritems
^[[A    return d.iteritems(**kw)
AttributeError: 'unicode' object has no attribute 'iteritems'
>>> import json
>>> print(','.join(["{}{}{}".format(key, "=", value) for key, value in iteritems(json.loads(u'{"node-role.kubernetes.io/infra":"true"}'))]))
node-role.kubernetes.io/infra=true
```
oo_filters.py maybe treat the source arguement as unicode object.

**Comment by faust64** [comment]
Can we see your inventory? Especially the logging selectors?

**Comment by vanloswang** [comment]
@faust64 The content of my inventory file is as following:
```bash
# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true

openshift_deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

# disable some check
openshift_disable_check=memory_availability,disk_availability,docker_storage,docker_image_availability,package_availability,package_version

# uncomment the following to enable cri-o
#openshift_crio_use_rpm=True
#openshift_use_crio=True

# Do not remove platform images
openshift_uninstall_images=false

# Do not excluder and docker excluder
openshift_enable_excluders=false

openshift_cluster_monitoring_operator_install=false
ansible_service_broker_install=false
template_service_broker_install=false
openshift_logging_install_logging=false
openshift_metrics_install_metrics=false
openshift_node_problem_detector_install=false

# host group for masters
[masters]
192.168.1.2

# host group for etcd
[etcd]
192.168.1.2

# host group for nodes, includes region info
[nodes]
192.168.1.2 openshift_node_group_name='node-config-all-in-one'
```

It will deploy logging ok by put the following content in inventory file.
```bash
openshift_logging_install_logging=true
openshift_logging_es_nodeselector={"node-role.kubernetes.io/infra":"true"}
openshift_logging_es_pvc_dynamic=true
```
So this issue is caused by pass value from shell to ansible with unicode encoding.
