### ISSUE TITLE
Could not find imported module support code for docker_info

### ISSUE THREAD

**Issue by beyonddc** [openshift/openshift-ansible#11644]
Thanks for reading!  I have been trying to get OKD running for the last couple days but no luck.  I hit couple of issues but I figure I should tackle the problem one by one.  Here's my first issue.  Thanks!

#### Description
Failed to deploy cluster using the RPM-based installer.  It failed during "Run health checks (install) - EL".  Particularly failed when checking for "docker_storage"

##### Version
```
[root@okd1 openshift-ansible]# ansible --version
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

[root@okd1 openshift-ansible]# git describe
openshift-ansible-3.11.115-1-26-gb669651

[root@okd1 openshift-ansible]# rpm -qa | grep docker
origin-docker-excluder-3.11.0-1.el7.git.0.62803d0.noarch
python-docker-pycreds-0.3.0-9.el7_6.noarch
docker-rhel-push-plugin-1.13.1-96.gitb2f74b2.el7.x86_64
docker-client-1.13.1-96.gitb2f74b2.el7.x86_64
python-docker-py-1.10.6-9.el7_6.noarch
docker-1.13.1-96.gitb2f74b2.el7.x86_64
docker-common-1.13.1-96.gitb2f74b2.el7.x86_64

[root@okd1 playbooks]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

##### Steps To Reproduce
1. ansible-playbook ./prerequisites.yml
2. ansible-playbook ./deploy_cluster.yml

##### Expected Results
Installation succeeded

```
Failure summary:
  1. Hosts:    okd1.beyonddc.net, okd2.beyonddc.net, okd3.beyonddc.net, okd4.beyonddc.net, okd5.beyonddc.net
     Play:     OpenShift Health Checks
     Task:     Run health checks (install) - EL
     Message:  One or more checks failed
     Details:  check "docker_storage":
               Could not find imported module support code for docker_info.  Looked for either AnsibleDockerClient.py or docker_common.py
               Traceback (most recent call last):
                 File "/root/workspace/openshift-ansible/roles/openshift_health_checker/action_plugins/openshift_health_check.py", line 225, in run_check
                   result = check.run()
                 File "/root/workspace/openshift-ansible/roles/openshift_health_checker/openshift_checks/docker_storage.py", line 53, in run
                   docker_info = self.execute_module("docker_info", {})
                 File "/root/workspace/openshift-ansible/roles/openshift_health_checker/openshift_checks/__init__.py", line 211, in execute_module
                   result = self._execute_module(module_name, module_args, self.tmp, self.task_vars)
                 File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 809, in _execute_module
                   (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
                 File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 203, in _configure_module
                   environment=final_environment)
                 File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 1023, in modify_module
                   environment=environment)
                 File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 859, in _find_module_utils
                   recursive_finder(module_name, b_module_data, py_module_names, py_module_cache, zf)
                 File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 621, in recursive_finder
                   raise AnsibleError(' '.join(msg))
               AnsibleError: Could not find imported module support code for docker_info.  Looked for either AnsibleDockerClient.py or docker_common.py

```

##### Observed Results
Seems like it couldn't get docker-info using Python but when I run docker info thru command line, it does show information.  I ensured the docker service is running on all my nodes and can get docker info via command line.

```
[root@okd1 playbooks]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 19.92 MB
 Data Space Total: 3.406 GB
 Data Space Available: 3.386 GB
 Metadata Space Used: 1.298 MB
 Metadata Space Total: 12.58 MB
 Metadata Space Available: 11.28 MB
 Thin Pool Minimum Free Space: 340.3 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.149-RHEL7 (2018-07-20)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9c3c5f853ebf0ffac0d087e94daef462133b69c7 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-957.12.2.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 15.51 GiB
Name: okd1.beyonddc.net
ID: F6AU:EZVB:QFRI:64OE:2U4K:UEZ4:JAWS:2DCX:NRNA:CUOU:VOXC:WHRL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure), docker.io (secure)
```

##### Additional Information
This is an on-premise installation in my homelab.

My inventory file is as follow.  I mostly copied and pasted from the installation guide for single master and multiple nodes.
```
[root@okd1 playbooks]# cat /etc/ansible/hosts
# This is the default ansible 'hosts' file.
#
# It should live in /etc/ansible/hosts
#
#   - Comments begin with the '#' character
#   - Blank lines are ignored
#   - Groups of hosts are delimited by [header] elements
#   - You can enter hostnames or ip addresses
#   - A hostname/ip can be a member of multiple groups

# Ex 1: Ungrouped hosts, specify before any group headers.

## green.example.com
## blue.example.com
## 192.168.100.1
## 192.168.100.10

# Ex 2: A collection of hosts belonging to the 'webservers' group

## [webservers]
## alpha.example.org
## beta.example.org
## 192.168.1.100
## 192.168.1.110

# If you have multiple hosts following a pattern you can specify
# them like this:

## www[001:006].example.com

# Ex 3: A collection of database servers in the 'dbservers' group

## [dbservers]
## 
## db01.intranet.mydomain.net
## db02.intranet.mydomain.net
## 10.25.1.56
## 10.25.1.57

# Here's another example of host ranges, this time there are no
# leading 0s:

## db-[99:101]-node.example.com

# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root
# Control plane pods didn't come up
# https://access.redhat.com/solutions/3607721
osm_etcd_image=registry.access.redhat.com/rhel7/etcd:3.2.22-30

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true

openshift_deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to AllowAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

# host group for masters
[masters]
okd1.beyonddc.net

# host group for etcd
[etcd]
okd1.beyonddc.net

# host group for nodes, includes region info
[nodes]
okd1.beyonddc.net openshift_node_group_name='node-config-master'
okd2.beyonddc.net openshift_node_group_name='node-config-compute'
okd3.beyonddc.net openshift_node_group_name='node-config-compute'
okd4.beyonddc.net openshift_node_group_name='node-config-infra'
okd5.beyonddc.net openshift_node_group_name='node-config-infra'
```

**Comment by vrutkovs** [comment]
Ansible 2.8 is not supported in 3.11

cc @mtnbikenc

**Comment by justinflemingibm** [comment]
I'm seeing the same problem when trying to bring up a cluster.

It is not clear in the setup instructions that Ansible 2.8 is not supported: https://github.com/openshift/openshift-ansible/tree/release-3.11#setup says 
```
Ansible >= 2.6, Ansible 2.7 is supported
```

Also, I followed the install instructions [here](https://docs.okd.io/3.11/install/host_preparation.html#installing-base-packages) for the RPM-based installed (step 3) and Ansible 2.8 was installed.

**Comment by beyonddc** [comment]
@justinflemingibm, I agree that it wasn't that obvious.  Ideally there should be an Ansible version check when running the prerequisites.yml playbook.  I did followed @vrutkovs suggestion to downgrade my Ansible to 2.6.  You can find Ansible RPMs from the following URL:  [https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/](https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/)

I think the hiccup is when I was following the host_preparation instruction from [https://docs.okd.io/3.11/install/host_preparation.html#installing-base-packages](https://docs.okd.io/3.11/install/host_preparation.html#installing-base-packages), it suggested to use the EPEL as package source and the EPEL package repository only has Ansible 2.8 in there.  I thought if I follow the documentation then I would have all the versioning right.  I didn't pay attention that OpenShift Ansible only support Ansible up till 1.7.

And rhel-7-server-extras-rpms repository only has version 2.3 and 2.4 so I have to grab the Ansible 2.6 RPM from the Ansible release page.

**Comment by justinflemingibm** [comment]
I tried Ansible 2.7.0 (since [this](https://github.com/openshift/openshift-ansible/tree/release-3.11#setup) says explicitly that 2.7 is supported) but the cluster deploy failed again, this time with [this error](https://bugzilla.redhat.com/show_bug.cgi?id=1638699). I switched to Ansible 2.7.1 and the cluster deploy was successful.

**Comment by laoshanxi** [comment]
Is Ansible 2.8 supported now?

**Comment by donghwicha** [comment]
> Is Ansible 2.8 supported now?

I don't think so. it is failing on my env

**Comment by ifelsefi** [comment]
I am getting the same error with Ansible 2.8.5.

**Comment by acidwars** [comment]
Same for Ansible 2.9.0

**Comment by madipietro** [comment]
Same Error ansible 2.9.2 on Archlinux with python 3.8.

**Comment by Lifter-PL** [comment]
Same error with Ansible 2.9.9 on CentOS7.
Works with Ansible 2.6.20.

**Comment by epava1516** [comment]
> Same error with Ansible 2.9.9 on CentOS7.
> Works with Ansible 2.6.20.

Same for me
