### ISSUE TITLE
Two bin/cluster failures on os x .

### ISSUE THREAD

**Issue by jayunit100** [openshift/openshift-ansible#1184]
Error 1: This is easy to fix.  Ive put the hack below:

I `bin/cluster` script seems to blow up for me on osx

The first two errors were related to `Forbidden` errors, which make sense, since some folks running EC2 instances may not be allowed to use some services (like elasticache).  This can be easily fixed like so.
```
         # Include RDS instances?
-        self.rds_enabled = True
+        self.rds_enabled = False
         if config.has_option('ec2', 'rds'):
             self.rds_enabled = config.getboolean('ec2', 'rds')

         # Include ElastiCache instances?
-        self.elasticache_enabled = True
+        self.elasticache_enabled = False
```

Error 2: Not sure how to fix this. 

But the next issue seemed a little trickier... a missing crypto library.  Not sure how to fix .  Any ideas?  I tried ` pip install --upgrade cryptography` but that didnt fix it.  Pasted below:

```
➜  openshift-ansible git:(master) ✗ ./bin/cluster list aws ''
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.4/libexec/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/Cellar/ansible/1.9.4/libexec/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/playbook/play.py", line 194, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/playbook/play.py", line 681, in _load_tasks
    role_name=role_name
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/playbook/task.py", line 255, in __init__
    self.async_seconds = template.template_from_string(play.basedir, self.async_seconds, all_vars)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/utils/template.py", line 346, in template_from_string
    environment.filters.update(_get_filters())
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/utils/template.py", line 54, in _get_filters
    plugins = [ x for x in utils.plugins.filter_loader.all()]
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/utils/plugins.py", line 232, in all
    self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)
  File "/Users/jayunit100/Development/openshift-ansible/filter_plugins/oo_filters.py", line 10, in <module>
    import OpenSSL.crypto
  File "/usr/local/Cellar/ansible/1.9.4/libexec/vendor/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/Cellar/ansible/1.9.4/libexec/vendor/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/Cellar/ansible/1.9.4/libexec/vendor/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
ImportError: No module named cryptography.hazmat.bindings.openssl.binding
ACTION [list] failed: Command 'ansible-playbook  -i inventory/aws/hosts -e 'cluster_id= cluster_env=dev deployment_type=origin' playbooks/aws/openshift-cluster/list.yml' returned non-zero exit status 1
```

**Comment by ncdc** [comment]
@jayunit100 what version of ansible do you have? How did you install it?

**Comment by jayunit100** [comment]
ansible 1.9.4   ; i used brew  .  i ll see if i can get a newer one ?

**Comment by ncdc** [comment]
I filed the bug to get it fixed, and it should be in a newer 1.9.4 release in brew

**Comment by jayunit100** [comment]
let me reinstall w/ homebrew, ill see if that fixes.  thanks!

**Comment by jayunit100** [comment]
ah ok.  I had to `brew update` and then `brew upgrade ansible` seemed to fix it

**Comment by jayunit100** [comment]
```
➜  openshift-ansible git:(master) ✗ ./bin/cluster list aws ''
```

Now gives the following error.

```
PLAY [Generate oo_list_hosts group] ********************************************

TASK [set_fact] ****************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'cluster_id != ''' failed. The error was: No module named runner.filter_plugins.core\n\nThe error appears to have been in '/Users/jayunit100/Development/openshift-ansible/playbooks/aws/openshift-cluster/list.yml': line 10, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - set_fact: scratch_group=tag_clusterid_{{ cluster_id }}\n    ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

ACTION [list] failed: Command 'ansible-playbook  -i inventory/aws/hosts -e 'cluster_id= cluster_env=dev deployment_type=origin' playbooks/aws/openshift-cluster/list.yml' returned non-zero exit status 2
```

**Comment by ncdc** [comment]
Did homebrew upgrade you to ansible 2?

**Comment by jayunit100** [comment]
yes.  its 2x .  So, progress, the new error is around the `cluster_id` stuff check i guess.

**Comment by abutcher** [comment]
The playbooks don't work with ansible 2x yet, we're tracking that (slowly) here https://github.com/openshift/openshift-ansible/pull/991

**Comment by detiber** [comment]
@jayunit100 you'll want to run with ansible 1.9.4

If you see that cryptography error again, it is probably just that you are missing pyOpenSSL.

**Comment by detiber** [comment]
https://github.com/openshift/openshift-ansible/pull/1187 Updates the ec2.ini file we ship to disable rds and elasticache.

**Comment by donovanmuller** [comment]
@jayunit100 I had issues with the brew installed Ansible (1.9.4) and ended up using the `pip` installed version, which worked without issue. Wrote about it [here](http://blog.switchbit.io/osx-el-capitan-and-ansible-opensslerror). If you're still stuck...

**Comment by jayunit100** [comment]
Thanks donovan, likewise ; Looks like this works, after doing the following threww things.

- update ansible version to 1.9.4, running from source (its really easy , just clone ansible, checkout the 1.9.4 tag, run `source  source ./hacking/env-setup` and then `bin/ansible` just works.
- update to latest head of openshift-ansible
- `pip install pyOpenSSL`

Will close this issue, will create a new issue if others pop up.
