### ISSUE TITLE
__main__.RouterException: Could not perform router preparation: Error: unknown flag: --default-cert

### ISSUE THREAD

**Issue by dombrowa** [openshift/openshift-ansible#11869]
#### Description

Provide a brief description of your issue here. For example:

openshift installer fails with unknown flag: --default-cert

##### Version

Please put the following version information in the code block
indicated below.
```
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
If you're operating from a **git clone**:

no git

If you're running from playbooks installed via RPM

Place the output between the code block below:

```
openshift-ansible-3.11.135-1.git.0.b7ad55a.el7.noarch
```

##### Steps To Reproduce
1. install redhat 7.6
2. use IBM RH satellite to upgrade (to 7.7)
3. ansible-playbook -i hosts.311 playbooks/deploy_cluster.yml

##### Expected Results
Describe what you expected to happen.

```
Successful install w/o syntax error
```

##### Observed Results
syntax error of mismatching version of oc and openshift-ansible using an unknown flag

```
TASK [openshift_hosted : Create OpenShift router] *****************************************************************************************************************************************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_hosted/tasks/router.yml:85
Wednesday 28 August 2019  14:02:24 -0400 (0:00:00.358)       0:00:12.819 ****** 
Using module file /usr/share/ansible/openshift-ansible/roles/lib_openshift/library/oc_adm_router.py
Pipelining is enabled.
<netsres5> ESTABLISH LOCAL CONNECTION FOR USER: root
<netsres5> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 114, in <module>
  File "<stdin>", line 106, in _ansiballz_main
  File "<stdin>", line 49, in invoke_module
  File "/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py", line 3265, in <module>
  File "/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py", line 3256, in main
  File "/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py", line 3175, in run_ansible
  File "/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py", line 2969, in create
  File "/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py", line 3013, in needs_update
  File "/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py", line 2727, in prepared_router
__main__.RouterException: Could not perform router preparation: Error: unknown flag: --default-cert


Usage:
  oc adm [flags]

Cluster Management:
  upgrade                            Upgrade a cluster
  top                                Show usage statistics of resources on the server
  must-gather                        Launch a new instance of a pod for gathering debug information

Node Management:
  drain                              Drain node in preparation for maintenance
  cordon                             Mark node as unschedulable
  uncordon                           Mark node as schedulable
  taint                              Update the taints on one or more nodes
  node-logs                          Display and filter node logs

Security and Policy:
  new-project                        Create a new project
  policy                             Manage cluster authorization and security policy
  groups                             Manage groups
  certificate                        Approve or reject certificate requests
  pod-network                        Manage pod network

Maintenance:
  prune                              Remove older versions of resources from the server
  migrate                            Migrate data in the cluster

Configuration:
  create-kubeconfig                  Create a basic .kubeconfig file from client certs
  create-api-client-config           Create a config file for connecting to the server as a user
  create-bootstrap-project-template  Create a bootstrap project template
  create-bootstrap-policy-file       Create the default bootstrap policy
  create-login-template              Create a login template
  create-provider-selection-template Create a provider selection template
  create-error-template              Create an error page template

Other Commands:
  build-chain                        Output the inputs and dependencies of your builds
  completion                         Output shell completion code for the specified shell (bash or zsh)
  config                             Change configuration files for the client
  release                            Tools for managing the OpenShift release process
  verify-image-signature             Verify the image identity contained in the image signature

Use "oc adm <command> --help" for more information about a given command.
Use "oc adm options" for a list of global command-line options (applies to all commands).



failed: [netsres5] (item={u'extended_validation': True, u'name': u'router', u'certificate': {u'keyfile': u'/etc/origin/master/openshift-router.key', u'certfile': u'/etc/origin/master/openshift-router.crt', u'cafile': u'/etc/origin/master/ca.crt'}, u'replicas': u'1', u'serviceaccount': u'router', u'namespace': u'default', u'selector': u'node-role.kubernetes.io/infra=true', u'edits': [{u'action': u'put', u'key': u'spec.strategy.rollingParams.intervalSeconds', u'value': 1}, {u'action': u'put', u'key': u'spec.strategy.rollingParams.updatePeriodSeconds', u'value': 1}, {u'action': u'put', u'key': u'spec.strategy.activeDeadlineSeconds', u'value': 21600}], u'images': u'registry.redhat.io/openshift3/ose-${component}:v3.11.135', u'stats_port': 1936, u'ports': [u'80:80', u'443:443']}) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "item": {
        "certificate": {
            "cafile": "/etc/origin/master/ca.crt", 
            "certfile": "/etc/origin/master/openshift-router.crt", 
            "keyfile": "/etc/origin/master/openshift-router.key"
        }, 
        "edits": [
            {
                "action": "put", 
                "key": "spec.strategy.rollingParams.intervalSeconds", 
                "value": 1
            }, 
            {
                "action": "put", 
                "key": "spec.strategy.rollingParams.updatePeriodSeconds", 
                "value": 1
            }, 
            {
                "action": "put", 
                "key": "spec.strategy.activeDeadlineSeconds", 
                "value": 21600
            }
        ], 
        "extended_validation": true, 
        "images": "registry.redhat.io/openshift3/ose-${component}:v3.11.135", 
        "name": "router", 
        "namespace": "default", 
        "ports": [
            "80:80", 
            "443:443"
        ], 
        "replicas": "1", 
        "selector": "node-role.kubernetes.io/infra=true", 
        "serviceaccount": "router", 
        "stats_port": 1936
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py\", line 3265, in <module>\n  File \"/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py\", line 3256, in main\n  File \"/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py\", line 3175, in run_ansible\n  File \"/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py\", line 2969, in create\n  File \"/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py\", line 3013, in needs_update\n  File \"/tmp/ansible_oc_adm_router_payload_ukanNs/__main__.py\", line 2727, in prepared_router\n__main__.RouterException: Could not perform router preparation: Error: unknown flag: --default-cert\n\n\nUsage:\n  oc adm [flags]\n\nCluster Management:\n  upgrade                            Upgrade a cluster\n  top                                Show usage statistics of resources on the server\n  must-gather                        Launch a new instance of a pod for gathering debug information\n\nNode Management:\n  drain                              Drain node in preparation for maintenance\n  cordon                             Mark node as unschedulable\n  uncordon                           Mark node as schedulable\n  taint                              Update the taints on one or more nodes\n  node-logs                          Display and filter node logs\n\nSecurity and Policy:\n  new-project                        Create a new project\n  policy                             Manage cluster authorization and security policy\n  groups                             Manage groups\n  certificate                        Approve or reject certificate requests\n  pod-network                        Manage pod network\n\nMaintenance:\n  prune                              Remove older versions of resources from the server\n  migrate                            Migrate data in the cluster\n\nConfiguration:\n  create-kubeconfig                  Create a basic .kubeconfig file from client certs\n  create-api-client-config           Create a config file for connecting to the server as a user\n  create-bootstrap-project-template  Create a bootstrap project template\n  create-bootstrap-policy-file       Create the default bootstrap policy\n  create-login-template              Create a login template\n  create-provider-selection-template Create a provider selection template\n  create-error-template              Create an error page template\n\nOther Commands:\n  build-chain                        Output the inputs and dependencies of your builds\n  completion                         Output shell completion code for the specified shell (bash or zsh)\n  config                             Change configuration files for the client\n  release                            Tools for managing the OpenShift release process\n  verify-image-signature             Verify the image identity contained in the image signature\n\nUse \"oc adm <command> --help\" for more information about a given command.\nUse \"oc adm options\" for a list of global command-line options (applies to all commands).\n\n\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
netsres5                   : ok=53   changed=0    unreachable=0    failed=1    skipped=53   rescued=0    ignored=0   


INSTALLER STATUS **************************************************************************************************************************************************************************************************
Initialization  : Complete (0:00:07)
Hosted Install  : In Progress (0:00:07)
	This phase can be restarted by running: playbooks/openshift-hosted/config.yml
Wednesday 28 August 2019  14:02:25 -0400 (0:00:00.910)       0:00:13.729 ****** 
=============================================================================== 
openshift_hosted : Create OpenShift router ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.91s
/usr/share/ansible/openshift-ansible/roles/openshift_hosted/tasks/router.yml:85 ----------------------------------------------------------------------------------------------------------------------------------
openshift_hosted : Create default projects ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.87s
/usr/share/ansible/openshift-ansible/roles/openshift_hosted/tasks/create_projects.yml:2 --------------------------------------------------------------------------------------------------------------------------
openshift_hosted : Grant the router service account(s) access to the appropriate scc ----------------------------------------------------------------------------------------------------------------------- 0.50s
/usr/share/ansible/openshift-ansible/roles/openshift_hosted/tasks/router.yml:68 ----------------------------------------------------------------------------------------------------------------------------------
openshift_hosted : Retrieve list of openshift nodes matching router selector ------------------------------------------------------------------------------------------------------------------------------- 0.47s
/usr/share/ansible/openshift-ansible/roles/openshift_hosted/tasks/router.yml:10 ----------------------------------------------------------------------------------------------------------------------------------
openshift_hosted : Create the router service account(s) ---------------------------------------------------------------------------------------------------------------------------------------------------- 0.47s
/usr/share/ansible/openshift-ansible/roles/openshift_hosted/tasks/router.yml:61 ----------------------------------------------------------------------------------------------------------------------------------
Gather Cluster facts --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.43s
/usr/share/ansible/openshift-ansible/playbooks/init/cluster_facts.yml:27 -----------------------------------------------------------------------------------------------------------------------------------------
get openshift_current_version ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.43s
/usr/share/ansible/openshift-ansible/playbooks/init/cluster_facts.yml:10 -----------------------------------------------------------------------------------------------------------------------------------------
openshift_hosted : generate a default wildcard router certificate ------------------------------------------------------------------------------------------------------------------------------------------ 0.41s
/usr/share/ansible/openshift-ansible/roles/openshift_hosted/tasks/router.yml:38 ----------------------------------------------------------------------------------------------------------------------------------
openshift_hosted : Set additional permissions for router service account ----------------------------------------------------------------------------------------------------------------------------------- 0.36s
/usr/share/ansible/openshift-ansible/roles/openshift_hosted/tasks/router.yml:76 ----------------------------------------------------------------------------------------------------------------------------------
Detecting Operating System from ostree_booted -------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.31s
/usr/share/ansible/openshift-ansible/playbooks/init/basic_facts.yml:19 -------------------------------------------------------------------------------------------------------------------------------------------
openshift_control_plane : slurp ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.30s
/usr/share/ansible/openshift-ansible/roles/openshift_control_plane/tasks/check_existing_config.yml:10 ------------------------------------------------------------------------------------------------------------
openshift_persistent_volumes : Delete temp directory ------------------------------------------------------------------------------------------------------------------------------------------------------- 0.27s
/usr/share/ansible/openshift-ansible/roles/openshift_persistent_volumes/tasks/main.yml:28 ------------------------------------------------------------------------------------------------------------------------
openshift_persistent_volumes : Create temp directory for volume definitions -------------------------------------------------------------------------------------------------------------------------------- 0.25s
/usr/share/ansible/openshift-ansible/roles/openshift_persistent_volumes/tasks/main.yml:2 -------------------------------------------------------------------------------------------------------------------------
Initialize openshift.node.sdn_mtu -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.23s
/usr/share/ansible/openshift-ansible/playbooks/init/cluster_facts.yml:61 -----------------------------------------------------------------------------------------------------------------------------------------
include_role : openshift_version --------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.17s
/usr/share/ansible/openshift-ansible/playbooks/init/version.yml:5 ------------------------------------------------------------------------------------------------------------------------------------------------
openshift_sanitize_inventory : Check for usage of deprecated variables ------------------------------------------------------------------------------------------------------------------------------------- 0.16s
/usr/share/ansible/openshift-ansible/roles/openshift_sanitize_inventory/tasks/deprecations.yml:4 -----------------------------------------------------------------------------------------------------------------
set_fact openshift_portal_net if present on masters -------------------------------------------------------------------------------------------------------------------------------------------------------- 0.16s
/usr/share/ansible/openshift-ansible/playbooks/init/cluster_facts.yml:19 -----------------------------------------------------------------------------------------------------------------------------------------
set_fact --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.15s
/usr/share/ansible/openshift-ansible/playbooks/init/cluster_facts.yml:80 -----------------------------------------------------------------------------------------------------------------------------------------
openshift_control_plane : stat ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.15s
/usr/share/ansible/openshift-ansible/roles/openshift_control_plane/tasks/check_existing_config.yml:3 -------------------------------------------------------------------------------------------------------------
openshift_persistent_volumes : Copy the admin client config(s) --------------------------------------------------------------------------------------------------------------------------------------------- 0.15s
/usr/share/ansible/openshift-ansible/roles/openshift_persistent_volumes/tasks/main.yml:7 -------------------------------------------------------------------------------------------------------------------------

```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
Linux netsres5 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Red Hat Enterprise Linux Server release 7.7 (Maipo)
```

**Comment by vrutkovs** [comment]
Are you installing OKD or OCP? Which version of `oc` has been installed?

cc @soltysh - any recent changes to CLI params in 3.11?

**Comment by dombrowa** [comment]
I did not know what OKD or OCP are (if that is k8s related, see below)

oc version is:
```
[root@netsres5 ~]# oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.10", GitCommit:"d81afa6ba", GitTreeState:"clean", BuildDate:"2019-08-06T12:14:19Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-01T23:56:00Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

I did not select any K8s version myself, this has been installed:
```
[root@netsres5 ~]# yum list installed |egrep 'ansible|atomic|kube'
ansible.noarch                    2.8.4-1.el7                @epel              
atomic.x86_64                     1:1.22.1-26.gitb507039.el7 @ftp3-extras       
atomic-openshift.x86_64           3.11.135-1.git.0.b309f70.el7
atomic-openshift-docker-excluder.noarch
atomic-openshift-excluder.noarch  3.11.135-1.git.0.b309f70.el7
atomic-openshift-hyperkube.x86_64 3.11.135-1.git.0.b309f70.el7
atomic-openshift-node.x86_64      3.11.135-1.git.0.b309f70.el7
atomic-registries.x86_64          1:1.22.1-28.gitb507039.el7 @rhel-7-server-extras-rpms
boost-atomic.x86_64               1.53.0-27.el7              @ftp3              
cockpit-kubernetes.x86_64         176-2.el7                  @rhel-7-server-ose-3.11-rpms
openshift-ansible.noarch          3.11.135-1.git.0.b7ad55a.el7
openshift-ansible-docs.noarch     3.11.135-1.git.0.b7ad55a.el7
openshift-ansible-playbooks.noarch
openshift-ansible-roles.noarch    3.11.135-1.git.0.b7ad55a.el7
```

**Comment by vrutkovs** [comment]
Your `oc` is too new, its version is 4.1.10 instead of 3.x

Does the problem go away when you oc installed from `rhel-7-server-ose-3.11-rpms` repo and reports `GitVersion: "v3.11..."`?

**Comment by harsha544** [comment]
I saw similar problem on 3.11 on x86_64 architecture - Enclosed the error log.

[Error.log](https://github.com/openshift/openshift-ansible/files/3558346/Error.log)
