### ISSUE TITLE
ImportError: No module named yum

### ISSUE THREAD

**Issue by donovanmuller** [openshift/openshift-ansible#1200]
This seems to be the same error as #855.

Using the [Fedora 23 GP2 HVM AMI](https://getfedora.org/cloud/download/) (ami-518bfb3b) on AWS I'm getting the following *after* successfully running `playbooks/adhoc/bootstrap-fedora.yml`:

```
$ ansible-playbook -i ... playbooks/adhoc/bootstrap-fedora.yml

PLAY [OSEv3] ******************************************************************

TASK: [install python and deps for ansible modules] ***************************
ok: [ec2-54-172-114-234.compute-1.amazonaws.com]
ok: [ec2-54-174-9-0.compute-1.amazonaws.com]
ok: [ec2-52-90-78-173.compute-1.amazonaws.com]

PLAY RECAP ********************************************************************
ec2-52-90-78-173.compute-1.amazonaws.com : ok=1    changed=0    unreachable=0    failed=0
ec2-54-172-114-234.compute-1.amazonaws.com : ok=1    changed=0    unreachable=0    failed=0
ec2-54-174-9-0.compute-1.amazonaws.com : ok=1    changed=0    unreachable=0    failed=0

$ ansible-playbook -i ... playbooks/byo/config.yml

...
TASK: [openshift_facts | set_fact ] *******************************************
ok: [ec2-54-172-114-234.compute-1.amazonaws.com]
ok: [ec2-54-174-9-0.compute-1.amazonaws.com]
ok: [ec2-52-90-78-173.compute-1.amazonaws.com]

TASK: [openshift_facts | Ensure PyYaml is installed] **************************
...
failed: [ec2-54-172-114-234.compute-1.amazonaws.com] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-alcqqopudzupdufmdzvyulsdxepfilxk
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Traceback (most recent call last):
  File "/home/fedora/.ansible/tmp/ansible-tmp-1453123922.84-195523226686556/yum", line 27, in <module>
    import yum
ImportError: No module named yum
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 77783
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0
Shared connection to ec2-54-172-114-234.compute-1.amazonaws.com closed.
```

Seems `ansible_pkg_mgr` is picking up as `yum` and not `dnf`:

```
$ ssh fedora@ec2-52-90-78-173.compute-1.amazonaws.com "cat /etc/redhat-release"
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Fedora release 23 (Twenty Three)

$ ansible -i ... -m setup ec2-54-172-114-234.compute-1.amazonaws.com | grep ansible_pkg_mgr
        "ansible_pkg_mgr": "yum",
```

This looks related to https://github.com/ansible/ansible-modules-core/issues/1797 but [this comment](https://github.com/ansible/ansible-modules-core/issues/1797#issuecomment-149328047) is rather confusing, considering it worked for [this person](https://github.com/ansible/ansible-modules-core/issues/1797#issuecomment-154834770) with 1.9.4 and Fedora 23 apparently (even though the [commit](https://github.com/ansible/ansible/commit/f624ec4cb8771736ffbe3fe81b2949edda159863) is tagged with v2.x).

So, should this work with Ansible 1.9.4 and Fedora 23?

**Comment by detiber** [comment]
@donovanmuller are you still running into this issue?

**Comment by donovanmuller** [comment]
@detiber Haven't tried in a while, will try again tomorrow...

**Comment by donovanmuller** [comment]
Just tried again. Yup, still an issue (using current master).

```
TASK: [openshift_facts | Ensure PyYaml is installed] **************************
failed: [ec2-52-90-117-78.compute-1.amazonaws.com] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-ydrdjjsarfxqttwktwxhhrybjiehgynk
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Traceback (most recent call last):
  File "/home/fedora/.ansible/tmp/ansible-tmp-1455305175.6-248413711154640/yum", line 27, in <module>
    import yum
ImportError: No module named yum
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to ec2-52-90-117-78.compute-1.amazonaws.com closed.

failed: [ec2-52-90-20-168.compute-1.amazonaws.com] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-qfbqwjkljhlerhecwqdiyaxtbdakycqa
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Traceback (most recent call last):
  File "/home/fedora/.ansible/tmp/ansible-tmp-1455305175.6-102647393731271/yum", line 27, in <module>
    import yum
ImportError: No module named yum
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to ec2-52-90-20-168.compute-1.amazonaws.com closed.

failed: [ec2-54-88-67-67.compute-1.amazonaws.com] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-jltiwbmbpuuibplvotnmcazqsumgpuho
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Traceback (most recent call last):
  File "/home/fedora/.ansible/tmp/ansible-tmp-1455305175.6-113646079554909/yum", line 27, in <module>
    import yum
ImportError: No module named yum
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to ec2-54-88-67-67.compute-1.amazonaws.com closed.

failed: [ec2-54-88-124-28.compute-1.amazonaws.com] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-ekwpmbixxudcodspqpemwabjxttvfqxk
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Traceback (most recent call last):
  File "/home/fedora/.ansible/tmp/ansible-tmp-1455305175.6-254524919440145/yum", line 27, in <module>
    import yum
ImportError: No module named yum
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to ec2-54-88-124-28.compute-1.amazonaws.com closed.

failed: [ec2-54-88-210-168.compute-1.amazonaws.com] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-gsabgbgawrtwsrlilgpczqeeuncrlpga
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Traceback (most recent call last):
  File "/home/fedora/.ansible/tmp/ansible-tmp-1455305175.61-140258271928625/yum", line 27, in <module>
    import yum
ImportError: No module named yum
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to ec2-54-88-210-168.compute-1.amazonaws.com closed.


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/donovan/config.retry

ec2-52-90-117-78.compute-1.amazonaws.com : ok=4    changed=0    unreachable=0    failed=1
ec2-52-90-20-168.compute-1.amazonaws.com : ok=4    changed=0    unreachable=0    failed=1
ec2-54-88-124-28.compute-1.amazonaws.com : ok=4    changed=0    unreachable=0    failed=1
ec2-54-88-210-168.compute-1.amazonaws.com : ok=4    changed=0    unreachable=0    failed=1
ec2-54-88-67-67.compute-1.amazonaws.com : ok=4    changed=0    unreachable=0    failed=1
localhost                  : ok=10   changed=0    unreachable=0    failed=0
```

**Comment by abutcher** [comment]
I'm seeing dnf on this AMI with 1.9.4

```
# rpm -qa ansible
ansible-1.9.4-1.fc23.noarch
# ansible -m setup localhost | grep ansible_pkg_mgr
        "ansible_pkg_mgr": "dnf",
```

**Comment by detiber** [comment]
@abutcher I want to headdesk so bad right now....

@donovanmuller I just realized the issue...  the playbooks/adhoc/bootstrap-fedora.yml playbook disables fact gathering (`gather_facts`: false), so it never gathers the ansible_pkg_mgr fact from the host and defaults to yum.

I'll submit a PR to remove `gather_facts: false`

**Comment by abutcher** [comment]
@detiber nice :sunglasses:

**Comment by donovanmuller** [comment]
@detiber :+1:

**Comment by donovanmuller** [comment]
Pulled my master branch and now am getting the below on fresh installs on AWS with AMI ass above:

```
ansible-playbook -i ../aws-fedora/aws playbooks/adhoc/bootstrap-fedora.yml

...

GATHERING FACTS ***************************************************************
failed: [ec2-54-210-221-205.compute-1.amazonaws.com] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-qinliacnjremreevqvfjpmyoddmgfute
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
/bin/sh: /usr/bin/python: No such file or directory
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to ec2-54-210-221-205.compute-1.amazonaws.com closed.

failed: [ec2-54-236-120-45.compute-1.amazonaws.com] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-nctnhjapikrnbercqbrjepwsixuykqje
/bin/sh: /usr/bin/python: No such file or directory
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to ec2-54-236-120-45.compute-1.amazonaws.com closed.

failed: [ec2-54-210-139-64.compute-1.amazonaws.com] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-hbasuevyfgauyhhreeignpxjenoieawo
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
/bin/sh: /usr/bin/python: No such file or directory
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to ec2-54-210-139-64.compute-1.amazonaws.com closed.

failed: [ec2-52-23-180-202.compute-1.amazonaws.com] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-tadfmbmavhqacnnsnrixnlaqlrdisvwd
/bin/sh: /usr/bin/python: No such file or directory
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to ec2-52-23-180-202.compute-1.amazonaws.com closed.

failed: [ec2-54-236-253-91.compute-1.amazonaws.com] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-rhgaqqjsfroxniimwvtnyyajqospeaxd
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
/bin/sh: /usr/bin/python: No such file or directory
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to ec2-54-236-253-91.compute-1.amazonaws.com closed.


TASK: [install python and deps for ansible modules] ***************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/donovan/bootstrap-fedora.retry

ec2-52-23-180-202.compute-1.amazonaws.com : ok=0    changed=0    unreachable=0    failed=1
ec2-54-210-139-64.compute-1.amazonaws.com : ok=0    changed=0    unreachable=0    failed=1
ec2-54-210-221-205.compute-1.amazonaws.com : ok=0    changed=0    unreachable=0    failed=1
ec2-54-236-120-45.compute-1.amazonaws.com : ok=0    changed=0    unreachable=0    failed=1
ec2-54-236-253-91.compute-1.amazonaws.com : ok=0    changed=0    unreachable=0    failed=1
```

Am I doing something dumb or ?

**Comment by detiber** [comment]
@donovanmuller It looks like the failure is because of this: `/bin/sh: /usr/bin/python: No such file or directory`

It looks like on f23+ there is a need to install the `python` package prior to running. There may be some additional `python-*` packages needed as well.

**Comment by detiber** [comment]
@abutcher @sdodson can either of you try to reproduce this using the ec2 ami mentioned above to try and gather a comprehensive list of which python2 packages are needed?

**Comment by abutcher** [comment]
@detiber I'll give this AMI another go soon

**Comment by ingvagabund** [comment]
https://github.com/openshift/openshift-ansible/blob/master/playbooks/adhoc/bootstrap-fedora.yml
