### ISSUE TITLE
Trouble creating cluster in us-west-2

### ISSUE THREAD

**Issue by barkerd427** [openshift/openshift-ansible#1203]
Hi all,

I'm having trouble creating a cluster in us-west-2. It seems the AMI doesn't exist there, and the others I've tried haven't worked. One didn't have python installed and the other didn't have yum. Is there a preferred AMI for that region? Thanks.

**Comment by abutcher** [comment]
Assuming centos, this image looks like the right one for us-west-2: `ami-d440a6e7`.

**Comment by barkerd427** [comment]
I'm now getting this error during the 'wait for user setup' stage:
```
failed: [localhost] => (item=[u'dst-test-master-e2428', {u'ramdisk': None, u'kernel': None, u'root_device_type': u'ebs', u'private_dns_name': u'ip-10-0-2-135.us-west-2.compute.internal', u'key_name': u'kubernetes-9d73dcf22623383c1eaacdf00dbcf71c', u'public_ip': u'52.32.23.4', u'image_id': u'ami-d440a6e7', u'private_ip': u'10.0.2.135', u'public_dns_name': u'ec2-52-32-23-4.us-west-2.compute.amazonaws.com', u'state_code': 16, u'id': u'i-6c5d54b5', u'placement': u'us-west-2b', u'ami_launch_index': u'0', u'dns_name': u'ec2-52-32-23-4.us-west-2.compute.amazonaws.com', u'region': u'us-west-2', u'ebs_optimized': False, u'launch_time': u'2016-01-19T13:00:52.000Z', u'instance_type': u'm3.medium', u'state': u'running', u'root_device_name': u'/dev/sda1', u'hypervisor': u'xen', u'virtualization_type': u'hvm', u'architecture': u'x86_64'}]) => {"attempts": 20, "changed": true, "cmd": ["ssh", "-o", "StrictHostKeyChecking=no", "-o", "PasswordAuthentication=no", "-o", "ConnectTimeout=10", "-o", "UserKnownHostsFile=/dev/null", "fedora@ec2-52-32-23-4.us-west-2.compute.amazonaws.com", "echo", "fedora", "user", "is", "setup"], "delta": "0:00:00.859238", "end": "2016-01-19 07:05:51.836916", "failed": true, "item": ["dst-test-master-e2428", {"ami_launch_index": "0", "architecture": "x86_64", "dns_name": "ec2-52-32-23-4.us-west-2.compute.amazonaws.com", "ebs_optimized": false, "hypervisor": "xen", "id": "i-6c5d54b5", "image_id": "ami-d440a6e7", "instance_type": "m3.medium", "kernel": null, "key_name": "kubernetes-9d73dcf22623383c1eaacdf00dbcf71c", "launch_time": "2016-01-19T13:00:52.000Z", "placement": "us-west-2b", "private_dns_name": "ip-10-0-2-135.us-west-2.compute.internal", "private_ip": "10.0.2.135", "public_dns_name": "ec2-52-32-23-4.us-west-2.compute.amazonaws.com", "public_ip": "52.32.23.4", "ramdisk": null, "region": "us-west-2", "root_device_name": "/dev/sda1", "root_device_type": "ebs", "state": "running", "state_code": 16, "virtualization_type": "hvm"}], "rc": 255, "start": "2016-01-19 07:05:50.977678", "warnings": []}
stderr: Warning: Permanently added 'ec2-52-32-23-4.us-west-2.compute.amazonaws.com,52.32.23.4' (RSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/dt208868/launch.retry

localhost                  : ok=20   changed=2    unreachable=0    failed=1


real	5m17.025s
user	0m3.146s
sys	0m3.779s
ACTION [create] failed with exit status 512
```

I have mostly been trying fedora images due to errors like this when I initially started trying to use this project.

**Comment by detiber** [comment]
@barkerd427 It looks like you are running bin/cluster to provision the hosts?

Do you have the private key associated with your ec2 account loaded in your ssh agent (or configured in ~/.ssh/config)?

**Comment by barkerd427** [comment]
Yes. It all connects normally when I try a fedora image, but I'm unsuccessful at picking the correct fedora image. The scripts seem to use the fedora user, which isn't set up in the centos AMI. Each AMI I pick for fedora seems to lack some part that ansible eventually needs. I was hoping for a quick and easy solution to spin up a cluster in AWS for prototyping, but this is turning into a much longer process than doing it manually.

**Comment by barkerd427** [comment]
@detiber Also, the ssh check is successful in the step immediately prior where it connects as the centos user.

**Comment by detiber** [comment]
@barkerd427 For CentOS images, we assume the CentOS image from the AWS Marketplace.

That said, the official Fedora AMIs should be fine, but you would need to modify playbooks/aws/openshift-cluster/vars.yml to set deployment_vars.origin.ssh_user to fedora as opposed to centos.

This PR addresses some known issues with the AWS provisioning using bin/cluster as well: https://github.com/openshift/openshift-ansible/pull/1146

**Comment by barkerd427** [comment]
I've gotten a lot further. My vars.yml was set to fedora in the current version I'm using, but I've bounced around because some don't recognize my environment variables. It is still failing here:
```
TASK: [openshift_master | Configure OpenShift settings] ***********************
<master.us-west-2.compute.amazonaws.com>
<master.us-west-2.compute.amazonaws.com> dest=/etc/sysconfig/openshift-master regexp=^OPTIONS= line=OPTIONS=--loglevel=4
<master.us-west-2.compute.amazonaws.com> ConnectTimeout=10 KbdInteractiveAuthentication=no PasswordAuthentication=no UserKnownHostsFile=/dev/null User=centos ForwardAgent=yes ControlPath=/Users/dt208868/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto ControlPersist=600s
<master.us-west-2.compute.amazonaws.com>
<master.us-west-2.compute.amazonaws.com> ConnectTimeout=10 KbdInteractiveAuthentication=no 'sudo -k && sudo -H -S -p "[sudo via ansible, key=lmtapdwvawarnjnjnyqyvgqjovuitpnx] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-lmtapdwvawarnjnjnyqyvgqjovuitpnx; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/centos/.ansible/tmp/ansible-tmp-1453305090.22-86655395230605/lineinfile; rm -rf /home/centos/.ansible/tmp/ansible-tmp-1453305090.22-86655395230605/ >/dev/null 2>&1'"'"'' PasswordAuthentication=no UserKnownHostsFile=/dev/null User=centos ForwardAgent=yes ControlPath=/Users/dt208868/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto ControlPersist=600s
failed: [dst-test-master-a854b] => (item={'regex': '^OPTIONS=', 'line': u'OPTIONS=--loglevel=4'}) => {"failed": true, "item": {"line": "OPTIONS=--loglevel=4", "regex": "^OPTIONS="}, "rc": 257}
msg: Destination /etc/sysconfig/openshift-master does not exist !
<master.us-west-2.compute.amazonaws.com>
<master.us-west-2.compute.amazonaws.com> dest=/etc/sysconfig/openshift-master regexp=^CONFIG_FILE= line=CONFIG_FILE=/etc/openshift/master/master-config.yaml
<master.us-west-2.compute.amazonaws.com> ConnectTimeout=10 KbdInteractiveAuthentication=no PasswordAuthentication=no UserKnownHostsFile=/dev/null User=centos ForwardAgent=yes ControlPath=/Users/dt208868/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto ControlPersist=600s
<master.us-west-2.compute.amazonaws.com>
<master.us-west-2.compute.amazonaws.com> ConnectTimeout=10 KbdInteractiveAuthentication=no 'sudo -k && sudo -H -S -p "[sudo via ansible, key=oxnxakihqtmjosglqwsnzhoprzyfgunt] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-oxnxakihqtmjosglqwsnzhoprzyfgunt; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/centos/.ansible/tmp/ansible-tmp-1453305094.35-131206288351021/lineinfile; rm -rf /home/centos/.ansible/tmp/ansible-tmp-1453305094.35-131206288351021/ >/dev/null 2>&1'"'"'' PasswordAuthentication=no UserKnownHostsFile=/dev/null User=centos ForwardAgent=yes ControlPath=/Users/dt208868/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto ControlPersist=600s
failed: [dst-test-master-a854b] => (item={'regex': '^CONFIG_FILE=', 'line': u'CONFIG_FILE=/etc/openshift/master/master-config.yaml'}) => {"failed": true, "item": {"line": "CONFIG_FILE=/etc/openshift/master/master-config.yaml", "regex": "^CONFIG_FILE="}, "rc": 257}
msg: Destination /etc/sysconfig/openshift-master does not exist !

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/dt208868/launch.retry

52.32.23.4                 : ok=0    changed=0    unreachable=1    failed=0
dst-test-master-a854b      : ok=43   changed=18   unreachable=0    failed=1
dst-test-node-024f8        : ok=9    changed=3    unreachable=0    failed=0
dst-test-node-25d55        : ok=9    changed=3    unreachable=0    failed=0
localhost                  : ok=40   changed=6    unreachable=0    failed=0


real	31m9.637s
user	0m8.675s
sys	0m11.052s
ACTION [create] failed with exit status 512
```

I modified the dns entry in the above output. I'm on this commit: cf1fb0b

**Comment by barkerd427** [comment]
`openshift-master` doesn't exist, but `origin-master` does. Not sure if that's an error. I'll try to run this with master soon to see if that will work for me.

**Comment by barkerd427** [comment]
When I checkout master, I get this error, which is why I tried tagged versions instead.
```
➜  openshift-ansible git:(master) bin/cluster -vvvvv create aws dst-test
RUN [time ansible-playbook -vvvvv -i inventory/aws/hosts -e 'num_masters=1 num_nodes=2 cluster_id=dst-test cluster_env=dev num_etcd=0 num_infra=1 deployment_type=origin' playbooks/aws/openshift-cluster/launch.yml]
ERROR: become is not a legal parameter at this level in an Ansible Playbook

real	0m30.430s
user	0m0.996s
sys	0m0.785s
Traceback (most recent call last):
  File "bin/cluster", line 379, in <module>
    args.func(args)
  File "bin/cluster", line 69, in create
    self.action(args, inventory, cluster, playbook)
  File "bin/cluster", line 246, in action
    .format(args.action, exc))
ActionFailed: ACTION [create] failed: Command 'time ansible-playbook -vvvvv -i inventory/aws/hosts -e 'num_masters=1 num_nodes=2 cluster_id=dst-test cluster_env=dev num_etcd=0 num_infra=1 deployment_type=origin' playbooks/aws/openshift-cluster/launch.yml' returned non-zero exit status 1
```

**Comment by barkerd427** [comment]
Everything appears to work starting at this tag: `openshift-ansible-3.0.20-1`. From that point to master gives me the above error. I didn't understand the changing versioning system. I'll open an issue around that if there isn't one.

**Comment by barkerd427** [comment]
Closing and opening #1249.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
