### ISSUE TITLE
FAILED - RETRYING: Wait for all control plane pods to become ready ( one master architecture )

### ISSUE THREAD

**Issue by bessalahAmar** [openshift/openshift-ansible#12124]
#### Description

I'm new to openshift willing to setup openshift orirgin ( okd ) 3.11 from scratch using ansible playbooks. 

I have been trying to setup an openshift 3.11 ( okd ) cluster of 1 masters , 1 master-infra node , 1 infra node and 2 nodes but i'm having the error "FAILED - RETRYING: Wait for all control plane pods to become ready" so i changed my architecture to just : 1 master node with no other node to make it simple but still the same error.
 
the prerequisites.yml playbook works correctly
i get the error when running the deploy_cluster.yml playbook. ( more precisely master install : playbooks/openshift-master/config.yml )

i can see that the master is not listen on port 8443 ( after using netstat , check the output of netstat below )

> i can't deploy the cluster ( even with just one master node architecture )

if you need any other logs let me know. thanks 👍 

##### Version

* ansible version per `ansible --version`
```
config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

* The output of `git describe`
```
openshift-ansible-3.11.187-1
```

##### Steps To Reproduce
1. ansible-playbook openshift-ansible/playbooks/prerequisites.yml
2. ansible-playbook openshift-ansible/playbooks/deploy_cluster.yml

##### Expected Results
Openshift should be deployed

##### Observed Results

```

FAILED - RETRYING: Wait for all control plane pods to come up and become ready ( retries left)

[WARNING]: Module invocation had junk after the JSON data: Error in atexit._run_exitfuncs: Traceback (most recent call last):   File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs     func(*targs, **kargs)   File
"/tmp/ansible_oc_obj_payload_J7Lg3k/ansible_oc_obj_payload.zip/ansible/modules/oc_obj.py", line 1260, in cleanup AttributeError: 'NoneType' object has no attribute 'path' Error in sys.exitfunc: Traceback (most recent call last):
File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs     func(*targs, **kargs)   File "/tmp/ansible_oc_obj_payload_J7Lg3k/ansible_oc_obj_payload.zip/ansible/modules/oc_obj.py", line 1260, in cleanup AttributeError:
'NoneType' object has no attribute 'path'

```
then in the end of the playbook i get :

```
fatal: [master1.esb.orange.com]: FAILED! => {"changed": false, "msg": "Control plane pods didn't come up and become ready"}
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* operating system and version
```
CentOS Linux release 7.7.1908 (Core)
```

* inventory file 
```
[OSEv3:children]
masters
nodes
etcd



[OSEv3:vars]

ansible_ssh_user=vagrant
ansible_become=true
openshift_deployment_type=origin
openshift_disable_check=memory_availability,disk_availability
openshift_master_identity_providers = [{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
openshift_master_htpasswd_users={'okd_user_1': '$apr1$2t5fmsrN$mwss9saTPBkSVNpU1nE4M0', 'okd_user_2': '$apr1$/HYX.Tax$43UZOMzuEPgSHtXxvZk6f/'}
openshift_master_cluster_method=native
openshift_master_cluster_hostname= master1.esb.orange.com
openshift_master_cluster_public_hostname= master1.esb.orange.com


[masters]
master1.esb.orange.com

[nodes]
master1.esb.orange.com  openshift_node_group_name='node-config-master'

[etcd]
master1.esb.orange.com

```

* sudo docker ps 

```
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS               NAMES
992edc263a6c        0822d6d186ef                             "/bin/bash -c '#!/..."   5 minutes ago       Up 5 minutes                            k8s_controllers_master-controllers-master1.esb.orange.com_kube-system_04335d3709e8228377883a762ef7f830_0
53461bd8c237        e87e7804f2f5                             "/bin/sh -c '#!/bi..."   5 minutes ago       Up 5 minutes                            k8s_etcd_master-etcd-master1.esb.orange.com_kube-system_6910dffb162446fa4f37027521cba029_0
2be4c1e88a70        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           5 minutes ago       Up 5 minutes                            k8s_POD_master-controllers-master1.esb.orange.com_kube-system_04335d3709e8228377883a762ef7f830_0
3c127647d6a4        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           5 minutes ago       Up 5 minutes                            k8s_POD_master-etcd-master1.esb.orange.com_kube-system_6910dffb162446fa4f37027521cba029_0
4df094e29962        docker.io/openshift/origin-pod:v3.11.0   "/usr/bin/pod"           5 minutes ago       Up 5 minutes                            k8s_POD_master-api-master1.esb.orange.com_kube-system_d400ab198a15ccbe597efa10e38d0719_0
```

* sudo telnet master1.esb.orange.com 8443
```
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
```

* sudo netstat -tulpn
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1235/master
tcp        0      0 0.0.0.0:8444            0.0.0.0:*               LISTEN      22777/openshift
tcp        0      0 10.0.2.15:2379          0.0.0.0:*               LISTEN      22606/etcd
tcp        0      0 10.0.2.15:2380          0.0.0.0:*               LISTEN      22606/etcd
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd
tcp        0      0 127.0.0.1:36881         0.0.0.0:*               LISTEN      21714/hyperkube
tcp        0      0 10.0.2.15:53            0.0.0.0:*               LISTEN      92666/dnsmasq
tcp        0      0 192.168.0.194:53        0.0.0.0:*               LISTEN      92666/dnsmasq
tcp        0      0 172.17.0.1:53           0.0.0.0:*               LISTEN      92666/dnsmasq
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1079/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      1235/master
tcp6       0      0 :::10250                :::*                    LISTEN      21714/hyperkube
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd
tcp6       0      0 fe80::5054:ff:fe8a:f:53 :::*                    LISTEN      92666/dnsmasq
tcp6       0      0 fe80::a00:27ff:fed5::53 :::*                    LISTEN      92666/dnsmasq
tcp6       0      0 :::22                   :::*                    LISTEN      1079/sshd
udp        0      0 0.0.0.0:810             0.0.0.0:*                           636/rpcbind
udp        0      0 127.0.0.1:323           0.0.0.0:*                           641/chronyd
udp        0      0 10.0.2.15:53            0.0.0.0:*                           92666/dnsmasq
udp        0      0 192.168.0.194:53        0.0.0.0:*                           92666/dnsmasq
udp        0      0 172.17.0.1:53           0.0.0.0:*                           92666/dnsmasq
udp        0      0 0.0.0.0:111             0.0.0.0:*                           1/systemd
udp6       0      0 :::810                  :::*                                636/rpcbind
udp6       0      0 ::1:323                 :::*                                641/chronyd
udp6       0      0 fe80::5054:ff:fe8a:f:53 :::*                                92666/dnsmasq
udp6       0      0 fe80::a00:27ff:fed5::53 :::*                                92666/dnsmasq
udp6       0      0 :::111                  :::*                                1/systemd

```

* sudo oc get nodes
```
The connection to the server master1.esb.orange.com:8443 was refused - did you specify the right host or port?
```

* sudo oc get pods
```
The connection to the server master1.esb.orange.com:8443 was refused - did you specify the right host or port?
```

* vboxmanage showvminfo master1.esb.orange.com
```
Name:                        master1.esb.orange.com
Groups:                      /
Guest OS:                    Red Hat (64-bit)
UUID:                        9b31e9be-a3e8-43e9-b6c9-372b803519ab
Config file:                 C:\Users\\VirtualBox VMs\master1.esb.orange.com\master1.esb.orange.com.vbox
Snapshot folder:             C:\Users\\VirtualBox VMs\master1.esb.orange.com\Snapshots
Log folder:                  C:\Users\\VirtualBox VMs\master1.esb.orange.com\Logs
Hardware UUID:               9b31e9be-a3e8-43e9-b6c9-372b803519ab
Memory size                  1024MB
Page Fusion:                 disabled
VRAM size:                   16MB
CPU exec cap:                100%
HPET:                        disabled
CPUProfile:                  host
Chipset:                     piix3
Firmware:                    BIOS
Number of CPUs:              4
PAE:                         enabled
Long Mode:                   enabled
Triple Fault Reset:          disabled
APIC:                        enabled
X2APIC:                      enabled
Nested VT-x/AMD-V:           disabled
CPUID Portability Level:     0
CPUID overrides:             None
Boot menu mode:              message and menu
Boot Device 1:               Floppy
Boot Device 2:               DVD
Boot Device 3:               HardDisk
Boot Device 4:               Not Assigned
ACPI:                        enabled
IOAPIC:                      enabled
BIOS APIC mode:              APIC
Time offset:                 0ms
RTC:                         UTC
Hardware Virtualization:     enabled
Nested Paging:               enabled
Large Pages:                 enabled
VT-x VPID:                   enabled
VT-x Unrestricted Exec.:     enabled
Paravirt. Provider:          Default
Effective Paravirt. Prov.:   KVM
State:                       running (since 2020-03-12T15:33:58.180000000)
Graphics Controller:         VBoxVGA
Monitor count:               1
3D Acceleration:             disabled
2D Video Acceleration:       disabled
Teleporter Enabled:          disabled
Teleporter Port:             0
Teleporter Address:
Teleporter Password:
Tracing Enabled:             disabled
Allow Tracing to Access VM:  disabled
Tracing Configuration:
Autostart Enabled:           disabled
Autostart Delay:             0
Default Frontend:
VM process priority:         default
Storage Controller Name (0):            IDE
Storage Controller Type (0):            PIIX4
Storage Controller Instance Number (0): 0
Storage Controller Max Port Count (0):  2
Storage Controller Port Count (0):      2
Storage Controller Bootable (0):        on
IDE (0, 0): C:\Users\\VirtualBox VMs\master1.esb.orange.com\centos-7-1-1.x86_64.vdi (UUID: 6a92c2a0-3f5e-47a4-b193-5eacb16e67d0)
IDE (0, 1): C:\Users\
\VirtualBox VMs\master1.esb.orange.com\extra/persistentStorage.vdi (UUID: 44a0e687-72f4-4cc8-a6d4-425f8c1327ad)
NIC 1:                       MAC: 5254008AFEE6, Attachment: NAT, Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 1 Settings:  MTU: 0, Socket (send: 64, receive: 64), TCP Window (send:64, receive: 64)
NIC 1 Rule(0):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 2222, guest ip = , guest port = 22
NIC 2:                       MAC: 080027D57B42, Attachment: Host-only Interface 'VirtualBox Host-Only Ethernet Adapter #2', Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 3:                       disabled
NIC 4:                       disabled
NIC 5:                       disabled
NIC 6:                       disabled
NIC 7:                       disabled
NIC 8:                       disabled
Pointing Device:             PS/2 Mouse
Keyboard Device:             PS/2 Keyboard
UART 1:                      disabled
UART 2:                      disabled
UART 3:                      disabled
UART 4:                      disabled
LPT 1:                       disabled
LPT 2:                       disabled
Audio:                       enabled (Driver: DSOUND, Controller: AC97, Codec: STAC9700)
Audio playback:              disabled
Audio capture:               disabled
Clipboard Mode:              disabled
Drag and drop Mode:          disabled
Session name:                headless
Video mode:                  720x400x0 at 0,0 enabled
VRDE:                        disabled
OHCI USB:                    disabled
EHCI USB:                    disabled
xHCI USB:                    disabled

USB Device Filters:

<none>

Available remote USB devices:

<none>

Currently Attached USB Devices:

<none>

Bandwidth groups:  <none>

Shared folders:<none>

VRDE Connection:             not active
Clients so far:              0

Capturing:                   active
Capture audio:               active
Capture screens:             0
Capture file:                C:\Users\\VirtualBox VMs\master1.esb.orange.com\master1.esb.orange.com.webm
Capture dimensions:          1024x768
Capture rate:                512kbps
Capture FPS:                 25kbps
Capture options:             vc_enabled=true,ac_enabled=true,ac_profile=med

Guest:

Configured memory balloon size: 0MB
OS type:                     RedHat_64
Additions run level:         0

Guest Facilities:

No active facilities
```

*sudo iptables -S
```
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION
-N KUBE-FIREWALL
-N OS_FIREWALL_ALLOW
-A INPUT -j KUBE-FIREWALL
-A INPUT -j OS_FIREWALL_ALLOW
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER-ISOLATION -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 10250 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 10256 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 4789 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 9000:10000 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 1936 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 2379 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 2380 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 8443 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 8444 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 8053 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 8053 -j ACCEPT
```

**Comment by bessalahAmar** [comment]
i tried with an all in one inventory file 
https://github.com/openshift/openshift-ansible/blob/release-3.11/inventory/hosts.localhost
i'm getting the same result

i'm wondering if it's not due to the virtual box vm environnement ( i can see i have two interfaces eth0 and eth1 , one on nat the other bridge mode )

**Comment by bessalahAmar** [comment]
i tried in another vm and its working.

but still wondering what is blocking in my other vm. maybe it's due to having 2 interfaces eth0 and eth1 , one for the nat and the other on bridge mode.

**Comment by sekayasin** [comment]
@vrutkovs any help on this above

**Comment by matsonkepson** [comment]
are there some workarounds for this ?

**Comment by mtnbikenc** [comment]
> i tried in another vm and its working.
> 
> but still wondering what is blocking in my other vm. maybe it's due to having 2 interfaces eth0 and eth1 , one for the nat and the other on bridge mode.

Only nodes with single interfaces are supported.  The single interface should be resolvable through DNS.
https://docs.openshift.com/container-platform/3.11/install/prerequisites.html#dns-config-prereq
