### ISSUE TITLE
Release-3.11 Openshift-Ansible Docker Build is failing 

### ISSUE THREAD

**Issue by RiteshWalia** [openshift/openshift-ansible#12132]
#### Description

Getting errors while building Openshift-Ansible docker images . 

I'm following instructions mentioned in this doc - https://github.com/openshift/openshift-ansible/blob/release-3.11/BUILD.md#build-an-openshift-ansible-container-image

##### Version

```
[root@osmaster-1 openshift-ansible]# ansible --version
ansible 2.9.5
  config file = /var/mnt/volume/ritesh/workspace/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

[root@osmaster-1 openshift-ansible]# git describe
openshift-ansible-3.11.170-1-2-gd9602c6  
```

##### Steps To Reproduce
1. [step 1] git clone https://github.com/openshift/openshift-ansible.git
2. [step 2] git checkout release-3.11
3. [step 3] cd openshift-ansible
4. [step 4] docker build -f images/installer/Dockerfile -t openshift-ansible .

##### Expected Results
Openshift containers should be build successfully 

```
There should not be any errors while building docker containers
```

##### Observed Results

Docker build command is failing below are the error details

```
[root@osmaster-1 openshift-ansible]# docker build -f images/installer/Dockerfile -t openshift-ansible .

Error Message ->

  Downloading https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d348039954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL-19.1.0-py2.py3-none-any.whl (53kB)
Collecting wheel==0.30.0 (from azure-cli-core==2.0.35->ansible[azure])
  Downloading https://files.pythonhosted.org/packages/0c/80/16a85b47702a1f47a63c104c91abdd0a6704ee8ae3b4ce4afc49bc39f9d9/wheel-0.30.0-py2.py3-none-any.whl (49kB)
Collecting pygments (from azure-cli-core==2.0.35->ansible[azure])
  Downloading https://files.pythonhosted.org/packages/6e/4d/4d2fe93a35dfba417311a4ff627489a947b01dc0cc377a3673c00cf7e4b2/Pygments-2.6.1.tar.gz (3.3MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3VoJ0k/pygments/setup.py", line 38, in <module>
        packages = find_packages(include=['pygments', 'pygments.*']),
    TypeError: find_packages() got an unexpected keyword argument 'include'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3VoJ0k/pygments/
You are using pip version 8.1.2, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c INSTALL_PKGS="python-lxml python-dns pyOpenSSL python2-cryptography openssl python2-passlib httpd-tools openssh-clients origin-clients iproute patch"  && yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS  && EPEL_PKGS="ansible-2.9.1 python2-boto python2-crypto which python2-pip.noarch python2-scandir python2-packaging azure-cli-2.0.46"  && yum install -y epel-release  && yum install -y --setopt=tsflags=nodocs $EPEL_PKGS  && if [ "$(uname -m)" == "x86_64" ]; then yum install -y https://sdodson.fedorapeople.org/google-cloud-sdk-183.0.0-3.el7.x86_64.rpm ; fi  && yum install -y java-1.8.0-openjdk-headless  && rpm -V $INSTALL_PKGS $EPEL_PKGS $EPEL_TESTING_PKGS  && pip install 'apache-libcloud~=2.2.1' 'SecretStorage<3' 'ansible[azure]' 'boto3==1.4.6'  && yum clean all' returned a non-zero code: 1
```

Complete Logs - https://gist.github.com/RiteshWalia/a8ab2fa9fb9b6600918883cd2a564af7

##### Additional Information

```
[root@osmaster-1 openshift-ansible]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
```

**Comment by RiteshWalia** [comment]
After replacing `ansible[azure]` with `ansible` in file "images/installer/Dockerfile" build is working fine. But can someone from community confirm if that's correct solution ?

**Comment by RiteshWalia** [comment]
@mayorova As per bug 1816422 I tried to include fix in file - roles/kuryr/tasks/master.yaml but that also doesn't resolves this issue. 

Pls share ur thoughts

**Comment by MaysaMacedo** [comment]
@RiteshWalia That fix is for another bug, not the one reported here. I linked this current issue, as it's failing on the CI and is blocking the PR to get merged.

**Comment by sdodson** [comment]
/assign @mtnbikenc 
Russ, have you seen this happening?

**Comment by mtnbikenc** [comment]
Yes, I've seen this on our PRs but did not get to it yet.  Related PR LGTM.
