### ISSUE TITLE
« Warn user about bad openshift_hostname values » failed on Vagrant

### ISSUE THREAD

**Issue by harobed** [openshift/openshift-ansible#1350]
« Warn user about bad openshift_hostname values » failed on Vagrant : 

```
TASK: [shell getent ahostsv4 {{ openshift.common.hostname }} | head -n 1 | awk '{ print $1 }'] ***
ok: [master]
ok: [node2]
ok: [node1]

TASK: [Warn user about bad openshift_hostname values] *************************
fatal: [master] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1036, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/action_plugins/pause.py", line 103, in run
    tcflush(sys.stdin, TCIFLUSH)
error: (25, 'Inappropriate ioctl for device')


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/stephane/vagrant.retry

localhost                  : ok=10   changed=0    unreachable=0    failed=0
master                     : ok=23   changed=0    unreachable=0    failed=1
node1                      : ok=23   changed=0    unreachable=0    failed=1
node2                      : ok=23   changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Why ? 

```
$ vagrant ssh master
$ sudo su
root@ose3-master vagrant]# getent ahostsv4 ose3-master.example.com | head -n 1 | awk '{ print $1 }'
127.0.0.1
[root@ose3-master vagrant]# getent ahostsv4
127.0.0.1       ose3-master.example.com ose3-master localhost localhost.localdomain localhost4 localhost4.localdomain4
127.0.0.1       localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.100.200 ose3-node1.example.com
192.168.100.201 ose3-node2.example.com
192.168.100.100 ose3-master.example.com
```

Ansible check first IP found.

**Comment by harobed** [comment]
Fix : 

```
getent ahostsv4 {{ openshift.common.hostname }} | grep -v "127.0.0.1" | head -n 1 | awk '{ print $1 }'
```

at https://github.com/openshift/openshift-ansible/blob/34b68829e36f7151c6c09411585b25b2340d2823/playbooks/common/openshift-cluster/validate_hostnames.yml#L18

**Comment by sdodson** [comment]
@harobed Out of curiosity have you deployed a router in this environment using Origin v1.1.1? Did the liveness probes work properly there?

Do you not get a prompt exposed via Vagrant? Does this happen immediately or does it sit on this task until it times out?

**Comment by harobed** [comment]
> @harobed Out of curiosity have you deployed a router in this environment using Origin v1.1.1?

I've deployed nothing, it's fresh install.

> Do you not get a prompt exposed via Vagrant? 

No, nothing.

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.
