### ISSUE TITLE
`bin/ossh --list` fails in version >= 3.0.27-1

### ISSUE THREAD

**Issue by pikariop** [openshift/openshift-ansible#1730]
The following problem arises with latest 'master', 'prod' or the latest release tag. It seems that v. 3.0.27-1 introduced this behavior.

```
$ git checkout openshift-ansible-3.0.27-1

$ bin/ossh --list
Traceback (most recent call last):
  File "bin/ossh", line 216, in <module>
    ossh = Ossh()
  File "bin/ossh", line 46, in __init__
    self.list_hosts()
  File "bin/ossh", line 168, in list_hosts
    '{oo_id:<15} {oo_public_ip:<18} {oo_private_ip:<18}'.format(**server_info)
KeyError: 'oo_name'
```

Everything seems fine when using 3.0.26-1

```
$ git checkout openshift-ansible-3.0.26-1

$ bin/ossh --list
test-node-infra-1               test     redacted
test-master-1                   test     redacted
test-node-compute-1             test     redacted
test-node-compute-2             test     redacted
```

Using v. >= 3.0.27-1 and dumping `server_info` contents:
https://github.com/openshift/openshift-ansible/blob/master/bin/ossh#L125

```
        for host_id, server_info in self.host_inventory.items():
            pprint.pprint(server_info)
            #print '{oo_name:<35} {oo_clusterid:<10} {oo_environment:<8} ' \
            #    '{oo_id:<15} {oo_public_ip:<18} {oo_private_ip:<18}'.format(**server_info)
```

It seems that none of the `oo_` variables are defined, but instead `server_info` is a list of `ec2_` prefixed stuff

```
$ bin/ossh --list

{u'ec2__in_monitoring_element': False,
 u'ec2_ami_launch_index': u'1',
 u'ec2_architecture': u'x86_64',
 u'ec2_client_token': u'',
 u'ec2_dns_name': u'redacted.compute.amazonaws.com',
 u'ec2_ebs_optimized': False,
 u'ec2_eventsSet': u'',
 u'ec2_group_name': u'',
 u'ec2_hypervisor': u'xen',
     ....
```

**Comment by detiber** [comment]
@twiest

**Comment by twiest** [comment]
@kwoodson fyi. Let's talk about this on Monday.

**Comment by michaelgugino** [comment]
The affected code path has been removed.

Closing this issue because it is no longer valid.
