### ISSUE TITLE
Install fails at containerized check if the host doesn't exist

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-ansible#1985]
This is more of a user fault, but the error message is not helpful.

The installation fails at checking if the install should be containerized when a host is listed in the inventory file, but does not exist.

ie. the following, and node2.example.com does not resolve to any host

[nodes]
node1.example.com
node2.example.com

**Comment by detiber** [comment]
@andrewklau could you paste a copy of the error? I would expect that there would be a failure at the beginning of a play when gather_facts forces the setup module to run against the host, is it possible that cached facts are involved?

**Comment by andrewklau** [comment]
Yep at the facts check:

TASK: [openshift_facts | Gather Cluster facts and set is_containerized if needed] *** 
fatal: [master1.example.com] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 589, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 793, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1017, in _executor_internal_inner
    complex_args = template.template(self.basedir, complex_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 6, in root
  File "/usr/lib/python2.7/site-packages/jinja2/runtime.py", line 156, in resolve
    return self.parent[key]
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 205, in __getitem__
    return template(self.basedir, var, self.vars, fail_on_undefined=self.fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 14, in root
  File "/root/openshift-ansible/filter_plugins/oo_filters.py", line 139, in oo_collect
    retval = [FilterModule.get_attr(d, attribute) for d in data]
  File "/root/openshift-ansible/filter_plugins/oo_filters.py", line 49, in get_attr
    ptr = ptr[attr]
KeyError: 'openshift'


FATAL: all hosts have already failed -- aborting

**Comment by detiber** [comment]
@andrewklau ah, I see the issue now, we are probably trying to gather data about the host without taking into account that the host might have failed.

@abutcher we probably do this in way too many places...

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if it can still be reproduced and you would like to see action taken on it.
