### ISSUE TITLE
TASK: [openshift_facts | Gather Cluster facts and set is_containerized if needed]  fails if more than one docker package is installed

### ISSUE THREAD

**Issue by TheMeier** [openshift/openshift-ansible#2106]
Due to a previouse abortet yum transaction I accidentally had two docker packages installed:

```
rpm -q docker
docker-1.9.1-31.origin.1.el7.centos.x86_64
docker-1.10.3-44.el7.centos.x86_64

```

This triggered the following error:

```
2016-06-30 15:16:13,575 p=78705 u=root |  TASK: [openshift_facts | Gather Cluster facts and set is_containerized if needed] *** 
2016-06-30 15:16:14,302 p=78705 u=root |  failed: [node01] => {"failed": true, "parsed": false}
2016-06-30 15:16:14,303 p=78705 u=root |  Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1467292573.66-63895857235501/openshift_facts", line 7245, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1467292573.66-63895857235501/openshift_facts", line 2111, in main
    protected_facts_to_overwrite)
  File "/root/.ansible/tmp/ansible-tmp-1467292573.66-63895857235501/openshift_facts", line 1589, in __init__
    protected_facts_to_overwrite)
  File "/root/.ansible/tmp/ansible-tmp-1467292573.66-63895857235501/openshift_facts", line 1622, in generate_facts
    defaults = self.get_defaults(roles, deployment_type)
  File "/root/.ansible/tmp/ansible-tmp-1467292573.66-63895857235501/openshift_facts", line 1728, in get_defaults
    version_info = get_docker_version_info()
  File "/root/.ansible/tmp/ansible-tmp-1467292573.66-63895857235501/openshift_facts", line 1107, in get_docker_version_info
    version_info = yaml.safe_load(get_version_output('/usr/bin/docker', 'version'))
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not found expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<string>", line 5, column 1:
    docker-common-1.10.3-44.el7.cent ... 
    ^
could not found expected ':'
  in "<string>", line 6, column 12:
     Go version:      go1.4.2
               ^
OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
```

maybe its worth the effort to check for such a conditon

**Comment by abutcher** [comment]
Hey @TheMeier! I think we'll want to catch this exception in `get_docker_version_info` to provide a more helpful error but, since this is a rare edge case, we likely won't get around to making a change soon.
