### ISSUE TITLE
Task Gather Cluster facts and set is_containerized if needed] => KeyError: 'openshift'

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#2328]
Hi!

After change my ansible version from 2.1 (See #2312), I got this error:

```
TASK [openshift_facts : Gather Cluster facts and set is_containerized if needed] ***
task path: /root/openshift/openshift-ansible/roles/openshift_facts/tasks/main.yml:26
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 120, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 369, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 230, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 307, in post_validate

▽
    value = templar.template(getattr(self, name))

▽
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 356, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 356, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 328, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 489, in _do_template
    res = j2_concat(rf)
  File "<template>", line 6, in root
  File "/usr/lib/python2.7/site-packages/jinja2/runtime.py", line 153, in resolve
    return self.parent[key]
  File "/usr/lib/python2.7/site-packages/ansible/template/vars.py", line 86, in __getitem__
    return self._templar.template(variable)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 328, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 489, in _do_template
    res = j2_concat(rf)
  File "<template>", line 14, in root
  File "/usr/share/ansible_plugins/filter_plugins/oo_filters.py", line 139, in oo_collect
    retval = [FilterModule.get_attr(d, attribute) for d in data]
  File "/usr/share/ansible_plugins/filter_plugins/oo_filters.py", line 49, in get_attr
    ptr = ptr[attr]
KeyError: 'openshift'

fatal: [FQDN]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

Current git commit:

```
[root@ansible openshift-ansible]$ git log -1
commit 7b262607ff4dedf7d4069d062b85118c613de42c
Merge: 096aec2 e11e0d4
Author: Scott Dodson <sdodson@redhat.com>
Date:   Thu Aug 4 11:16:55 2016 -0400

    Merge pull request #2256 from sdodson/enterprise-3.2

    Enterprise 3.2 backports
```

I wound why this error happens on the **2nd** master, not on the first.

All master/nodes does not have own host variables.

**Comment by detiber** [comment]
@sdodson I suspect this might be some edge case that we aren't hitting in 1.3/3.3 currently, lets dig in deeper early next week.

**Comment by jkroepke** [comment]
Note: This error happends on Ansible 2.0. Not on Ansible 2.2.

**Comment by detiber** [comment]
@jkroepke ah, thanks. We most likely need to update our check for supported versions. I don't think we'll try to support ansible 2.0, since the performance issue we see related to nested includes in 2.1 also exists in 2.0 and there is a but in 2.0 that prevents the causes issues when using delegate_to the ansible_becomes value differs between the play host and the delegate_to host.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
