### ISSUE TITLE
crash on gathering cluster facts

### ISSUE THREAD

**Issue by vanloswang** [openshift/openshift-ansible#2983]
Just chkconfig NetworkManager off  and service NetworkManager stop and del the route of '10.1.0.0/16 dev tun0', and uninstall a cluster, and then chkconfig NetworkManager on  and service NetworkManager start and readd the route of '10.1.0.0/16 dev tun0', and then install again, it always crash on gathering cluster facts.

##### Version
openshift-ansible 3.2.7
ansible 1.9.6

##### Steps To Reproduce
1.  chkconfig NetworkManager off  and service NetworkManager stop and del the route of '10.1.0.0/16 dev tun0'
2. uninstall the cluster
3. chkconfig NetworkManager on  and service NetworkManager start and readd the route of '10.1.0.0/16 dev tun0'
4. install again

##### Current Result
```bash
2016-12-16 22:49:32,633 p=25335 u=root |  TASK: [openshift_facts | Gather Cluster facts and set is_containerized if needed] *** 
2016-12-16 22:49:33,210 p=25335 u=root |  failed: [192.168.10.12] => {"failed": true, "parsed": false}
2016-12-16 22:49:33,210 p=25335 u=root |  Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1481899772.71-21258692195242/openshift_facts", line 7259, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1481899772.71-21258692195242/openshift_facts", line 2125, in main
    protected_facts_to_overwrite)
  File "/root/.ansible/tmp/ansible-tmp-1481899772.71-21258692195242/openshift_facts", line 1603, in __init__
    protected_facts_to_overwrite)
  File "/root/.ansible/tmp/ansible-tmp-1481899772.71-21258692195242/openshift_facts", line 1636, in generate_facts
    defaults = self.get_defaults(roles, deployment_type)
  File "/root/.ansible/tmp/ansible-tmp-1481899772.71-21258692195242/openshift_facts", line 1679, in get_defaults
    ip_addr = self.system_facts['default_ipv4']['address']
KeyError: 'address'
OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 192.168.10.12 closed.
```

##### Expected Result
no such an error.

##### Additional Information
CentOS 7.2.1511 updated some packages

**Comment by sdodson** [comment]
Ansible 2.2 is required for master, release-1.4, release-1.3, and release-1.2 branches. Can you please try with ansible 2.2? I suspect the issue will pesist but we won't fix any problems with running our code on Ansible 1.9.6 at this point so no point in using it.

**Comment by vanloswang** [comment]
@sdodson it is release-1.2, I reinstall the vm and then it can not appear now. but before reinstall the vm, it appears ervery time when installing a cluster.

**Comment by vanloswang** [comment]
it caused by broken dnf.
