### ISSUE TITLE
Apparent hang during os_update_latest task of "bin/cluster create aws ..."

### ISSUE THREAD

**Issue by jupierce** [openshift/openshift-ansible#2999]
##### Version
openshift-ansible-3.4.17-1-275-g616ca82

ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

Fedora 24

##### Steps To Reproduce
1. Followed doc for AWS setup
2. bin/cluster create aws jupierce

##### Current Result
Waited more than an hour for os_update_latest to terminate. Eventually Ctrl-C'd:
```
TASK [openshift_repos : assert] ************************************************
ok: [jupierce-master-9278b] => {
    "changed": false, 
    "msg": "All assertions passed"
}
ok: [jupierce-node-infra-c1c38] => {
    "changed": false, 
    "msg": "All assertions passed"
}
ok: [jupierce-node-compute-2c4d0] => {
    "changed": false, 
    "msg": "All assertions passed"
}
ok: [jupierce-node-compute-65492] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [openshift_repos : Ensure libselinux-python is installed] *****************
ok: [jupierce-master-9278b]
ok: [jupierce-node-compute-65492]
ok: [jupierce-node-compute-2c4d0]
ok: [jupierce-node-infra-c1c38]

TASK [openshift_repos : Create any additional repos that are defined] **********
skipping: [jupierce-master-9278b]
skipping: [jupierce-node-compute-2c4d0]
skipping: [jupierce-node-compute-65492]
skipping: [jupierce-node-infra-c1c38]

TASK [openshift_repos : Remove the additional repos if no longer defined] ******
ok: [jupierce-node-compute-65492]
ok: [jupierce-node-compute-2c4d0]
ok: [jupierce-master-9278b]
ok: [jupierce-node-infra-c1c38]

TASK [openshift_repos : Configure origin gpg keys if needed] *******************
changed: [jupierce-node-compute-65492]
changed: [jupierce-node-compute-2c4d0]
changed: [jupierce-master-9278b]
changed: [jupierce-node-infra-c1c38]

TASK [openshift_repos : Configure origin yum repositories RHEL/CentOS] *********
changed: [jupierce-node-compute-2c4d0]
changed: [jupierce-master-9278b]
changed: [jupierce-node-compute-65492]
changed: [jupierce-node-infra-c1c38]

TASK [os_update_latest : Update all packages] **********************************
changed: [jupierce-node-infra-c1c38]
^CTraceback (most recent call last):
  File "bin/cluster", line 419, in <module>
    args.func(args)
  File "bin/cluster", line 87, in create
    self.action(args, inventory, cluster, playbook)
  File "bin/cluster", line 261, in action
Process WorkerProcess-246:
Process WorkerProcess-248:
    subprocess.check_call(command, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 535, in check_call
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process WorkerProcess-247:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib64/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
 [ERROR]: User interrupted execution
```
##### Additional Information
Hack day run.

**Comment by detiber** [comment]
@jupierce I suspect the issue is either intermittent connectivity and ssh hanging, or some other process is holding on to the rpm database and the 'Update all packages' task is stuck waiting for a lock.

That said, bin/cluster isn't considered an officially supported tool, and is only still in the repo because there are existing legacy users that are still willing to maintain it. It is not something that we test or exercise regularly.

**Comment by jupierce** [comment]
@detiber Fair, enough. Thanks!
