### ISSUE TITLE
BYO v1.3 playbook fails on Fedora 25 with yaml.scanner.ScannerError 

### ISSUE THREAD

**Issue by vnugent** [openshift/openshift-ansible#3211]
#### Description

BYO v1.3 playbook on Fedora 25 fails with yaml parsing error on master node
```
fatal: [172.18.17.19]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "openshift_facts"}, "module
_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_TL8Xe8/ansible_module_openshift_fa
cts.py\", line 2223, in <module>\r\n    main()\r\n  File \"/tmp/ansible_TL8Xe8/ansible_module_openshift_facts.py\", line 2204,
 in main\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_TL8Xe8/ansible_module_openshift_facts.py\", line 1672, 
in __init__\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_TL8Xe8/ansible_module_openshift_facts.py\", line 171
0, in generate_facts\r\n    defaults = self.get_defaults(roles, deployment_type, deployment_subtype)\r\n  File \"/tmp/ansible_TL8Xe8/ansible_module_openshift_facts.py\", line 1800, in get_defaults\r\n    version_info = get_docker_version_info()\r\n  File \"/tmp/ansible_TL8Xe8/ansible_module_openshift_facts.py\", line 1140, in get_docker_version_info\r\n    version_info = yaml.safe_load(get_version_output('/usr/bin/docker', 'version'))\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/__init__.py\", line 93, in safe_load\r\n    return load(stream, SafeLoader)\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/__init__.py\", line 71, in load\r\n    return loader.get_single_data()\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/constructor.py\", line 37, in get_single_data\r\n    node = self.get_single_node()\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/composer.py\", line 36, in get_single_node\r\n    document = self.compose_document()\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/composer.py\", line 55, in compose_document\r\n    node = self.compose_node(None, None)\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/composer.py\", line 84, in compose_node\r\n    node = self.compose_mapping_node(anchor)\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/composer.py\", line 133, in compose_mapping_node\r\n    item_value = self.compose_node(node, item_key)\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/composer.py\", line 84, in compose_node\r\n    node = self.compose_mapping_node(anchor)\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/composer.py\", line 127, in compose_mapping_node\r\n    while not self.check_event(MappingEndEvent):\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/parser.py\", line 98, in check_event\r\n    self.current_event = self.state()\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/parser.py\", line 428, in parse_block_mapping_key\r\n    if self.check_token(KeyToken):\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/scanner.py\", line 116, in check_token\r\n    self.fetch_more_tokens()\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/scanner.py\", line 220, in fetch_more_tokens\r\n    return self.fetch_value()\r\n  File \"/usr/lib64/python2.7/site-packages/yaml/scanner.py\", line 576, in fetch_value\r\n    self.get_mark())\r\nyaml.scanner.ScannerError: mapping values are not allowed here\r\n  in \"<string>\", line 4, column 63:\r\n     ... ing read locks for locker 0x3486: 1443/140007870522688\r\n                                         ^\r\n", "msg": "MODULE FAILURE"}
```

##### Version
Ansible was downgraded to to get around issue https://github.com/openshift/openshift-ansible/issues/3111
```
# ansible-playbook --version
ansible-playbook 2.1.2.0
```

If you're operating from a **git clone**:

* The output of `git describe`
```
# git describe 
openshift-ansible-3.3.61-1-2-g59a949d
```
##### Steps To Reproduce
1. git clone https://github.com/openshift/openshift-ansible.git
2. git checkout origin/release-1.3
3. ansible-playbook ansible-playbook -vvv -i origin-os1.inventory openshift-ansible/playbooks/byo/config.yml

##### Expected Results
playbook finishes without errors

### master and node
Fedora release 25 (Twenty Five)

**Comment by abutcher** [comment]
Hey @vnugent, we [require at least 2.2.0.0 via a callback](https://github.com/openshift/openshift-ansible/blob/master/callback_plugins/aa_version_requirement.py#L32) and we'll need to figure out why that callback failed. 2.2.0.0* is the only working version due to #3111

**Comment by mtnbikenc** [comment]
@abutcher I expect the callback didn't run because callback_plugins is not configured in the local ansible.cfg file.

cc: @tbielawa

**Comment by detiber** [comment]
@mtnbikenc we should probably remove ansible.cfg from the .gitignore file and ship a default with it configured.

**Comment by vnugent** [comment]
I have since downgraded the master to Fedora 24 with `2.2.1.0-1.fc24 ` and still no luck

**Comment by vnugent** [comment]
```
# ansible --version
ansible 2.2.1.0
# cat /etc/redhat-release 
Fedora release 24 (Twenty Four)
# git describe
openshift-ansible-3.5.2-1-69-ge6bec56
```

```
TASK [openshift_master : set_fact] *********************************************
task path: /root/openshift-ansible/roles/openshift_master/tasks/main.yml:146
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 443, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 248, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 373, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 427, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 383, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 583, in do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root

  File "/root/openshift-ansible/filter_plugins/openshift_master.py", line 492, in translate_idps
    Dumper=AnsibleDumper)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 215, in represent_list
    return self.represent_sequence(u'tag:yaml.org,2002:seq', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 101, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: htpasswd_auth
fatal: [172.18.17.19]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

**Comment by abutcher** [comment]
Will have to downgrade to 2.2.0.0, see #3111

**Comment by vnugent** [comment]
Downgraded.  Now it's a different error on the node:
```
# ansible-playbook --version
ansible-playbook 2.2.0.0
```

```
TASK [set_fact] ****************************************************************
task path: /root/openshift-ansible/playbooks/common/openshift-cluster/initialize_facts.yml:16
fatal: [172.18.17.27]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'openshift'\n\nThe error appears to have been in '/root/openshift-ansible/playbooks/common/openshift-cluster/initialize_facts.yml': line 16, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n        hostname: \"{{ openshift_hostname | default(None) }}\"\n  - set_fact:\n    ^ here\n"
}
 ```

**Comment by abutcher** [comment]
@vnugent Does an error occur earlier in the run? That failure looks like a symptom of an earlier failure during fact collection.

**Comment by vnugent** [comment]
I was back to square one. In summary:
- ansible  2.2.0.0: ansible ssh.py filedescriptor out of range in select() https://github.com/openshift/openshift-ansible/issues/3111#issuecomment-278435484
- ansible 2.2.1.0 same as https://github.com/openshift/openshift-ansible/issues/3111

**Comment by vnugent** [comment]
Could anyone kindly suggest how to set up a working cluster?  I simplified the inventory to 1 single node and have tried various combinations of Fedora 24, 25, Centos7, with and without ansible_connection=local, containerized=true, latest master, 1.4 branch, ansible 2.2.0.0, 2.2.1.

**Comment by vnugent** [comment]
I was able to work around this issue by completely removing yum/dnf ansible and instead using pip to install ansible.
`pip install ansible==2.2.0.0`
You might need to pip upgrade MarkupSafe and jinja2 if encountered errors.
