### ISSUE TITLE
Problems installing origin via ansible

### ISSUE THREAD

**Issue by mmaier2** [openshift/openshift-ansible#323]
Hi,

I'm using RHEL7 and tried to install OS Origin via the ansible. That's my error:

```
TASK: [openshift_facts ] ****************************************************** 
ok: [master1.tsi-af.de] => (item={'local_facts': {'public_hostname': u'', 'hostname': u'', 'deployment_type': u'origin'}, 'role': 'common'})
failed: [master1.tsi-af.de] => (item={'local_facts': {'pod_cidr': u'', 'labels': u'', 'resources_cpu': u'', 'annotations': u'', 'resources_memory': u''}, 'role': 'node'}) => {"failed": true, "item": {"local_facts": {"annotations": "", "labels": "", "pod_cidr": "", "resources_cpu": "", "resources_memory": ""}, "role": "node"}, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1435915919.4-173473263131782/openshift_facts", line 5377, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1435915919.4-173473263131782/openshift_facts", line 855, in main
    openshift_facts = OpenShiftFacts(role, fact_file, local_facts)
  File "/root/.ansible/tmp/ansible-tmp-1435915919.4-173473263131782/openshift_facts", line 643, in __init__
    self.facts = self.generate_facts(local_facts)
  File "/root/.ansible/tmp/ansible-tmp-1435915919.4-173473263131782/openshift_facts", line 655, in generate_facts
    local_facts = self.init_local_facts(local_facts)
  File "/root/.ansible/tmp/ansible-tmp-1435915919.4-173473263131782/openshift_facts", line 816, in init_local_facts
    new_local_facts = merge_facts(local_facts, facts_to_set)
  File "/root/.ansible/tmp/ansible-tmp-1435915919.4-173473263131782/openshift_facts", line 544, in merge_facts
    facts[key] = merge_facts(value, new[key])
  File "/root/.ansible/tmp/ansible-tmp-1435915919.4-173473263131782/openshift_facts", line 544, in merge_facts
    facts[key] = merge_facts(value, new[key])
  File "/root/.ansible/tmp/ansible-tmp-1435915919.4-173473263131782/openshift_facts", line 549, in merge_facts
    new_keys = set(new.keys()) - set(orig.keys())
AttributeError: 'str' object has no attribute 'keys'
```

my hosts file

```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# To deploy origin, change deployment_type to origin
deployment_type=origin

# Pre-release registry URL
#openshift_registry_url=docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-${component}:${version}

# Pre-release additional repo
#openshift_additional_repos=[{'id': 'ose-devel', 'name': 'ose-devel', 'baseurl': 'http://buildvm-devops.usersys.redhat.com/puddle/build/OpenShiftEnterprise/3.0/latest/RH7-RHOSE-3.0/$basearch/os', 'enabled': 1, 'gpgcheck': 0}]
#openshift_additional_repos=[{'id': 'ose-devel', 'name': 'ose-devel', 'baseurl': 'http://buildvm-devops.usersys.redhat.com/puddle/build/OpenShiftEnterpriseErrata/3.0/latest/RH7-RHOSE-3.0/$basearch/os', 'enabled': 1, 'gpgcheck': 0}]

# Origin copr repo
#openshift_additional_repos=[{'id': 'openshift-origin-copr', 'name': 'OpenShift Origin COPR', 'baseurl': 'https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/epel-7-$basearch/', 'enabled': 1, 'gpgcheck': 1, gpgkey: 'https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/pubkey.gpg'}]

# host group for masters
[masters]
master1.tsi-af.de

# host group for nodes, includes region info
[nodes]
master1.tsi-af.de 
```

I've tried with ansible 1.8.4 as well as 1.9.2. So any clues?
Thanx
Markus

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. We have many many changes to the area of code you were having issues with in your original post.

Please update and reopen this issue if this is still a priority you would like to see action on.
