### ISSUE TITLE
Installer fails 

### ISSUE THREAD

**Issue by marcusramberg** [openshift/openshift-ansible#324]
Tried installing openshift origin from the master branch, got this error:

```
TASK: [set_fact ] ************************************************************* 
fatal: [w3utv-mr01.uio.no] => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible-1.9-py2.6.egg/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.6/site-packages/ansible-1.9-py2.6.egg/ansible/runner/__init__.py", line 792, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.6/site-packages/ansible-1.9-py2.6.egg/ansible/runner/__init__.py", line 1006, in _executor_internal_inner
    complex_args = template.template(self.basedir, complex_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/lib/python2.6/site-packages/ansible-1.9-py2.6.egg/ansible/utils/template.py", line 133, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/lib/python2.6/site-packages/ansible-1.9-py2.6.egg/ansible/utils/template.py", line 119, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/lib/python2.6/site-packages/ansible-1.9-py2.6.egg/ansible/utils/template.py", line 365, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 13, in root
  File "/home/marcusr/Source/openshift-ansible/filter_plugins/oo_filters.py", line 80, in oo_collect
    retval = [FilterModule.get_attr(d, attribute) for d in data]
  File "/home/marcusr/Source/openshift-ansible/filter_plugins/oo_filters.py", line 38, in get_attr
    ptr = ptr[attr]
KeyError: 'openshift_hostname'


FATAL: all hosts have already failed -- aborting
```

**Comment by aveshagarwal** [comment]
I am seeing the same issue.

**Comment by rjleaf** [comment]
Looks like it might be related to this PR: https://github.com/openshift/openshift-ansible/pull/319

**Comment by andrew-jones** [comment]
Your using ansible 1.9.*?  Downgrading to 1.8.4 fixed this for me.

**Comment by marcusramberg** [comment]
I tried downgrading without luck. Seems that #319 fixes this issue for me. Pulled it into my checkout, and now the playbook works. Thanks @rjleaf

**Comment by rjleaf** [comment]
@marcusramberg Did you pull it into the master branch or into the 3.x branch - I'm still having issues getting this to work.

**Comment by detiber** [comment]
@rleaf Ping me in IRC, both the latest 3.x branch and master branches
should both work with #319

On Tue, Jul 7, 2015 at 10:49 AM, Ryan Leaf <notifications@github.com> wrote:

> @marcusramberg <https://github.com/marcusramberg> Did you pull it into
> the master branch or into the 3.x branch - I'm still having issues getting
> this to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/openshift-ansible/issues/324#issuecomment-119226684>
> .
>



-- 
Jason DeTiberus

**Comment by marcusramberg** [comment]
@rjleaf I pulled it into master.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
