### ISSUE TITLE
Errors while running on CentOS7

### ISSUE THREAD

**Issue by LalatenduMohanty** [openshift/openshift-ansible#344]
I am seeing some odd errors when I am trying this (see below). I am using CentOS7.1 for this. I hope the ansible playbook supports CentOS7.

I am referencing to the documentation at :  https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide

```
[root@localhost ~]# ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 157, in main
    inventory = ansible.inventory.Inventory(options.inventory, vault_password=vault_pass)
  File "/usr/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 128, in __init__
    self.parser = InventoryParser(filename=host_list)
  File "/usr/lib/python2.7/site-packages/ansible/inventory/ini.py", line 43, in __init__
    self._parse()
  File "/usr/lib/python2.7/site-packages/ansible/inventory/ini.py", line 47, in _parse
    self._parse_base_groups()
  File "/usr/lib/python2.7/site-packages/ansible/inventory/ini.py", line 108, in _parse_base_groups
    tokens = shlex.split(line)
  File "/usr/lib64/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib64/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib64/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib64/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation" 
```

**Comment by detiber** [comment]
@LalatenduMohanty What does your inventory file look like (/etc/ansible/hosts is the default when not specified)? The error points to there being a missing quote in the inventory file.

**Comment by LalatenduMohanty** [comment]
Yeah, there was a copy paste error in /etc/ansible/hosts.  Now it moved ahead of this the reported error.
