### ISSUE TITLE
Cannot partition NFS disk with too many forward slashes

### ISSUE THREAD

**Issue by johnjelinek** [openshift/openshift-ansible#349]
```
TASK: [kube_nfs_volumes | partition the drives] *******************************
<104.233.75.198> ESTABLISH CONNECTION FOR USER: root
<104.233.75.198> REMOTE_MODULE partitionpool disks=/dev/mapper/centos-root force=False sizes=5G:10
<104.233.75.198> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/jjelinek/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 104.233.75.198 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436933368.46-258033611304349 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1436933368.46-258033611304349 && echo $HOME/.ansible/tmp/ansible-tmp-1436933368.46-258033611304349'
<104.233.75.198> PUT /var/folders/rh/wxb4f7d50151_tzpn2z_whdh0000gp/T/tmpi8a0Hv TO /root/.ansible/tmp/ansible-tmp-1436933368.46-258033611304349/partitionpool
<104.233.75.198> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/jjelinek/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 104.233.75.198 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1436933368.46-258033611304349/partitionpool; rm -rf /root/.ansible/tmp/ansible-tmp-1436933368.46-258033611304349/ >/dev/null 2>&1'
failed: [104.233.75.198] => {"failed": true, "parsed": false}
skipping /dev/mapper/centos-root
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1436933368.46-258033611304349/partitionpool", line 1844, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1436933368.46-258033611304349/partitionpool", line 231, in main
    partitions += get_partitions(disk)
  File "/root/.ansible/tmp/ansible-tmp-1436933368.46-258033611304349/partitionpool", line 193, in get_partitions
    (_, _, pname) = part.path.rsplit("/")
ValueError: too many values to unpack
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 102: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 58238
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0
Shared connection to 104.233.75.198 closed.


FATAL: all hosts have already failed -- aborting
```

**Comment by detiber** [comment]
> <104.233.75.198> REMOTE_MODULE partitionpool disks=/dev/mapper/centos-root force=False sizes=5G:10

@johnjelinek The partitionpool module expects a comma separated list of disk devices (such as '/dev/sda,/dev/xvdb').

It probably wouldn't be a bad idea to validate that the value(s) passed in are raw disk devices though.

**Comment by johnjelinek** [comment]
It would be nice to add some steps to reduce my logical volume, create a new logical partition, format and make it NFS.



—

**Comment by detiber** [comment]
@johnjelinek I agree it would be nice, I'm not sure we want to try to go down that road yet though.

I think the risk (potentially destroying the user's system) vs. the reward is too high at this point. The other thing to note is that the default filesystem for RHEL (xfs) does not support shrinking existing filesystems.

**Comment by johnjelinek** [comment]
Another option, for single-tenant systems (like my environment) could be to
skip creating partitions altogether and instead create a lot of folders in
something like /home/data and add those to /etc/exports and maybe auto
create the pvs.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
