### ISSUE TITLE
Not able to install "vagrant-hostmanager" plugin  on F22 libvirt Vagrant setup

### ISSUE THREAD

**Issue by LalatenduMohanty** [openshift/openshift-ansible#373]
I am getting below error when I am trying to install  "vagrant-hostmanager" according to https://github.com/openshift/openshift-ansible/blob/master/README_vagrant.md

I have a working Vagrant libvirt setup on Fedora22. 

``` r
]# vagrant --version
Vagrant 1.7.2

]# vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing unf_ext (0.0.7.1), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.1'` succeeds before bundling.

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20150720-27252-11ll7wt.rb extconf.rb 
checking for main() in -lstdc++... no
creating Makefile

make "DESTDIR=" clean
rm -f 
rm -f unf_ext.so  *.o  *.bak mkmf.log .*.time

make "DESTDIR="
g++ -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.   -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -m64 -o unf.o -c unf.cc
make: g++: Command not found
Makefile:206: recipe for target 'unf.o' failed
make: *** [unf.o] Error 127

make failed, exit code 2

Gem files will remain installed in /root/.vagrant.d/gems/gems/unf_ext-0.0.7.1 for inspection.
Results logged to /root/.vagrant.d/gems/extensions/x86_64-linux/unf_ext-0.0.7.1/gem_make.out

```

To reproduce the issue follow the below steps on F22:
- dnf install -y vagrant-libvirt vagrant
- dnf install -y ansible rubygem-thor rubygem-parseconfig util-linux
- vagrant plugin install vagrant-hostmanager

**Comment by detiber** [comment]
@LalatenduMohanty The error indicates that you do not have gcc-c++ installed.  You could either do a dnf install rubygem-unf to install the dependency or a dnf install gcc-c++ to be able to get past the error compiling the unf_ext gem.

**Comment by LalatenduMohanty** [comment]
@detiber thanks. Installing  gcc-c++  solved the similar issue on CentOS7. But on Fedora 22 I am still seeing below error after doing " dnf install gcc-c++ ;dnf install rubygem-unf"


```{r}
[root@dhcp35-203 vagrant-workspace]# dnf install gcc-c++
Last metadata expiration check performed 0:55:35 ago on Mon Jul 20 20:48:41 2015.
Package gcc-c++-5.1.1-4.fc22.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

[root@dhcp35-203 vagrant-workspace]# dnf install rubygem-unf
Last metadata expiration check performed 0:55:41 ago on Mon Jul 20 20:48:41 2015.
Package rubygem-unf-0.1.4-5.fc22.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

[root@dhcp35-203 vagrant-workspace]# vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ruby-libvirt (0.5.2), and Bundler cannot continue.
Make sure that `gem install ruby-libvirt -v '0.5.2'` succeeds before bundling.

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20150720-31132-wjqzc2.rb extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib64
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)
        --with-libvirt-include
        --without-libvirt-include
        --with-libvirt-lib
        --without-libvirt-lib
        --with-libvirt-config
        --without-libvirt-config
        --with-pkg-config
        --without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /root/.vagrant.d/gems/gems/ruby-libvirt-0.5.2 for inspection.
Results logged to /root/.vagrant.d/gems/extensions/x86_64-linux/ruby-libvirt-0.5.2/gem_make.out

```

**Comment by LalatenduMohanty** [comment]
So I have installed ruby-libvirt through dnf, but I still see the issue

```{r}
[root@dhcp35-203 ~]# dnf install ruby-libvirt
Last metadata expiration check performed 0:58:45 ago on Mon Jul 20 20:48:41 2015.
Dependencies resolved.
======================================================================================================================================================
 Package                               Arch                            Version                                  Repository                       Size
======================================================================================================================================================
Installing:
 ruby-libvirt                          x86_64                          0.5.2-6.fc22                             fedora                           88 k

Transaction Summary
======================================================================================================================================================
Install  1 Package

Total download size: 88 k
Installed size: 256 k
Is this ok [y/N]: y
Downloading Packages:
ruby-libvirt-0.5.2-6.fc22.x86_64.rpm                                                                                  1.2 MB/s |  88 kB     00:00    
------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                  45 kB/s |  88 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : ruby-libvirt-0.5.2-6.fc22.x86_64                                                                                                  1/1 
  Verifying   : ruby-libvirt-0.5.2-6.fc22.x86_64                                                                                                  1/1 

Installed:
  ruby-libvirt.x86_64 0.5.2-6.fc22                                                                                                                    

Complete!


[root@dhcp35-203 ~]# vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ruby-libvirt (0.5.2), and Bundler cannot continue.
Make sure that `gem install ruby-libvirt -v '0.5.2'` succeeds before bundling.

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20150720-31325-1rfpe0q.rb extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--with-libvirt-include
	--without-libvirt-include
	--with-libvirt-lib
	--without-libvirt-lib
	--with-libvirt-config
	--without-libvirt-config
	--with-pkg-config
	--without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /root/.vagrant.d/gems/gems/ruby-libvirt-0.5.2 for inspection.
Results logged to /root/.vagrant.d/gems/extensions/x86_64-linux/ruby-libvirt-0.5.2/gem_make.out

```

**Comment by voxik** [comment]
You need probably rubygem-ruby-libvirt instead of ruby-libvirt, although I am not sure if the system one will be picked on F22, since bundler tends to install the more recent one from RubyGems.

**Comment by detiber** [comment]
@voxik nice catch, I think that is indeed the issue.

**Comment by voxik** [comment]
anyway, I believe that something like libvirt-devel will allow to build the RubyGems version. Probably good to look into .spec file [1] what is needed to get it build.

[1] http://pkgs.fedoraproject.org/cgit/rubygem-ruby-libvirt.git/tree/rubygem-ruby-libvirt.spec#n16

**Comment by LalatenduMohanty** [comment]
Just for confirmation "rubygem-ruby-libvirt " does not solve the issue.

```{r}
[root@dhcp35-203 ~]# dnf install rubygem-ruby-libvirt
Last metadata expiration check performed 2:27:02 ago on Mon Jul 20 20:48:41 2015.
Package rubygem-ruby-libvirt-0.4.0-9.fc22.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

[root@dhcp35-203 ~]# vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ruby-libvirt (0.5.2), and Bundler cannot continue.
Make sure that `gem install ruby-libvirt -v '0.5.2'` succeeds before bundling.

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20150720-412-13om43k.rb extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--with-libvirt-include
	--without-libvirt-include
	--with-libvirt-lib
	--without-libvirt-lib
	--with-libvirt-config
	--without-libvirt-config
	--with-pkg-config
	--without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /root/.vagrant.d/gems/gems/ruby-libvirt-0.5.2 for inspection.
Results logged to /root/.vagrant.d/gems/extensions/x86_64-linux/ruby-libvirt-0.5.2/gem_make.out

```

**Comment by detiber** [comment]
@LalatenduMohanty it looks like the packaged version of rubygem-ruby-libvirt you have installed is too old.

**Comment by LalatenduMohanty** [comment]
@detiber Thats the latest available in Fedora 22. http://koji.fedoraproject.org/koji/buildinfo?buildID=604321

Looks like we have hit an impasse

**Comment by strzibny** [comment]
@LalatenduMohanty This issue and the one for CentOS happens because of the way how Vagrant handles upstream plugins....e.g. instead of reusing our packaged stuff that works it tries to download and install all dependent gems again.

If you install new gems you face compile issues because some of them have C extensions. If you use Vagrant with vagrant-libvirt that always happen.

This behaviour should change in future versions of Vagrant according to upstream. I even proposed a patch that fixes this behaviour, but upstream did not accept nor reject it yet.

Solutions for Fedora: either include my patch (noone still tried that except me so I don't have any feedback) or package vagrant-hostmanager. Note that package submission and acceptance takes some time.

**Comment by anna-liao** [comment]
I had the same error when trying to install the vagrant host-manager plugin on 32-bit Fedora 21 and installing the latest vagrant 1.8.1 (.rpm) fixes it.
https://www.vagrantup.com/downloads.html

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.
