### ISSUE TITLE
Vagrant file does not work on CentOS7 Vagrant libvirt setup

### ISSUE THREAD

**Issue by LalatenduMohanty** [openshift/openshift-ansible#375]
Refer: https://github.com/openshift/openshift-ansible/blob/master/README_vagrant.md for this.

For setting up Vagrant on CentOS refer https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/quickstart.rst#centos

``` r
[root@n32 openshift-ansible]# vagrant up --provider=libvirt --no-provision
/root/.vagrant.d/gems/gems/i18n-0.7.0/lib/i18n/config.rb:19:in `backend': cannot load such file -- i18n/backend (LoadError)
        from /root/.vagrant.d/gems/gems/i18n-0.7.0/lib/i18n.rb:147:in `translate'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/errors.rb:103:in `translate_error'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/errors.rb:72:in `initialize'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant.rb:276:in `exception'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant.rb:276:in `raise'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant.rb:276:in `rescue in <top (required)>'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant.rb:272:in `<top (required)>'
        from /opt/rh/vagrant1/root/usr/share/vagrant/bin/vagrant:105:in `require'
        from /opt/rh/vagrant1/root/usr/share/vagrant/bin/vagrant:105:in `<main>'

```

Required Vagrant plugins are installed

``` r
[root@n32 openshift-ansible]# vagrant plugin list
vagrant-hostmanager (1.5.0)
vagrant-libvirt (0.0.26, system)
```

```
[root@n32 openshift-ansible]# cat /etc/centos-release
CentOS Linux release 7.1.1503 (Core) 
```

**Comment by detiber** [comment]
@LalatenduMohanty you can try uninstalling the i18n gem and installing rubygem-i18n to see if it resolves the issue.

**Comment by LalatenduMohanty** [comment]
@detiber I have below i18n RPM package installed. 
```
[root@n32 openshift-ansible]# rpm -qa | grep i18n
ror40-rubygem-i18n-0.6.4-3.el7.centos.noarch
```
Looks like ror40-rubygem-i18n-0.6.4-3.el7.centos.noarch is only available for CentOS7
```{r}
[root@n32 openshift-ansible]# yum search rubygem-i18n
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.ci.centos.org
 * epel: archive.linux.duke.edu
 * extras: mirror.ci.centos.org
 * updates: mirror.ci.centos.org
============================================================= N/S matched: rubygem-i18n ==============================================================
ror40-rubygem-i18n-doc.noarch : Documentation for rubygem-i18n
ror40-rubygem-i18n.noarch : New wave Internationalization support for Ruby

  Name and summary matches only, use "search all" for everything.
```

**Comment by LalatenduMohanty** [comment]
I tried the setup again on a fresh CentOS7 and got this new issue. It is different then the last one.

To reproduce the issue , refer https://github.com/LalatenduMohanty/atomicapp-vagrantbox-with-openshift-provider/blob/master/vagrant-libvirt-centos7.md

```{r}
root@n53 centos]# vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostmanager (1.5.0)'!

[root@n53 centos]# vagrant up
/root/.vagrant.d/gems/gems/fog-core-1.32.0/lib/fog/core/services_mixin.rb:12:in `new': libvirt is not a recognized provider (ArgumentError)
        from /root/.vagrant.d/gems/gems/fog-core-1.32.0/lib/fog/compute.rb:62:in `new'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.26/lib/vagrant-libvirt/action/connect_libvirt.rb:38:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:214:in `action_raw'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:191:in `block in action'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:516:in `lock'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:178:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:178:in `action'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.26/lib/vagrant-libvirt/provider.rb:70:in `state'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:480:in `state'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:141:in `initialize'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/vagrantfile.rb:75:in `new'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/vagrantfile.rb:75:in `machine'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:614:in `machine'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:192:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:174:in `each'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
        from /opt/rh/vagrant1/root/usr/share/vagrant/plugins/commands/up/command.rb:74:in `block in execute'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:277:in `block (2 levels) in batch'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:275:in `tap'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:275:in `block in batch'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:274:in `synchronize'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:274:in `batch'
        from /opt/rh/vagrant1/root/usr/share/vagrant/plugins/commands/up/command.rb:58:in `execute'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/cli.rb:42:in `execute'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:301:in `cli'
        from /opt/rh/vagrant1/root/usr/share/vagrant/bin/vagrant:174:in `<main>'
```

**Comment by detiber** [comment]
@LalatenduMohanty it looks like at some point fog dropped the libvirt provider.

See: https://github.com/fog/fog/tree/v1.22.1/lib/fog
vs: https://github.com/fog/fog/tree/master/lib/fog

**Comment by detiber** [comment]
jdetiber@localhost:~/git/github/openshift/v3/keynote2015/ansible git:(master)➤ gem list fog

*** LOCAL GEMS ***

fog (1.22.1)
fog-brightbox (0.1.1)
fog-core (1.22.0)
fog-json (1.0.0)

**Comment by detiber** [comment]
A quick google search brings up this project which appears to be a separate fog plugin to provide libvirt support: https://github.com/fog/fog-libvirt

**Comment by LalatenduMohanty** [comment]
@detiber I have tried to install fog-libvirt. (I also have ruby200-ruby-devel-2.0.0.353-23.el7.centos.x86_64 installed in the machine). But from the error it seems like it is looking for some header files.

```{r}
[root@n56 c7]# sudo gem install fog-libvirt
Fetching: builder-3.2.2.gem (100%)
Successfully installed builder-3.2.2
Fetching: excon-0.45.4.gem (100%)
Successfully installed excon-0.45.4
Fetching: formatador-0.2.5.gem (100%)
Successfully installed formatador-0.2.5
Fetching: mime-types-2.6.1.gem (100%)
Successfully installed mime-types-2.6.1
Fetching: net-ssh-2.9.2.gem (100%)
Successfully installed net-ssh-2.9.2
Fetching: net-scp-1.2.1.gem (100%)
Successfully installed net-scp-1.2.1
Fetching: fog-core-1.32.0.gem (100%)
Successfully installed fog-core-1.32.0
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: fog-json-1.0.2.gem (100%)
Successfully installed fog-json-1.0.2
Fetching: mini_portile-0.6.2.gem (100%)
Successfully installed mini_portile-0.6.2
Fetching: nokogiri-1.6.6.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing fog-libvirt:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h


Gem files will remain installed in /usr/local/share/gems/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /usr/local/share/gems/gems/nokogiri-1.6.6.2/ext/nokogiri/gem_make.out
```

**Comment by voxik** [comment]
@LalatenduMohanty I doubt that you are running in SCL environment. You are probably using system ruby and you don't have installed system ruby-devel package. Something like ```scl enable ruby200 bash``` should help probably.

**Comment by LalatenduMohanty** [comment]
@voxik I thought, I am using SCL ruby as "which ruby" pointed to /opt/rh/ruby200.  i am still a newbie in SCL

```
ruby: No such file or directory -- extconf.rb (LoadError)
[root@n56 c7]# which ruby
/opt/rh/ruby200/root/usr/bin/ruby
```
I did "scl enable ruby200 bash", still it did not help.

```{r}
[root@n56 c7]# scl enable ruby200 bash
[root@n56 c7]# sudo gem install fog-libvirt
Building native extensions.  This could take a while...
ERROR:  Error installing fog-libvirt:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h


Gem files will remain installed in /usr/local/share/gems/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /usr/local/share/gems/gems/nokogiri-1.6.6.2/ext/nokogiri/gem_make.out
```

**Comment by voxik** [comment]
This is what is weird:

```
    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h
```

So apparently, system ruby is called at some point. Have you tried to install the gems as a regular user? Does it make any difference?

**Comment by voxik** [comment]
Trying to reproduce your issue, this is the error I get:

```
# gem install nokogiri
Fetching: mini_portile-0.6.2.gem (100%)
Successfully installed mini_portile-0.6.2
Fetching: nokogiri-1.6.6.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    /opt/rh/ruby200/root/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /opt/rh/ruby200/root/usr/share/include/ruby.h


Gem files will remain installed in /opt/rh/ruby200/root/usr/local/share/gems/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /opt/rh/ruby200/root/usr/local/share/gems/gems/nokogiri-1.6.6.2/ext/nokogiri/gem_make.out
```

Please notice the difference in paths. This command will execute the ```gem install fog-libvir``` in the SCL context:

```
echo "gem install fog-libvirt" | scl enable ruby200 -
```

**Comment by LalatenduMohanty** [comment]
@voxik I get similar error when I remove the sudo while running the command. (not sure why I had sudo at first place when I was root anyway)

```
[root@n56 c7]# gem install fog-libvirt

Building native extensions.  This could take a while...
ERROR:  Error installing fog-libvirt:
        ERROR: Failed to build gem native extension.

    /opt/rh/ruby200/root/usr/bin/ruby extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib64
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/rh/ruby200/root/usr/bin/ruby
        --with-libvirt-include
        --without-libvirt-include
        --with-libvirt-lib
        --without-libvirt-lib
        --with-libvirt-config
        --without-libvirt-config
        --with-pkg-config
        --without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)


Gem files will remain installed in /opt/rh/ruby200/root/usr/local/share/gems/gems/ruby-libvirt-0.5.2 for inspection.
Results logged to /opt/rh/ruby200/root/usr/local/share/gems/gems/ruby-libvirt-0.5.2/ext/libvirt/gem_make.out
```

**Comment by LalatenduMohanty** [comment]
I installed "make automake kernel-devel libvirt-devel" then fog-libvirt installation worked fine. I will reproduce 

```
[root@n56 c7]# yum install make automake kernel-devel libvirt-devel

[root@n56 c7]# gem install fog-libvirt
Building native extensions.  This could take a while...
rSuccessfully installed ruby-libvirt-0.5.2
Fetching: fog-libvirt-0.0.2.gem (100%)
Successfully installed fog-libvirt-0.0.2
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Parsing documentation for ruby-libvirt-0.5.2
Installing ri documentation for ruby-libvirt-0.5.2
Parsing documentation for fog-libvirt-0.0.2
Installing ri documentation for fog-libvirt-0.0.2
Parsing documentation for multi_json-1.11.2
Installing ri documentation for multi_json-1.11.2
3 gems installed
```
But still the error abt the "libvirt is not a recognized provider (ArgumentError)" comes. :(

```{r}
[root@n56 openshift-ansible]# vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostmanager (1.5.0)'!


[root@n56 openshift-ansible]# vagrant up --provider=libvirt --no-provision

/opt/rh/ruby200/root/usr/local/share/gems/gems/fog-core-1.32.0/lib/fog/core/services_mixin.rb:12:in `new': libvirt is not a recognized provider (ArgumentError)
        from /opt/rh/ruby200/root/usr/local/share/gems/gems/fog-core-1.32.0/lib/fog/compute.rb:62:in `new'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.26/lib/vagrant-libvirt/action/connect_libvirt.rb:38:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:214:in `action_raw'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:191:in `block in action'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:516:in `lock'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:178:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:178:in `action'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.26/lib/vagrant-libvirt/provider.rb:70:in `state'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:480:in `state'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/machine.rb:141:in `initialize'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/vagrantfile.rb:75:in `new'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/vagrantfile.rb:75:in `machine'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:614:in `machine'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:192:in `call'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:174:in `each'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
        from /opt/rh/vagrant1/root/usr/share/vagrant/plugins/commands/up/command.rb:74:in `block in execute'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:277:in `block (2 levels) in batch'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:275:in `tap'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:275:in `block in batch'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:274:in `synchronize'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:274:in `batch'
        from /opt/rh/vagrant1/root/usr/share/vagrant/plugins/commands/up/command.rb:58:in `execute'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/cli.rb:42:in `execute'
        from /opt/rh/vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:301:in `cli'
        from /opt/rh/vagrant1/root/usr/share/vagrant/bin/vagrant:174:in `<main>'
```
```

**Comment by voxik** [comment]
And do you have installed vagrant-libvirt?

**Comment by LalatenduMohanty** [comment]
Through SCL, yes
```
[root@n56 openshift-ansible]# rpm -qa | grep vagrant-libvirt
vagrant1-vagrant-libvirt-0.0.24-1.el7.centos.noarch
```

**Comment by voxik** [comment]
Is the plugin listed among vagrant plugins?

```
# vagrant plugin list
vagrant-libvirt (0.0.30, system)
```

**Comment by LalatenduMohanty** [comment]
@voxik yes 
```
[root@n56 openshift-ansible]# vagrant plugin list
vagrant-hostmanager (1.5.0)
vagrant-libvirt (0.0.26, system)
```

**Comment by strzibny** [comment]
I was the one who proposed and implemented the fog and fog-libvirt separation change. Unfortunately if you install upstream plugins, all Vagrant gems get updated. The right versions in these scenarios is tricky to ensure. I already proposed patch upstream that would solve the issue. In the meantime the safest way is to build the plugin as another scl gem instead of upstream installation.

**Comment by LalatenduMohanty** [comment]
@strzibny you mean vagrant-libvirt as a gem plugin?  lets catch up on irc . you can find me on #centos-devel or #nulecule as lalatenduM.

**Comment by LalatenduMohanty** [comment]
@strzibny regarding the patch you have already in the upstream, can we rebuild Fedora COPR repo with the patch, so I can move ahead without waiting for CentOS SCLo SIG?

**Comment by strzibny** [comment]
This is the patch: https://github.com/mitchellh/vagrant/pull/5877. You can try to do a build for yourself with the patch included, help me to test the patch and then we can include it in COPR.

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.
