### ISSUE TITLE
Failure in Origin-gce

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#3978]
```
TASK [openshift_master : Create session secrets file] **************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_master/tasks/main.yml:138
Saturday 22 April 2017  02:45:53 +0000 (0:00:00.230)       0:10:40.963 ******** 
<130.211.121.205> ESTABLISH SSH CONNECTION FOR USER: cloud-user
<130.211.121.205> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=900s -o GSSAPIAuthentication=no -o StrictHostKeyChecking=no -o 'IdentityFile="/home/cloud-user/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=30 -o ControlPath=/var/tmp/%h-%r 130.211.121.205 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1492829153.15-146723034898404 `" && echo ansible-tmp-1492829153.15-146723034898404="` echo ~/.ansible/tmp/ansible-tmp-1492829153.15-146723034898404 `" ) && sleep 0'"'"''
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/files/stat.py
<130.211.121.205> ESTABLISH SSH CONNECTION FOR USER: cloud-user
<130.211.121.205> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=900s -o GSSAPIAuthentication=no -o StrictHostKeyChecking=no -o 'IdentityFile="/home/cloud-user/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=30 -o ControlPath=/var/tmp/%h-%r 130.211.121.205 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-trzlttofikhrsxdsxfbtldzafbzmgjda; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<130.211.121.205> PUT /tmp/tmpxK_b3X TO /home/cloud-user/.ansible/tmp/ansible-tmp-1492829153.15-146723034898404/source
<130.211.121.205> SSH: EXEC sftp -b - -o ControlMaster=auto -o ControlPersist=900s -o GSSAPIAuthentication=no -o StrictHostKeyChecking=no -o 'IdentityFile="/home/cloud-user/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=30 -o ControlPath=/var/tmp/%h-%r '[130.211.121.205]'
<130.211.121.205> ESTABLISH SSH CONNECTION FOR USER: cloud-user
<130.211.121.205> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=900s -o GSSAPIAuthentication=no -o StrictHostKeyChecking=no -o 'IdentityFile="/home/cloud-user/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=30 -o ControlPath=/var/tmp/%h-%r 130.211.121.205 '/bin/sh -c '"'"'chmod u+x /home/cloud-user/.ansible/tmp/ansible-tmp-1492829153.15-146723034898404/ /home/cloud-user/.ansible/tmp/ansible-tmp-1492829153.15-146723034898404/source && sleep 0'"'"''
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/files/copy.py
<130.211.121.205> ESTABLISH SSH CONNECTION FOR USER: cloud-user
<130.211.121.205> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=900s -o GSSAPIAuthentication=no -o StrictHostKeyChecking=no -o 'IdentityFile="/home/cloud-user/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=30 -o ControlPath=/var/tmp/%h-%r 130.211.121.205 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-fhlhlftvpexftkepipuemreuqpjnjbaf; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<130.211.121.205> ESTABLISH SSH CONNECTION FOR USER: cloud-user
<130.211.121.205> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=900s -o GSSAPIAuthentication=no -o StrictHostKeyChecking=no -o 'IdentityFile="/home/cloud-user/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=30 -o ControlPath=/var/tmp/%h-%r 130.211.121.205 '/bin/sh -c '"'"'rm -f -r /home/cloud-user/.ansible/tmp/ansible-tmp-1492829153.15-146723034898404/ > /dev/null 2>&1 && sleep 0'"'"''
changed: [ci-primg216-ig-m-jk1m] => {
    "changed": true, 
    "checksum": "8afdf8b859e60938e53dca393fbdb9384f06f9d8", 
    "dest": "/etc/origin/master/session-secrets.yaml", 
    "gid": 0, 
    "group": "root", 
    "invocation": {
        "module_args": {
            "backup": false, 
            "content": null, 
            "delimiter": null, 
            "dest": "/etc/origin/master/session-secrets.yaml", 
            "directory_mode": null, 
            "follow": true, 
            "force": true, 
            "group": "root", 
            "mode": 384, 
            "original_basename": "sessionSecretsFile.yaml.v1.j2", 
            "owner": "root", 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/home/cloud-user/.ansible/tmp/ansible-tmp-1492829153.15-146723034898404/source", 
            "unsafe_writes": null, 
            "validate": null
        }
    }, 
    "md5sum": "ad3f8562e79291887922d7674c52e753", 
    "mode": "0600", 
    "owner": "root", 
    "secontext": "system_u:object_r:etc_t:s0", 
    "size": 147, 
    "src": "/home/cloud-user/.ansible/tmp/ansible-tmp-1492829153.15-146723034898404/source", 
    "state": "file", 
    "uid": 0
}

TASK [openshift_master : set_fact] *********************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_master/tasks/main.yml:150
Saturday 22 April 2017  02:45:56 +0000 (0:00:03.470)       0:10:44.433 ******** 
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 443, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 248, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 373, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 427, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 383, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 583, in do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/usr/share/ansible/openshift-ansible/roles/openshift_master_facts/filter_plugins/openshift_master.py", line 499, in translate_idps
    Dumper=AnsibleDumper))
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 215, in represent_list
    return self.represent_sequence(u'tag:yaml.org,2002:seq', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 101, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: allow_all
fatal: [ci-primg216-ig-m-jk1m]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

Have not changed the config, not sure what is failing

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/215/console

**Comment by smarterclayton** [comment]
We have been setting:

```
openshift_master_identity_providers: [{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]
```

in the unshift release setup.

**Comment by smarterclayton** [comment]
Ansible 2.2.1

**Comment by ashcrow** [comment]
After looking further this looks an awful like https://github.com/ansible/ansible/issues/20885.

**Comment by sdodson** [comment]
> Ansible 2.2.1

rpm -q ansible ? ansible-2.2.1.0-2.el7 has patches for the problems in previous comment, we should make sure we're using the patched version

**Comment by smarterclayton** [comment]
I was able to work around this by adding a `| to_json | from_json` hack.  I'm installing the latest package available from CentOS.

**Comment by smarterclayton** [comment]
Still broken (but I was able to work around it for now in another way that I don't want to maintain)
