### ISSUE TITLE
repoquery module expects /etc/yum.conf to exist

### ISSUE THREAD

**Issue by abutcher** [openshift/openshift-ansible#4180]
`/etc/yum.conf` doesn't exist on atomic and we're running this repoquery module against all containerized. Should the when also include `not openshift.common.is_atomic`?

https://s3.amazonaws.com/aos-ci/ghprb/openshift/openshift-ansible/ec60ae7de883c5b5d621c486659257d1a10055ab.0.1494619368279990261/output.log

```
TASK [openshift_version : Get available origin version] ************************
task path: /var/tmp/checkout/roles/openshift_version/tasks/main.yml:92
Using module file /var/tmp/checkout/roles/lib_utils/library/repoquery.py
<ocp-master> ESTABLISH SSH CONNECTION FOR USER: root
<ocp-master> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r ocp-master '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_jzjmpwb8/ansible_module_repoquery.py", line 635, in <module>
    main()
  File "/tmp/ansible_jzjmpwb8/ansible_module_repoquery.py", line 626, in main
    rval = Repoquery.run_ansible(module.params, module.check_mode)
  File "/tmp/ansible_jzjmpwb8/ansible_module_repoquery.py", line 586, in run_ansible
    results = repoquery.repoquery()
  File "/tmp/ansible_jzjmpwb8/ansible_module_repoquery.py", line 534, in repoquery
    with open("/etc/yum.conf", "r") as file_handler:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/yum.conf'
fatal: [ocp-master]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "repoquery"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_jzjmpwb8/ansible_module_repoquery.py\", line 635, in <module>\n    main()\n  File \"/tmp/ansible_jzjmpwb8/ansible_module_repoquery.py\", line 626, in main\n    rval = Repoquery.run_ansible(module.params, module.check_mode)\n  File \"/tmp/ansible_jzjmpwb8/ansible_module_repoquery.py\", line 586, in run_ansible\n    results = repoquery.repoquery()\n  File \"/tmp/ansible_jzjmpwb8/ansible_module_repoquery.py\", line 534, in repoquery\n    with open(\"/etc/yum.conf\", \"r\") as file_handler:\nFileNotFoundError: [Errno 2] No such file or directory: '/etc/yum.conf'\n", 
    "module_stdout": ""
}
```

**Comment by sdodson** [comment]
@jlebon If we'd made the fedora atomic jobs blocking we would've caught this. I know we discussed making them blocking after a week of generally green test results. Do you think it's ready to block the merge queue?

**Comment by jlebon** [comment]
@sdodson, @abutcher, I'll defer to you for that decision since I don't have as good a handle on how flaky/solid they've been. That said, if we do make it blocking, I'm definitely ready to help out in ironing out any flakiness that arises, if any.

**Comment by abutcher** [comment]
Fixed in https://github.com/openshift/openshift-ansible/pull/4189
