### ISSUE TITLE
failure when running against Fedora 26 with python3 

### ISSUE THREAD

**Issue by dustymabe** [openshift/openshift-ansible#4438]
When running against Fedora 26 Atomic Host and using the python3 interpreter I get failures from the attemtps to run the seboolean module to change things. This is related to an [intentional change](https://bugzilla.redhat.com/show_bug.cgi?id=1460818) that was made in selinux. Thus the ansible module needs to be updated ([upstream issue](https://github.com/ansible/ansible/issues/25651)). We are going to have to deal with this in openshift-ansible because we know users are going to be executing from older versions of ansible against newer hosts with new libselinux-python3. 

Let's workaround this if possible.

Here is an example failure from dc12c4b

<details>

```
TASK [openshift_node : Set seboolean to allow nfs storage plugin access from containers] **************************************************************************************************************************************************************************************
task path: /guests/sharedfolder/code/github.com/openshift/openshift-ansible/roles/openshift_node/tasks/storage_plugins/nfs.yml:16
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/seboolean.py
<45.55.51.130> ESTABLISH SSH CONNECTION FOR USER: root
<45.55.51.130> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/dustymabe/.ansible/cp/8d524dc87e 45.55.51.130 '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
<45.55.51.130> (1, '\n{"msg": "SELinux boolean virt_use_nfs does not exist.", "failed": true, "invocation": {"module_args": {"persistent": true, "state": true, "name": "virt_use_nfs"}}}\n', '')
failed: [45.55.51.130] (item={'_ansible_parsed': True, 'stderr_lines': [], u'cmd': [u'getsebool', u'virt_use_nfs'], u'end': u'2017-06-12 19:36:57.778712', '_ansible_no_log': False, u'stdout': u'virt_use_nfs --> off', '_ansible_item_result': True, u'changed': False, 'item': u'virt_use_nfs', u'delta': u'0:00:00.001927', u'stderr': u'', u'rc': 0, u'invocation': {u'module_args': {u'creates': None, u'executable': None, u'chdir': None, u'_raw_params': u'getsebool virt_use_nfs', u'removes': None, u'warn': True, u'_uses_shell': False}}, 'stdout_lines': [u'virt_use_nfs --> off'], 'failed_when_result': False, u'start': u'2017-06-12 19:36:57.776785', 'failed': False}) => {
    "failed": true,
    "invocation": {
        "module_args": {
            "name": "virt_use_nfs",
            "persistent": true,
            "state": true
        }
    },
    "item": {
        "changed": false,
        "cmd": [
            "getsebool",
            "virt_use_nfs"
        ],
        "delta": "0:00:00.001927",
        "end": "2017-06-12 19:36:57.778712",
        "failed": false,
        "failed_when_result": false,
        "invocation": {
            "module_args": {
                "_raw_params": "getsebool virt_use_nfs",
                "_uses_shell": false,
                "chdir": null,
                "creates": null,
                "executable": null,
                "removes": null,
                "warn": true
            }
        },
        "item": "virt_use_nfs",
        "rc": 0,
        "start": "2017-06-12 19:36:57.776785",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "virt_use_nfs --> off",
        "stdout_lines": [
            "virt_use_nfs --> off"
        ]
    }
}

MSG:

SELinux boolean virt_use_nfs does not exist.
```

**Comment by dustymabe** [comment]
@abutcher FYI

**Comment by sdodson** [comment]
https://github.com/ansible/ansible/issues/25651 is the upstream issue

**Comment by dustymabe** [comment]
> ansible/ansible#25651 is the upstream issue

copy/paste error, thanks!

**Comment by inlandsee** [comment]
F26 origin byo  fails 'Set seboolean to allow nfs storage plugin access from containers' even when Michael Scherer's [python-libselinux workaround] (https://github.com/mscherer/ansible/commit/976ae45748d581eaab5494f49af9805fe63cce46
) is applied.  Fedora requires python 3 so switching to 2 isn't an option.
```
TASK [openshift_node : Set seboolean to allow nfs storage plugin access from containers] ***************************************************************************************************************************************************************************************
task path: /home/workspace/vendor/openshift-ansible/roles/openshift_node/tasks/storage_plugins/nfs.yml:16
Using module file /usr/lib/python2.7/site-packages/ansible-2.3.1.0-py2.7.egg/ansible/modules/system/seboolean.py
<master.local> ESTABLISH LOCAL CONNECTION FOR USER: dev
<master.local> EXEC /bin/sh -c 'echo ~ && sleep 0'
<master.local> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1497966743.44-136542178275459 `" && echo ansible-tmp-1497966743.44-136542178275459="` echo /root/.ansible/tmp/ansible-tmp-1497966743.44-136542178275459 `" ) && sleep 0'
<master.local> PUT /tmp/tmporuxUc TO /root/.ansible/tmp/ansible-tmp-1497966743.44-136542178275459/seboolean.py
<master.local> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1497966743.44-136542178275459/ /root/.ansible/tmp/ansible-tmp-1497966743.44-136542178275459/seboolean.py && sleep 0'
<master.local> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1497966743.44-136542178275459/seboolean.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1497966743.44-136542178275459/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_30d800zb/ansible_module_seboolean.py", line 234, in <module>
    main()
  File "/tmp/ansible_30d800zb/ansible_module_seboolean.py", line 203, in main
    if not has_boolean_value(module, name):
  File "/tmp/ansible_30d800zb/ansible_module_seboolean.py", line 85, in has_boolean_value
    if isinstance(bools[1], b''):
TypeError: isinstance() arg 2 must be a type or tuple of types

failed: [master.local] (item={'_ansible_parsed': True, 'stderr_lines': [], u'cmd': [u'getsebool', u'virt_use_nfs'], u'end': u'2017-06-20 09:52:22.954262', '_ansible_no_log': False, u'stdout': u'virt_use_nfs --> on', '_ansible_item_result': True, u'changed': False, 'item': u'virt_use_nfs', u'delta': u'0:00:00.002008', u'stderr': u'', u'rc': 0, u'invocation': {u'module_args': {u'creates': None, u'executable': None, u'chdir': None, u'_raw_params': u'getsebool virt_use_nfs', u'removes': None, u'warn': True, u'_uses_shell': False}}, 'stdout_lines': [u'virt_use_nfs --> on'], 'failed_when_result': False, u'start': u'2017-06-20 09:52:22.952254', 'failed': False}) => {
    "failed": true, 
    "item": {
        "changed": false, 
        "cmd": [
            "getsebool", 
            "virt_use_nfs"
        ], 
        "delta": "0:00:00.002008", 
        "end": "2017-06-20 09:52:22.954262", 
        "failed": false, 
        "failed_when_result": false, 
        "invocation": {
            "module_args": {
                "_raw_params": "getsebool virt_use_nfs", 
                "_uses_shell": false, 
                "chdir": null, 
                "creates": null, 
                "executable": null, 
                "removes": null, 
                "warn": true
            }
        }, 
        "item": "virt_use_nfs", 
        "rc": 0, 
        "start": "2017-06-20 09:52:22.952254", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "virt_use_nfs --> on", 
        "stdout_lines": [
            "virt_use_nfs --> on"
        ]
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_30d800zb/ansible_module_seboolean.py\", line 234, in <module>\n    main()\n  File \"/tmp/ansible_30d800zb/ansible_module_seboolean.py\", line 203, in main\n    if not has_boolean_value(module, name):\n  File \"/tmp/ansible_30d800zb/ansible_module_seboolean.py\", line 85, in has_boolean_value\n    if isinstance(bools[1], b''):\nTypeError: isinstance() arg 2 must be a type or tuple of types\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

```

**Comment by mscherer** [comment]
Indeed, that code is bad, I blindly followed the CI suggestion (one more reason to not listen to computer). I am gonna fix it

**Comment by mscherer** [comment]
Ok so I think now the code would make sense, I do not have much to test right now, so I would appreciate a new test

**Comment by inlandsee** [comment]
(https://github.com/mscherer/ansible/commit/47e241c9499b363205ffd9e4b8266f6c1220b391) works for me.  tx
