### ISSUE TITLE
openshift v3.5 install metrics_cassandra fail

### ISSUE THREAD

**Issue by lixwlixw** [openshift/openshift-ansible#4539]
>ansible-playbook openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.yml -e openshift_metrics_install_metrics=True    -e openshift_metrics_hawkular_hostname=hawkular-metrics.example.com

oc logs -f hawkular-cassandra-1-vk4s7
```
INFO  [main] 2017-06-22 08:58:17,428 StorageService.java:566 - Token metadata: 
INFO  [main] 2017-06-22 08:58:17,520 StorageService.java:577 - Cassandra version: 3.0.12
INFO  [main] 2017-06-22 08:58:17,521 StorageService.java:578 - Thrift API version: 20.1.0
INFO  [main] 2017-06-22 08:58:17,521 StorageService.java:579 - CQL supported versions: 3.4.0 (default: 3.4.0)
INFO  [main] 2017-06-22 08:58:17,567 IndexSummaryManager.java:85 - Initializing index summary manager with a memory pool size of 45 MB and a resize interval of 60 minutes
INFO  [main] 2017-06-22 08:58:17,568 StorageService.java:598 - Loading persisted ring state
INFO  [main] 2017-06-22 08:58:17,587 StorageService.java:746 - Starting up server gossip
Unable to create ssl socket
Fatal configuration error; unable to start server.  See log for stacktrace.
ERROR [main] 2017-06-22 08:58:17,704 CassandraDaemon.java:710 - Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Unable to create ssl socket
	at org.apache.cassandra.net.MessagingService.getServerSockets(MessagingService.java:518) ~[apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	at org.apache.cassandra.net.MessagingService.listen(MessagingService.java:498) ~[apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	at org.apache.cassandra.net.MessagingService.listen(MessagingService.java:482) ~[apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:755) ~[apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:644) ~[apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:572) ~[apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:346) [apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:569) [apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:697) [apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
Caused by: java.io.IOException: Error creating the initializing the SSL Context
	at org.apache.cassandra.security.SSLFactory.createSSLContext(SSLFactory.java:183) ~[apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	at org.apache.cassandra.security.SSLFactory.getServerSocket(SSLFactory.java:61) ~[apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	at org.apache.cassandra.net.MessagingService.getServerSockets(MessagingService.java:514) ~[apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	... 8 common frames omitted
Caused by: java.io.FileNotFoundException: ${TRUSTSTORE_FILE} (Permission denied)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_131]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_131]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_131]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[na:1.8.0_131]
	at org.apache.cassandra.security.SSLFactory.createSSLContext(SSLFactory.java:150) ~[apache-cassandra-3.0.12.redhat-1.jar:3.0.12.redhat-1]
	... 10 common frames omitted
```

**Comment by aizuddin85** [comment]
Hello @lixwlixw,

Usually this caused by the wrong branch checked-out for installation.


1.As an example, we are going to install v1.5.

```
#>git clone https://github.com/openshift/openshift-ansible
#>git checkout release-1.5
```

2.In inventory file name main.yml:
```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
containerized=true
openshift_release=v1.5
openshift_image_tag=v1.5.0
openshift_hosted_metrics_deploy=true
openshift_hosted_router_selector='region=infra'
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
enable_excluders=false
openshift_hosted_metrics_deployer_version=v1.5.0

openshift_master_cluster_public_hostname=master.example.com
openshift_public_hostname=console.example.com
openshift_master_default_subdomain=cloudapps.example.com

[masters]
master

[etcd]
master

[nodes]
master openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true
```

3. And now do the installation:
```
ansible-playbook -i main.yml openshift-origin/playbooks/byo/config.yml
```

4. Or in your case:
```
ansible-playbook -i main.yml openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.yml 
```

__Note__: Step no 4 is True only when the version is not mismatched. Thus follow steps 1 to 3.

**Comment by lixwlixw** [comment]
thinks ~ 
yes, I have realized this mistake
