### ISSUE TITLE
openshift_facts module inside openshift_facts role causes runtime error on python3 host

### ISSUE THREAD

**Issue by maxamillion** [openshift/openshift-ansible#4815]
#### Description

The module `openshift_facts` inside the `openshift_facts` role causes a python runtime error in python3 mode, which is now required for a Fedora installation.

##### Version

* Ansible version per `ansible --version`

```
ansible 2.3.1.0
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

* The output of `git describe` -> `openshift-ansible-3.5.101-1`

##### Steps To Reproduce
1. `ansible-playbook playbooks/byo/config.yml -i path/to/inventory` against Fedora 26 hosts using Python3 

##### Expected Results

The playbook to not error.

##### Observed Results

```
TASK [openshift_facts : Gather Cluster facts and set is_containerized if needed] **************************************
task path: /root/openshift-ansible/roles/openshift_facts/tasks/main.yml:71
Using module file /root/openshift-ansible/roles/openshift_facts/library/openshift_facts.py
<osbs-master01.stg.phx2.fedoraproject.org> ESTABLISH SSH CONNECTION FOR USER: root
<osbs-master01.stg.phx2.fedoraproject.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/dbbd3b6aef osbs-master01.stg.phx2.fedoraproject.org '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
Using module file /root/openshift-ansible/roles/openshift_facts/library/openshift_facts.py
<osbs-node01.stg.phx2.fedoraproject.org> ESTABLISH SSH CONNECTION FOR USER: root
<osbs-node01.stg.phx2.fedoraproject.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/f265a6ea1f osbs-node01.stg.phx2.fedoraproject.org '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
Using module file /root/openshift-ansible/roles/openshift_facts/library/openshift_facts.py
<osbs-node02.stg.phx2.fedoraproject.org> ESTABLISH SSH CONNECTION FOR USER: root
<osbs-node02.stg.phx2.fedoraproject.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/a893e1f1b4 osbs-node02.stg.phx2.fedoraproject.org '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
<osbs-master01.stg.phx2.fedoraproject.org> (1, '', 'Traceback (most recent call last):\n  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 2491, in <module>\n    main()\n  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 2478, in main\n    protected_facts_to_overwrite)\n  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 2491, in <module>
    main()
  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 2478, in main
    protected_facts_to_overwrite)
  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 1899, in __init__
    for (k, v) in self.system_facts.items():
RuntimeError: dictionary changed size during iteration

fatal: [osbs-master01.stg.phx2.fedoraproject.org]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py\", line 2491, in <module>\n    main()\n  File \"/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py\", line 2478, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py\", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n",
    "module_stdout": "",
    "rc": 1
}

MSG:

MODULE FAILURE

<osbs-node01.stg.phx2.fedoraproject.org> (1, '', 'Traceback (most recent call last):\n  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 2491, in <module>\n    main()\n  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 2478, in main\n    protected_facts_to_overwrite)\n  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 2491, in <module>
    main()
  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 2478, in main
    protected_facts_to_overwrite)
  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 1899, in __init__
    for (k, v) in self.system_facts.items():
RuntimeError: dictionary changed size during iteration

fatal: [osbs-node01.stg.phx2.fedoraproject.org]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py\", line 2491, in <module>\n    main()\n  File \"/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py\", line 2478, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py\", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n",
    "module_stdout": "",
    "rc": 1
}

MSG:

MODULE FAILURE

<osbs-node02.stg.phx2.fedoraproject.org> (1, '', 'Traceback (most recent call last):\n  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 2491, in <module>\n    main()\n  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 2478, in main\n    protected_facts_to_overwrite)\n  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 2491, in <module>
    main()
  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 2478, in main
    protected_facts_to_overwrite)
  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 1899, in __init__
    for (k, v) in self.system_facts.items():
RuntimeError: dictionary changed size during iteration

fatal: [osbs-node02.stg.phx2.fedoraproject.org]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py\", line 2491, in <module>\n    main()\n  File \"/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py\", line 2478, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py\", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n",
    "module_stdout": "",
    "rc": 1
}

MSG:

MODULE FAILURE

```

##### Additional Information

```
NAME=Fedora
VERSION="26 (Twenty Six)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Twenty Six)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=26
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=26
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
```

**Comment by maxamillion** [comment]
This appears to be fixed upstream, just not backported to the `openshift-ansible-3.5.101-1` tag. I don't see a branch or anything to submit a pull request against either so I'm not sure how to offer a fix.

**Comment by abutcher** [comment]
Backport opened -> #4817

**Comment by maxamillion** [comment]
@abutcher thanks, I realize now the branch->tag relationship ... I'll submit a PR in the future if I find something like this. Thanks again! :+1:
