### ISSUE TITLE
Rerun cluster config overwrites logging deployment config patches

### ISSUE THREAD

**Issue by bmduffy** [openshift/openshift-ansible#4836]
#### Description

I set configuration variables to auto install the EFK aggregated logging stack. I did not use one of the three options for persistent storage, but instead configured storage post install to use local disks, which involved patching the deployment configs and config map for the elasticsearch pods.

Later, when updating proxy configuration variables the following was run with an edited version of the original inventory file; 
```
ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
```
The deployment config patch for the storage on local disks for elastic search was overwritten by rerunning the cluster config. 

Just wondering;

1. Is this expected behavior?
2. Or should the config scripts skip logging deployment if deploy configs exist?
3. Should I just ensure that I run an inventory file that doesn't specify and variables that we don't want to touch?

##### Version

```
>> ansible --version
ansible 2.2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides
```
```
>> rpm -q atomic-openshift-utils openshift-ansible
atomic-openshift-utils-3.5.91-1.git.0.28b3ddb.el7.noarch
openshift-ansible-3.5.91-1.git.0.28b3ddb.el7.noarch
```

##### Steps To Reproduce
1. Install Openshift Enterprise 3.5 with automatic logging install enabled with ephemeral storage
   - Master nodes have extra disks and elasticsearch node selectors are configured
2. Configure local disk storage patching the deployment configs to point at nodes, [guide](https://access.redhat.com/documentation/en-us/openshift_container_platform/3.5/html/installation_and_configuration/install-config-aggregate-logging)
3. Change a config variable in the original inventory NO_PROXY 
4. Re-run 
ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml

##### Expected Results
NO_PROXY configured in all `/etc/sysconfig/atomic-openshift-*` they way you expect. Logging still works and is still pointing at local disk storage that was previously configured.

##### Observed Results
The following elasticsearch deployment config patches are missing. Persistent storage not working and pods are failing and crashing.

##### Additional Information

Post install configuration;

```
>> for dc in $(oc get deploymentconfig --selector logging-infra=elasticsearch -o name); do
    oc scale $dc --replicas=0
    oc patch $dc \
       -p '{"spec":{"template":{"spec":{"containers":[{"name":"elasticsearch","securityContext":{"privileged": true}}]}}}}'
  done

>> oc patch dc/logging-es-<suffix> \
   -p '{"spec":{"template":{"spec":{"nodeSelector":{"logging-es-node":"1"}}}}}'

>> for dc in $(oc get deploymentconfig --selector logging-infra=elasticsearch -o name); do
    oc set volume $dc \
          --add --overwrite --name=elasticsearch-storage \
          --type=hostPath --path=/usr/local/es-storage
    oc rollout latest $dc
    oc scale $dc --replicas=1
  done
```

**Comment by ewolinetz** [comment]
Hostmounts should be honored and kept as a DC storage config as of `openshift-ansible-3.5.94`. Can you please retest and confirm that you no longer see this?

**Comment by bmduffy** [comment]
Hi @ewolinetz,

I reran and see the issue again. Any manual configuration done to logging is wiped out. I should point out that I have `openshift_hosted_logging_deploy=true` set in my hostfile. 

The `hostPath` is set but the necessary config patches to access that `hostPath` are overwritten. 

If I set this to `openshift_hosted_logging_deploy=false` logging is ignored. But what if I want to reconfigure for example the public URL or the source image? Should I use the  role that is activated by setting `openshift_logging_install_logging=true` instead?

I should also point out again that OSE `v3.5` installs `openshift-ansible-3.5.91-1.git.0.28b3ddb.el7.noarch`, which is a few patches behind.

Patched deployment configs fail to start.
```
>> oc get po
NAME                            READY     STATUS             RESTARTS   AGE
logging-curator-6-wbdgm         1/1       Running            1          6d
logging-es-ajxuvhnt-22-tlxww    0/1       CrashLoopBackOff   193        16h
logging-es-dee5e7z8-18-p1vtb    0/1       CrashLoopBackOff   192        16h
logging-es-dee5e7z8-19-deploy   0/1       Error              0          16h
logging-es-yxjy13ym-23-clvj3    0/1       CrashLoopBackOff   193        16h
logging-fluentd-19jz5           1/1       Running            0          16h
logging-fluentd-246vt           1/1       Running            0          16h
logging-fluentd-5m6mx           1/1       Running            0          16h
logging-fluentd-9657v           1/1       Running            0          16h
logging-fluentd-j6jmb           1/1       Running            0          16h
logging-fluentd-n5p6g           1/1       Running            0          16h
logging-fluentd-p1wb7           1/1       Running            0          16h
logging-fluentd-wgj9c           1/1       Running            0          16h
logging-kibana-7-wsbrd          2/2       Running            0          16h
pod-diagnostic-test-tj1jh       0/1       Completed          0          16h
```
Deploy pod output;
```
>> oc logs logging-es-dee5e7z8-19-deploy
--> Scaling logging-es-dee5e7z8-18 down to zero
--> Scaling logging-es-dee5e7z8-19 to 1 before performing acceptance check
--> Error listing events for replication controller logging-es-dee5e7z8-19: Get https://172.30.0.1:443/api/v1/namespaces/logging/events?fieldSelector=involvedObject.kind%3DReplicationController%2CinvolvedObject.name%3Dlogging-es-dee5e7z8-19%2CinvolvedObject.namespace%3Dlogging%2CinvolvedObject.uid%3D7c857641-7b93-11e7-9f9d-022038e6f851: dial tcp 172.30.0.1:443: getsockopt: connection refused
--> Error listing events for replication controller logging-es-dee5e7z8-18: Get https://172.30.0.1:443/api/v1/namespaces/logging/events?fieldSelector=involvedObject.kind%3DReplicationController%2CinvolvedObject.name%3Dlogging-es-dee5e7z8-18%2CinvolvedObject.namespace%3Dlogging%2CinvolvedObject.uid%3D181269ae-7b8e-11e7-9f9d-022038e6f851: dial tcp 172.30.0.1:443: getsockopt: connection refused
error: couldn't scale logging-es-dee5e7z8-19 to 1: Scaling the resource failed with: Get https://172.30.0.1:443/api/v1/namespaces/logging/replicationcontrollers/logging-es-dee5e7z8-19: dial tcp 172.30.0.1:443: getsockopt: connection refused; Current resource version Unknown
```
The pods were manually configured to be privileged but because the deployment config was overwritten they can no longer complete
```
>> oc logs logging-es-ajxuvhnt-22-tlxww
[2017-08-08 09:29:48,399][INFO ][container.run            ] Begin Elasticsearch startup script
[2017-08-08 09:29:48,414][INFO ][container.run            ] Comparing the specified RAM to the maximum recommended for Elasticsearch...
[2017-08-08 09:29:48,415][INFO ][container.run            ] Inspecting the maximum RAM available...
[2017-08-08 09:29:48,420][INFO ][container.run            ] ES_JAVA_OPTS: '-Dmapper.allow_dots_in_name=true -Xms4096m -Xmx4096m'
Exception in thread "main" java.lang.IllegalStateException: Failed to created node environment
Likely root cause: java.nio.file.AccessDeniedException: /elasticsearch/persistent/logging-es
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
        at java.nio.file.Files.createDirectories(Files.java:767)
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:169)
        at org.elasticsearch.node.Node.<init>(Node.java:165)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
Refer to the log for complete error details.
[2017-08-08 09:29:48,424][INFO ][container.run            ] Checking if Elasticsearch is ready on https://localhost:9200 
```
Deployment config for the pod. The nodeSelector and securityContext patches applied manually were not preserved.
```
[root@ieabvlxosemsl01 ~]# oc get dc logging-es-ajxuvhnt -o yaml
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2017-07-25T10:25:41Z
  generation: 59
  labels:
    component: es
    deployment: logging-es-ajxuvhnt
    logging-infra: elasticsearch
    provider: openshift
  name: logging-es-ajxuvhnt
  namespace: logging
  resourceVersion: "1538583"
  selfLink: /oapi/v1/namespaces/logging/deploymentconfigs/logging-es-ajxuvhnt
  uid: 9bd5e3ca-7123-11e7-93de-061441c797d3
spec:
  replicas: 1
  selector:
    component: es
    deployment: logging-es-ajxuvhnt
    logging-infra: elasticsearch
    provider: openshift
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: es
        deployment: logging-es-ajxuvhnt
        logging-infra: elasticsearch
        provider: openshift
      name: logging-es-ajxuvhnt
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        - name: SERVICE_DNS
          value: logging-es-cluster
        - name: CLUSTER_NAME
          value: logging-es
        - name: INSTANCE_RAM
          value: 8Gi
        - name: NODE_QUORUM
          value: "2"
        - name: RECOVER_AFTER_NODES
          value: "2"
        - name: RECOVER_EXPECTED_NODES
          value: "3"
        - name: RECOVER_AFTER_TIME
          value: 5m
        image: registry.access.redhat.com/openshift3/logging-elasticsearch:v3.5
        imagePullPolicy: Always
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: restapi
          protocol: TCP
        - containerPort: 9300
          name: cluster
          protocol: TCP
        resources:
          limits:
            memory: 8Gi
          requests:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/elasticsearch/secret
          name: elasticsearch
          readOnly: true
        - mountPath: /usr/share/java/elasticsearch/config
          name: elasticsearch-config
          readOnly: true
        - mountPath: /elasticsearch/persistent
          name: elasticsearch-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        supplementalGroups:
        - 65534
      serviceAccount: aggregated-logging-elasticsearch
      serviceAccountName: aggregated-logging-elasticsearch
      terminationGracePeriodSeconds: 30
      volumes:
      - name: elasticsearch
        secret:
          defaultMode: 420
          secretName: logging-elasticsearch
      - configMap:
          defaultMode: 420
          name: logging-elasticsearch
        name: elasticsearch-config
      - hostPath:
          path: /elasticsearch/persistent
        name: elasticsearch-storage
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  conditions:
  - lastTransitionTime: 2017-07-25T10:25:41Z
    lastUpdateTime: null
    message: Deployment config does not have minimum availability.
    status: "False"
    type: Available
  - lastTransitionTime: 2017-08-07T17:11:59Z
    lastUpdateTime: 2017-08-07T17:12:01Z
    message: replication controller "logging-es-ajxuvhnt-22" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 22
  observedGeneration: 59
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```
Additionally the configmap, which has a bug in it https://access.redhat.com/solutions/3110981, https://bugzilla.redhat.com/show_bug.cgi?id=1466626, also gets overwritten. 
```
>> oc get configmap logging-elasticsearch -o yaml | grep io.fabric8
    io.fabric8.elasticsearch.authentication.users: ["system.logging.kibana", "system.logging.fluentd", "system.logging.curator", "system.admin"]
    io.fabric8.elasticsearch.kibana.mapping.app: /usr/share/elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
    io.fabric8.elasticsearch.kibana.mapping.ops: /usr/share/elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
      io.fabric8.elasticsearch: ${PLUGIN_LOGLEVEL}
      io.fabric8.kubernetes: ${PLUGIN_LOGLEVEL}
```
```
