### ISSUE TITLE
Issue redeploy master certs Origin 3.6

### ISSUE THREAD

**Issue by cello86** [openshift/openshift-ansible#5931]
#### Description
We tried to update the master certificates with the ansible script "/playbooks/byo/openshift-cluster/redeploy-master-certificates.yml" but we received this error:

```
TASK [openshift_named_certificates : set_fact] **********************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'unicode' object has no attribute 'keys'
fatal: [dev-openshift01.test.local]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT **************************************************************************************************************************
        to retry, use: --limit @/root/openshift-ansible/playbooks/byo/openshift-cluster/redeploy-master-certificates.retry
```

The full stack trace during the playbook execution is reported below:

```
task path: /root/openshift-ansible/roles/openshift_named_certificates/tasks/main.yml:2
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 465, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 248, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 376, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 494, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 450, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 672, in do_template
    res = j2_concat(rf)
  File "<template>", line 11, in root
  File "/root/openshift-ansible/filter_plugins/oo_filters.py", line 571, in oo_parse_named_certificates
    if 'names' in certificate.keys():
AttributeError: 'unicode' object has no attribute 'keys'

fatal: [dev-openshift01.test.local]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

##### Version

```
# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```
##### Steps To Reproduce
1. We create new master certificate from a custom installation and we'll configure the hosts ansible file with new paths.
2. We execute the playbook as root user.

##### Expected Results
We expect to update the certificates on the master nodes.

##### Observed Results
The scripts fails during the task execution.

##### Additional Information

```
# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```

**Comment by abutcher** [comment]
Hey @cello86, what is set for `openshift_master_named_certificates` within the inventory?

**Comment by cello86** [comment]
Hi @abutcher,
I configured the openshift_master_named_certificates adding also the parameter "names" and this works fine.

```
openshift_master_overwrite_named_certificates=true
openshift_master_named_certificates=[{"certfile": "/root/openshift/certs/dev-openshift.local.crt", "keyfile": "/root/openshift/certs/dev-openshift.local.key", "cafile": "/root/openshift/certs/internalCA.crt", "names": ["dev-openshift.test.local"]}]
```

Actually we have a problem after the console certificate upgrade, because the console certs is ok but the registry and registry console don't work correctly.

Marcello
