### ISSUE TITLE
Unable to start origin-master-api during installation of v1.5

### ISSUE THREAD

**Issue by chinacoolhacker** [openshift/openshift-ansible#5941]
#### Unable to start origin-master-api during installation of  v1.5

```
[root@dev-g001-master-1 ~]# rpm -qa | grep orig
origin-clients-1.5.1-1.el7.x86_64
origin-master-1.5.1-1.el7.x86_64
origin-1.5.1-1.el7.x86_64
[root@dev-g001-master-1 ~]# systemctl restart origin-master-api.service 
Job for origin-master-api.service failed because a fatal signal was delivered causing the control process to dump core. See "systemctl status origin-master-api.service" and "journalctl -xe" for details.
[root@dev-g001-master-1 ~]# systemctl status origin-master-api.service
● origin-master-api.service - Atomic OpenShift Master API
   Loaded: loaded (/usr/lib/systemd/system/origin-master-api.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: core-dump) since Tue 2017-10-31 09:56:56 UTC; 483ms ago
     Docs: https://github.com/openshift/origin
  Process: 29122 ExecStart=/usr/bin/openshift start master api --config=${CONFIG_FILE} $OPTIONS (code=dumped, signal=ABRT)
 Main PID: 29122 (code=dumped, signal=ABRT)

Oct 31 09:56:56 dev-g001-master-1.novalocal systemd[1]: Failed to start Atomic OpenShift Master API.
Oct 31 09:56:56 dev-g001-master-1.novalocal systemd[1]: Unit origin-master-api.service entered failed state.
Oct 31 09:56:56 dev-g001-master-1.novalocal systemd[1]: origin-master-api.service failed.
```
My generated /etc/origin/master/master-config.yaml contains:
```

kubernetesMasterConfig:
  apiServerArguments:
    runtime-config:
     - apis/settings.k8s.io/v1alpha1=false
  controllerArguments:
    node-monitor-grace-period:
    - 24s
    node-monitor-period:
    - 3s
    pod-eviction-timeout:
    - 3m
  masterCount: 3
  masterIP: 192.168.102.81
  podEvictionTimeout: 1m
  proxyClientInfo:
    certFile: master.proxy-client.crt
    keyFile: master.proxy-client.key
  schedulerArguments: 
  schedulerConfigFile: /etc/origin/master/scheduler.json
  servicesNodePortRange: 30000-32999
  servicesSubnet: 172.30.0.0/16
  staticNodeNames: []
```

but `apis/settings.k8s.io/v1alpha1=false` looks unavailable at v1.5

```
Oct 31 10:01:17 dev-g001-master-1.novalocal atomic-openshift-master-api[29692]: E1031 10:01:17.791372   29692 configgetter.go:63] group version apis/settings.k8s.io that has not been registered
Oct 31 10:01:17 dev-g001-master-1.novalocal atomic-openshift-master-api[29692]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 31 10:01:17 dev-g001-master-1.novalocal atomic-openshift-master-api[29692]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x185ca8a]
Oct 31 10:01:17 dev-g001-master-1.novalocal atomic-openshift-master-api[29692]: goroutine 1 [running]:
Oct 31 10:01:17 dev-g001-master-1.novalocal atomic-openshift-master-api[29692]: panic(0x3b55580, 0xc420010040)
Oct 31 10:01:17 dev-g001-master-1.novalocal atomic-openshift-master-api[29692]: /usr/lib/golang/src/runtime/panic.go:500 +0x1a1 fp=0xc420f8ced8 sp=0xc420f8ce48
Oct 31 10:01:17 dev-g001-master-1.novalocal atomic-openshift-master-api[29692]: runtime.panicmem()
Oct 31 10:01:17 dev-g001-master-1.novalocal atomic-openshift-master-api[29692]: /usr/lib/golang/src/runtime/panic.go:62 +0x6d fp=0xc420f8cf08 sp=0xc420f8ced8
Oct 31 10:01:17 dev-g001-master-1.novalocal atomic-openshift-master-api[29692]: runtime.sigpanic()
Oct 31 10:01:17 dev-g001-master-1.novalocal atomic-openshift-master-api[29692]: /usr/lib/golang/src/runtime/sigpanic_unix.go:24 +0x214 fp=0xc420f8cf60 sp=0xc420f8cf08

```

##### Version
ansible --version 

```
$ ansible --version 
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/scripts/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### Steps To Reproduce
1. Try to install v1.5 OpenShift with openshift-ansible-3.7.0-0.188.0 release

##### Expected Results
OpenShift v1.5 installed

##### Observed Results
OpenShift v1.5 installation failed 

```
TASK [restart master api] *******************************************************************************************************************************************************************************************
fatal: [10.101.17.29]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service origin-master-api: Job for origin-master-api.service failed because a fatal signal was delivered causing the control process to dump core. See \"systemctl status origin-master-api.service\" and \"journalctl -xe\" for details.\n"}
	to retry, use: --limit @/scripts/DEV_gluster/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************
10.101.17.26               : ok=225  changed=84   unreachable=0    failed=0   
10.101.17.27               : ok=225  changed=87   unreachable=0    failed=0   
10.101.17.29               : ok=273  changed=99   unreachable=0    failed=1   
localhost                  : ok=12   changed=0    unreachable=0    failed=0   

```

**Comment by sdodson** [comment]
@chinacoolhacker Hi, thanks for the issue. Unfortunately at this point the master branch is not tested against v1.5.x so it's not a surprise that you're running into problems there and we'd prefer not adding more conditional logic to the master branch to make it work. Can you please use the release-1.5 branch and see if that works better for you?

https://github.com/openshift/openshift-ansible#getting-the-correct-version describes our branching strategy

**Comment by chinacoolhacker** [comment]
@sdodson Hi! Unfortunately, release-1.5 branch does not support glusterfs, so i cant use it. In PR  https://github.com/openshift/openshift-ansible/pull/5786 master branch was suggested for deploy version 1.5, so, here am i. Can i back-port v1.5 templates into release-3.6, or such big feature will be rejected too?

**Comment by chinacoolhacker** [comment]
release-3.6 can install OS 1.5 with gluster
