### ISSUE TITLE
Installation fails with latest master branch

### ISSUE THREAD

**Issue by pgeorgiev333** [openshift/openshift-ansible#6057]
#### Description
Cannot install openshift origin from the master branch.

##### Version

```
ansible 2.4.0.0
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

git describe
openshift-ansible-3.7.0-0.198.0-2-g196891f

```

##### Steps To Reproduce
1. Run the playbook 

```
ansible-playbook /root/openshift-ansible/playbooks/byo/config.yml 
```

##### Expected Results
Install to be successful.

##### Observed Results
Installation fails on TASK [initialize_facts set_fact on openshift_docker_hosted_registry_network] 

```
     Message:  The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'openshift'

               The error appears to have been in '/root/openshift-ansible/playbooks/common/openshift-cluster/initialize_facts.yml': line 167, column 5, but may
               be elsewhere in the file depending on the exact syntax problem.

               The offending line appears to be:


                 - name: initialize_facts set_fact on openshift_docker_hosted_registry_network
                   ^ here

               exception type: <class 'ansible.errors.AnsibleUndefinedVariable'>
               exception: 'dict object' has no attribute 'openshift'

```

##### Additional Information

CentOs 7

I have 1 master, 2 nodes and 3 machines for the glusterfs storage. Here's my config (FQDN masked with XXX.YYY):

```
[OSEv3:children]
masters
nodes
etcd
nfs
glusterfs

[OSEv3:vars]

openshift_deployment_type=origin

ansible_ssh_user=root
containerized=false
openshift_master_cluster_hostname=openshift.XXX.YYY
openshift_master_cluster_public_hostname=openshift.XXX.YYY

# Can set multitenant plugin
os_sdn_network_plugin_name=redhat/openshift-ovs-subnet

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

os_firewall_use_firewalld=true

openshift_portal_net=172.30.0.0/16
openshift_master_default_subdomain=XXX.YYY

openshift_node_proxy_mode=iptables

osm_cluster_network_cidr=10.128.0.0/14

osm_host_subnet_length=9

# Metrics
openshift_metrics_install_metrics=true

openshift_metrics_hawkular_hostname=metrics.XXX.YYY
openshift_logging_kibana_hostname=kibana.XXX.YYY

openshift_metrics_storage_kind=nfs
openshift_metrics_storage_access_modes=['ReadWriteOnce']
openshift_metrics_storage_nfs_directory=/exports
openshift_metrics_storage_nfs_options='*(rw,root_squash)'
openshift_metrics_storage_volume_name=metrics
openshift_metrics_storage_volume_size=10Gi

openshift_deployment_type=origin

openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_nfs_directory=/exports
openshift_hosted_registry_storage_nfs_options='*(rw,root_squash)'
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=10Gi

openshift_storage_glusterfs_namespace=glusterfs
openshift_storage_glusterfs_name=storage

openshift_logging_install_logging=true

[masters]
openshift.XXX.YYY containerized=false

[nodes]
openshift.XXX.YYY openshift_hostname=openshift.XXX.YYY openshift_schedulable=true openshift_node_labels="{'region': 'infra'}"
oc-node-1.XXX.YYY openshift_node_labels="{'region': 'primary', 'zone': 'bg'}"
oc-node-2.XXX.YYY openshift_node_labels="{'region': 'primary', 'zone': 'bg'}"
oc-gluster-1.XXX.YYY
oc-gluster-2.XXX.YYY
oc-gluster-3.XXX.YYY

[etcd]
openshift.XXX.YYY

[nfs]
openshift.XXX.YYY

[glusterfs]
oc-gluster-1.XXX.YYY glusterfs_ip=10.xx.xx.xx glusterfs_devices='[ "/dev/sdc" ]'
oc-gluster-2.XXX.YYY glusterfs_ip=10.xx.xx.xx glusterfs_devices='[ "/dev/sdc" ]'
oc-gluster-3.XXX.YYY glusterfs_ip=10.xx.xx.xx glusterfs_devices='[ "/dev/sdc" ]'

```

**Comment by pgeorgiev333** [comment]
I noticed that there is another error before the last one:

TASK [Gather Cluster facts and set is_containerized if needed] ******************************************************************************************************************************************
Wednesday 08 November 2017  16:41:14 +0200 (0:00:00.160)       0:00:41.517 ****
ok: [oc-node-1.XXX.YYY]
ok: [oc-gluster-2.XXX.YYY]
fatal: [openshift.XXX.YYY]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to openshift.XXX.YYY closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_SGvTNZ/ansible_module_openshift_facts.py\", line 2470, in <module>\r\n    main()\r\n  File \"/tmp/ansible_SGvTNZ/ansible_module_openshift_facts.py\", line 2457, in main\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_SGvTNZ/ansible_module_openshift_facts.py\", line 1830, in __init__\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_SGvTNZ/ansible_module_openshift_facts.py\", line 1879, in generate_facts\r\n    facts = set_selectors(facts)\r\n  File \"/tmp/ansible_SGvTNZ/ansible_module_openshift_facts.py\", line 496, in set_selectors\r\n    facts['logging']['selector'] = None\r\nTypeError: 'unicode' object does not support item assignment\r\n", "msg": "MODULE FAILURE", "rc": 0}

**Comment by sosiouxme** [comment]
The earlier error causes the one that's reported at the end because nodes try to look up master variables that aren't set due to early failure. It's very confusing and unfortunate.

As far as the real error, I'm seeing it too and I have no idea why yet:

```
<origin-master> (1, '', 'Traceback (most recent call last):\n  File "/tmp/ansible_mk96O4/ansible_module_openshift_facts.py", line 2470, in <module>\n    main()\n  File "/tmp/ansible_mk96O4/ansible_module_openshift_facts.py", line 2457, in main\n    protected_facts_to_overwrite)\n  File "/tmp/ansible_mk96O4/ansible_module_openshift_facts.py", line 1830, in __init__\n    protected_facts_to_overwrite)\n  File "/tmp/ansible_mk96O4/ansible_module_openshift_facts.py", line 1879, in generate_facts\n    facts = set_selectors(facts)\n  File "/tmp/ansible_mk96O4/ansible_module_openshift_facts.py", line 496, in set_selectors\n    facts[\'logging\'][\'selector\'] = None\nTypeError: \'unicode\' object does not support item assignment\n')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_mk96O4/ansible_module_openshift_facts.py", line 2470, in <module>
    main()
  File "/tmp/ansible_mk96O4/ansible_module_openshift_facts.py", line 2457, in main
    protected_facts_to_overwrite)
  File "/tmp/ansible_mk96O4/ansible_module_openshift_facts.py", line 1830, in __init__
    protected_facts_to_overwrite)
  File "/tmp/ansible_mk96O4/ansible_module_openshift_facts.py", line 1879, in generate_facts
    facts = set_selectors(facts)
  File "/tmp/ansible_mk96O4/ansible_module_openshift_facts.py", line 496, in set_selectors
    facts['logging']['selector'] = None
TypeError: 'unicode' object does not support item assignment

fatal: [origin-master]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mk96O4/ansible_module_openshift_facts.py\", line 2470, in <module>\n    main()\n  File \"/tmp/ansible_mk96O4/ansible_module_openshift_facts.py\", line 2457, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_mk96O4/ansible_module_openshift_facts.py\", line 1830, in __init__\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_mk96O4/ansible_module_openshift_facts.py\", line 1879, in generate_facts\n    facts = set_selectors(facts)\n  File \"/tmp/ansible_mk96O4/ansible_module_openshift_facts.py\", line 496, in set_selectors\n    facts['logging']['selector'] = None\nTypeError: 'unicode' object does not support item assignment\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

```
$ ansible-playbook --version
ansible-playbook 2.4.1.0
  config file = /home/lmeyer/go/src/github.com/openshift/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/lmeyer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lmeyer/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.14 (default, Nov  2 2017, 18:42:05) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

**Comment by michaelgugino** [comment]
This seems to be related to stale data on either the target host or the localhost (where ansible is run from) in the following file:

'/etc/ansible/facts.d/openshift.fact'

I'm unsure of the root cause as to why the logging variables are inject into that file, or if they are needed/desired in that file.

The work around for now is to back up that facts file (not sure if it's needed on subsequent runs against the same clstuer) and remove it from the localhost/taget hosts.

**Comment by sosiouxme** [comment]
I have logging and metrics vars commented out in inventory:

```
#openshift_hosted_logging_deploy=true
#openshift_logging_image_version=v3.7.0-alpha.0
```

I ran with them on an initial run and then commented them out later. Logging is in fact deployed.
