### ISSUE TITLE
3.9 templates missing from glusterfs role

### ISSUE THREAD

**Issue by jmencak** [openshift/openshift-ansible#6593]
#### Description
3.9 templates are missing from glusterfs role, which breaks an installation.

##### Version

```
ansible 2.4.2.0
  config file = /home/cloud-user/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/cloud-user/openshift-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Dec  8 2017, 16:39:59) [GCC 4.8.5 20150623 (Red Hat 4.8.5-25)]

openshift-ansible-3.9.0-0.13.0-10-g19d1642c2
```

##### Expected Results
Successful install of cns on 3.9.

##### Observed Results

```
TASK [openshift_storage_glusterfs : Copy GlusterFS DaemonSet template] *********
task path: /home/cloud-user/openshift-ansible/roles/openshift_storage_glusterfs/tasks/glusterfs_deploy.yml:66
Wednesday 03 January 2018  03:38:28 -0500 (0:00:01.918)       0:22:22.690 *****
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/copy.py", line 457, in run
    source = self._find_needle('files', source)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 986, in _find_needle
    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
  File "/usr/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 386, in path_dwim_relative_stack
    raise AnsibleFileNotFound(file_name=source, paths=[to_text(p) for p in search])
AnsibleFileNotFound: Could not find or access 'v3.9/glusterfs-template.yml'
Searched in:
        /home/cloud-user/openshift-ansible/roles/openshift_storage_glusterfs/files/v3.9/glusterfs-template.yml
        /home/cloud-user/openshift-ansible/roles/openshift_storage_glusterfs/v3.9/glusterfs-template.yml
        /home/cloud-user/openshift-ansible/roles/openshift_storage_glusterfs/tasks/files/v3.9/glusterfs-template.yml
        /home/cloud-user/openshift-ansible/roles/openshift_storage_glusterfs/tasks/v3.9/glusterfs-template.yml
        /home/cloud-user/openshift-ansible/playbooks/openstack/openshift-cluster/../../openshift-glusterfs/private/files/v3.9/glusterfs-template.yml
        /home/cloud-user/openshift-ansible/playbooks/openstack/openshift-cluster/../../openshift-glusterfs/private/v3.9/glusterfs-template.yml
fatal: [master-0.scale-ci.example.com]: FAILED! => {
    "changed": false,
    "msg": "Could not find or access 'v3.9/glusterfs-template.yml'\nSearched in:\n\t/home/cloud-user/openshift-ansible/roles/openshift_storage_glusterfs/files/v3.9/glusterfs-template.yml\n\t/home/cloud-user/openshift-ansible/roles/openshift_storage_glusterfs/v3.9/glusterfs-template.yml\n\t/home/cloud-user/openshift-ansible/roles/openshift_storage_glusterfs/tasks/files/v3.9/glusterfs-template.yml\n\t/home/cloud-user/openshift-ansible/roles/openshift_storage_glusterfs/tasks/v3.9/glusterfs-template.yml\n\t/home/cloud-user/openshift-ansible/playbooks/openstack/openshift-cluster/../../openshift-glusterfs/private/files/v3.9/glusterfs-template.yml\n\t/home/cloud-user/openshift-ansible/playbooks/openstack/openshift-cluster/../../openshift-glusterfs/private/v3.9/glusterfs-template.yml"
}
```

##### Additional Information

Simply copying 3.8 templates to 3.9 templates fixes the problem for me.
```
cp -a openshift-ansible/roles/openshift_storage_glusterfs/templates/v3.8 openshift-ansible/roles/openshift_storage_glusterfs/templates/v3.9
cp -a openshift-ansible/roles/openshift_storage_glusterfs/files/v3.8 openshift-ansible/roles/openshift_storage_glusterfs/files/v3.9
```

**Comment by jmencak** [comment]
Fixed by: https://github.com/openshift/openshift-ansible/pull/6596
