### ISSUE TITLE
Metrics: CPU & MEMORY Usage not working...

### ISSUE THREAD

**Issue by dungdm93** [openshift/openshift-ansible#7548]
I'm install OpenShift on Google Cloud Platform.
It's success and everything look good:
```
[cloud-user@openshift-master]$ oc get all -n openshift-infra 

NAME                      HOST/PORT                           PATH      SERVICES           PORT      TERMINATION   WILDCARD
routes/hawkular-metrics   hawkular-metrics.apps.dungdm93.tk             hawkular-metrics   <all>     reencrypt     None

NAME                            READY     STATUS    RESTARTS   AGE
po/hawkular-cassandra-1-lfz9z   1/1       Running   0          23m
po/hawkular-metrics-s97df       1/1       Running   0          23m
po/heapster-l5xch               1/1       Running   0          23m

NAME                      DESIRED   CURRENT   READY     AGE
rc/hawkular-cassandra-1   1         1         1         23m
rc/hawkular-metrics       1         1         1         24m
rc/heapster               1         1         1         24m

NAME                           CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
svc/hawkular-cassandra         172.30.24.228    <none>        9042/TCP,9160/TCP,7000/TCP,7001/TCP   24m
svc/hawkular-cassandra-nodes   None             <none>        9042/TCP,9160/TCP,7000/TCP,7001/TCP   24m
svc/hawkular-metrics           172.30.212.220   <none>        443/TCP                               24m
svc/heapster                   172.30.181.240   <none>        80/TCP                                24m

```
However, metrics: CPU & MEMORY Usage not working...
![image](https://user-images.githubusercontent.com/6848311/37513944-0d155ee2-2939-11e8-80f8-a71582be8710.png)
My config:
```yaml
openshift_metrics_install_metrics: true
openshift_metrics_storage_kind: dynamic
openshift_metrics_storage_volume_size: 20Gi
```
I have try many time, but I got the same problem. Any idea???

**Comment by saurabhtandon13** [comment]
Hello, 

Can you please let me know what is the output when you open the metrics route from the browser.

**Comment by dungdm93** [comment]
@saurabhtandon13 
```

2018-03-19 04:41:33,008 WARN  [org.hawkular.metrics.core.dropwizard.HawkularMetricsRegistryListener] (default task-18) Did not find meta data for timer GET {dual_path} that has been added to the registry
--
  | 2018-03-19 04:41:33,009 WARN  [org.hawkular.metrics.core.dropwizard.HawkularObjectNameFactory] (default task-18) No meta data found for GET {dual_path}
  | 2018-03-19 05:00:30,470 INFO  [org.hawkular.metrics.core.jobs.TempDataCompressor] (RxIoScheduler-3) Starting to process temp table for starting time of 2018-03-19T02:00:00.000Z
  | 2018-03-19 05:00:30,474 INFO  [org.hawkular.metrics.core.jobs.TempDataCompressor] (RxIoScheduler-4) Finished processing data in 15 ms
  | 2018-03-19 05:00:30,478 ERROR [org.hawkular.metrics.core.service.MetricsServiceImpl] (RxComputationScheduler-2) Failure while trying to apply compression, skipping block: java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table data_temp_2018031902
  | at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
  | at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
  | at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
  | at rx.observable.ListenableFutureObservable$2$1.run(ListenableFutureObservable.java:78)
  | at rx.observable.ListenableFutureObservable$1$1.call(ListenableFutureObservable.java:50)
  | at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$1.call(EventLoopsScheduler.java:172)
  | at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table data_temp_2018031902
  | at com.datastax.driver.core.Responses$Error.asException(Responses.java:148)
  | at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
  | at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:186)
  | at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:50)
  | at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:817)
  | at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:651)
  | at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1077)
  | at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1000)
  | at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
  | at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
  | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
  | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
  | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
  | at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1267)
  | at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1078)
  | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:491)
  | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:430)
  | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
  | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
  | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
  | at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
  | at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
  | ... 1 more
  | 2018-03-19 05:36:21,057 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-60) RESTEASY002142: Multiple resource methods match request "GET /". Selecting one. Matching methods: [public javax.ws.rs.core.Response org.hawkular.metrics.api.jaxrs.handler.BaseHandler.baseJSON(), public void org.hawkular.metrics.api.jaxrs.handler.BaseHandler.baseHTML(javax.servlet.ServletContext) throws java.lang.Exception]
```
Or you could see full logs file here: [hawkular-metrics-m4rb8.log](https://github.com/openshift/openshift-ansible/files/1823815/hawkular-metrics-m4rb8.log)

**Comment by dungdm93** [comment]
@saurabhtandon13 
![image](https://user-images.githubusercontent.com/6848311/37579950-b6756e64-2b73-11e8-80a9-bb60a2d5d6fc.png)
Then it redirect to `hawkular/metrics/ui/index.html`
![image](https://user-images.githubusercontent.com/6848311/37579969-d329c3b6-2b73-11e8-91be-3726348479e6.png)

**Comment by saurabhtandon13** [comment]
Hello, 
Looks like the POD are up and running, on the other hand application doesn't come up. Kindly check the below POD logs 

# oc logs -f  hawkular-metrics-s97df 

# oc logs -f  hawkular-cassandra-1-lfz9z

if there is any java error or the error is related to the application not able to connect to DB. Kindly restart the metrics pods via below command. 

# oc delete pod <hawkular-metrics-s97df> and check the logs of the pods and then try to check the Hawkular Metrics URL from the browser.

**Comment by dungdm93** [comment]
@saurabhtandon13 I tried it many times. I even delete my cluster and re-create it.
