### ISSUE TITLE
Ansible server issues 

### ISSUE THREAD

**Issue by Dhariaj** [openshift/openshift-ansible#7978]
I have posted the same question on the quickstart guide section for openshift as I am not soo sure where and which is the right forum.  

I am using the new template that was released on April, 6, 2018 and having issues with the ansible server. The error log is pasted below and I checked the host file and it looks empty. Up until yesterday the host file was getting populated but the Ansible was not able to SSH to just the master nodes and now today this...

ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
Apr 13 14:18:37 ip-10-1x.x.x cloud-init: [WARNING]: provided hosts list is empty, only localhost is available. Note
Apr 13 14:18:37 ip-10-x.x.x cloud-init: that the implicit localhost does not match 'all'
Apr 13 14:18:38 ip-10-1x.x.x cloud-init: + qs_err ' Openshift installation failed, see logs for details '

**Comment by Dhariaj** [comment]
I also ran the command /bin/aws-ose-qs-scale --generate-initial-inventory --write-hosts-to-tempfiles
 manually and got the following error 

[root@ip-10-x-x- ec2-user]# /bin/aws-ose-qs-scale --generate-initial-inventory --write-hosts-to-tempfiles
Traceback (most recent call last):
File "/bin/aws-ose-qs-scale", line 14, in 
sys.exit(main())
File "/bin/aws-ose-qs-scale", line 11, in main
return aws_openshift_quickstart.scaler.main()
File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 297, in main
ClusterGroups.setup()
File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 646, in setup
for group in cls._determine_cluster_groups():
File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 658, in _determine_cluster_groups
_g = LocalASG(all_groups[i])
File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 470, in init
self.openshift_config_category = self._determine_openshift_category(self.logical_id)
AttributeError: 'LocalASG' object has no attribute 'logical_id'

**Comment by Dhariaj** [comment]
Please refer to this thread for a possible solution https://github.com/aws-quickstart/quickstart-redhat-openshift/issues/117
