### ISSUE TITLE
ansible-playbook installation failed with etcd_client_flannel_certs_missing

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#844]
It looks like etc_client_flannel_certs_missing is only defined when use_flannel is true, but in the later check that sets etcd_needing_client_certs does not have a conditional on use_flannel or take into account that etc_client_flannel_certs_missing may not be set on a host.

As a workaround, you could change line 72 of https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-node/config.yml to set etcd_needing_client_certs to []

​
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=root
product_type=openshift
deployment_type=enterprise

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/openshift/openshift-passwd'}]

# host group for masters
[masters]
ose3-master1.oseinternal.priv

# host group for etcd
[etcd]
ose3-master1.oseinternal.priv

# host group for nodes, includes region info
[nodes]
ose3-master1.oseinternal.priv
ose3-infra1.oseinternal.priv openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
ose3-node01.oseinternal.priv openshift_node_labels="{'region': 'primary', 'zone': 'odd'}"
ose3-node02.oseinternal.priv openshift_node_labels="{'region': 'primary', 'zone': 'even'}"

TASK: [etcd_certificates | Ensure generated_certs directory present] **********
fatal: [ose3-master1.oseinternal.priv] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 815, in _executor_internal
    complex_args=complex_args
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 869, in _executor_internal_inner
    if not utils.check_conditional(cond, self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/usr/lib/python2.7/site-packages/ansible/utils/__init__.py", line 269, in check_conditional
    conditional = template.template(basedir, presented, inject)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 6, in root
  File "/usr/lib/python2.7/site-packages/jinja2/runtime.py", line 153, in resolve
    return self.parent[key]
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 205, in __getitem__
    return template(self.basedir, var, self.vars, fail_on_undefined=self.fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 11, in root
  File "/root/openshift-ansible/filter_plugins/oo_filters.py", line 278, in oo_filter_list
    return [x for x in data if x[filter_attr]]
KeyError: 'etcd_client_flannel_certs_missing'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/config.retry

localhost                  : ok=12   changed=0    unreachable=0    failed=0
ose3-infra1.oseinternal.priv : ok=8    changed=1    unreachable=0    failed=0
ose3-master1.oseinternal.priv : ok=237  changed=9    unreachable=1    failed=0
ose3-node01.oseinternal.priv : ok=8    changed=1    unreachable=0    failed=0
ose3-node02.oseinternal.priv : ok=8    changed=1    unreachable=0    failed=0

**Comment by abutcher** [comment]
@brenton This one can be closed
