### ISSUE TITLE
Logging fails to install when using a cinder volume

### ISSUE THREAD

**Issue by tdudgeon** [openshift/openshift-ansible#8456]
#### Description

When deploying logging when using a PVC backed by a cinder volume the elasticsearch container fails to start due to permissions problem. When using NFS or GlusterFS backed volumes it works fine.

##### Version

```
ansible 2.5.0
openshift-ansible git: openshift-ansible-3.7.48-1-10-g3583ac5
```

##### Steps To Reproduce
1. create pvc/pv using this:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-es-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: cloud-block-volume
```

2. run the playbook:
```
ansible-playbook -i inventory -e openshift_logging_install_logging=true ~/github/openshift-ansible-release-3.7/playbooks/byo/openshift-cluster/openshift-logging.yml
```
Here is the relevant part of the inverntory file:
```
openshift_logging_install_logging=true
openshift_logging_image_version=v3.7
openshift_logging_elasticsearch_proxy_image_version=v1.0.0
openshift_logging_kibana_nodeselector={"zone":"default"}
openshift_logging_curator_nodeselector={"zone":"default"}
openshift_logging_es_nodeselector={"zone":"default"}
openshift_logging_es_pvc_storage_class_name=cloud-block-volume
openshift_logging_es_pvc_size=15Gi
```

##### Expected Results

All pods in logging project would start correctly

##### Observed Results

The elasticsearch container fails to start:
```
[2018-05-21 11:03:48,483][INFO ][container.run            ] Begin Elasticsearch startup script
[2018-05-21 11:03:48,500][INFO ][container.run            ] Comparing the specified RAM to the maximum recommended for Elasticsearch...
[2018-05-21 11:03:48,503][INFO ][container.run            ] Inspecting the maximum RAM available...
[2018-05-21 11:03:48,513][INFO ][container.run            ] ES_HEAP_SIZE: '4096m'
[2018-05-21 11:03:48,527][INFO ][container.run            ] Setting heap dump location /elasticsearch/persistent/heapdump.hprof
[2018-05-21 11:03:48,531][INFO ][container.run            ] Checking if Elasticsearch is ready on https://localhost:9200
Exception in thread "main" java.lang.IllegalStateException: Failed to created node environment
Likely root cause: java.nio.file.AccessDeniedException: /elasticsearch/persistent/logging-es
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
    at java.nio.file.Files.createDirectory(Files.java:674)
    at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
    at java.nio.file.Files.createDirectories(Files.java:767)
    at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:169)
    at org.elasticsearch.node.Node.<init>(Node.java:165)
    at org.elasticsearch.node.Node.<init>(Node.java:140)
    at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
Refer to the log for complete error details.
```

##### Additional Information

The directory ownerships do look very strange. Using Gluster (where it works) you see this (/elasticsearch/persistent is where the volume is mounted):

sh-4.2$ cd /elasticsearch/persistent
sh-4.2$ ls -al
total 8
drwxrwsr-x. 4 root 2009 4096 May 21 07:17 .
drwxrwxrwx. 4 root root   42 May 21 07:17 ..
drwxr-sr-x. 3 1000 2009 4096 May 21 07:17 logging-es

User 1000 and group 2009 do not exist in /etc/passwd or /etc/groups.
The elasticsearch container is running as this user:
```
$ id
uid=1000 gid=0(root) groups=0(root),2009,65534
```

**Comment by anpingli** [comment]
Is there any special configuration in nodes or openstack? We never hit such issue when deploy logging using cinder volume.

**Comment by tdudgeon** [comment]
Nothing I can think of. We're only a tenant on the openshift environment so can't comment on things deep down, but we're just using the cloud provider as is described in the docs and cinder volumes are working for other things, so it does look to be a strange permissions problem with the elacticsearch container.
I can show this in action if that helps.

**Comment by tdudgeon** [comment]
I hit this problem again. To avoid it you need to:
1. ssh to the node where the elasticsearch pod is running
2. do a `docker exec -it -u 0:0 <container> bash` into the elasticsearch container
3. modify the permissions using `chmod g+w /elasticsearch/persistent`

**Comment by anpingli** [comment]
How your cinder volume are attached elasticsearch pods?   Have you used storageclass?

**Comment by tdudgeon** [comment]
Yes, see above for details.
The volume is provisioned and attached fine.
It's just the permissions that are wrong.

**Comment by richm** [comment]
This is what we have to do for Elasticsearch for local storage - it may also be applicable to gluster:
https://github.com/ViaQ/Main/blob/master/README-install.md#persistent-storage
and
https://github.com/ViaQ/Main/blob/master/README-install.md#enabling-elasticsearch-to-mount-the-directory
