### ISSUE TITLE
Unexpected Exception, this is probably a bug: [Errno 24] No file descriptors available

### ISSUE THREAD

**Issue by prasadjlv** [openshift/openshift-ansible#9077]
#### Description

 Multi master installation fails with:

2018-07-05 00:09:07,406 p=10 u=root |  ERROR! Unexpected Exception, this is probably a bug: [Errno 24] No file descriptors available

##### Version

# ansible --version
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Feb 22 2018, 21:59:35) [GCC 6.3.0]

```
openshift-ansible-3.7.52-1
```

##### Steps To Reproduce
1. ansible-playbook playbooks/byo/config.yml

##### Observed Results

```
2018-07-05 00:09:07,403 p=10 u=root |  PLAY [Node Install Checkpoint Start] **************************************************************************************************************************************************************************************
2018-07-05 00:09:07,406 p=10 u=root |  ERROR! Unexpected Exception, this is probably a bug: [Errno 24] No file descriptors available
2018-07-05 00:09:07,409 p=10 u=root |  the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 266, in run
    self._initialize_processes(min(self._options.forks, iterator.batch_size))
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 114, in _initialize_processes
    rslt_q = multiprocessing.Queue()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 69, in __init__
    self._sem = BoundedSemaphore(maxsize)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 130, in __init__
    SemLock.__init__(self, SEMAPHORE, value, value)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 24] No file descriptors available
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

* openshift-ansible is running in an alpine 3.5.0 container
* Inventory file (partial)
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=root
ansible_become=true
debug_level=2
deployment_type=origin
openshift_image_tag=v3.7.2
openshift_install_examples=false
openshift_master_cluster_method=native
openshift_pkg_version=-3.7.2
openshift_release=v3.7

# increase max number of inflight requests
openshift_master_max_requests_inflight=1000

* Sample code, etc

```
ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 14992
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1048576
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

sysctl fs.file-nr
fs.file-nr = 1408	0	300000
```

**Comment by prasadjlv** [comment]
The above deployment works fine in ansible 2.5.5.
