### ISSUE TITLE
[3.11] Module failure in rule_expand_ports when from_port == "all"

### ISSUE THREAD

**Issue by frobware** [openshift/openshift-ansible#9342]
#### Description

Running:

   

    $ cd ~/openshift-ansible/
    $ git branch
    * (HEAD detached at openshift-ansible-3.11.0-0.9.0)

    $ ansible-playbook -vvv -i inventory ~/openshift-ansible/playbooks/aws/openshift-cluster/prerequisites.yml -e @vars.yaml

Note: I have been running this in 3.10 and I did not see the error there.

```console

TASK [openshift_aws : create the node group sgs] **************************************************************************************************
task path: /home/aim/openshift-ansible/roles/openshift_aws/tasks/security_group.yml:9
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: aim
<127.0.0.1> EXEC /bin/sh -c 'echo ~aim && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/aim/.ansible/tmp/ansible-tmp-1532603123.2-187451616775925 `" && echo ansible-tmp-1532603123.2-187451616775925="` echo /home/aim/.ansible/tmp/ansible-tmp-1532603123.2-187451616775925 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/amazon/ec2_group.py
<127.0.0.1> PUT /home/aim/.ansible/tmp/ansible-local-269492P21AR/tmp8dbqdo TO /home/aim/.ansible/tmp/ansible-tmp-1532603123.2-187451616775925/ec2_group.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/aim/.ansible/tmp/ansible-tmp-1532603123.2-187451616775925/ /home/aim/.ansible/tmp/ansible-tmp-1532603123.2-187451616775925/ec2_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/aim/.ansible/tmp/ansible-tmp-1532603123.2-187451616775925/ec2_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/aim/.ansible/tmp/ansible-tmp-1532603123.2-187451616775925/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_a3heeo/ansible_module_ec2_group.py", line 1021, in <module>
    main()
  File "/tmp/ansible_a3heeo/ansible_module_ec2_group.py", line 875, in main
    rules = deduplicate_rules_args(rules_expand_sources(rules_expand_ports(module.params['rules'])))
  File "/tmp/ansible_a3heeo/ansible_module_ec2_group.py", line 607, in rules_expand_ports
    for rule in rule_expand_ports(rule_complex)]
  File "/tmp/ansible_a3heeo/ansible_module_ec2_group.py", line 584, in rule_expand_ports
    rule['from_port'] = int(rule.get('from_port'))
ValueError: invalid literal for int() with base 10: 'all'
failed: [localhost] (item={'value': {u'rules': [{u'to_port': 22, u'from_port': 22, u'cidr_ip': u'0.0.0.0/0', u'proto': u'tcp'}, {u'to_port': u'all', u'from_port': u'all', u'group_name': u'amcdermo-asg311', u'proto': u'all'}], u'name': u'amcdermo-asg311', u'desc': u'amcdermo-asg311 default'}, 'key': u'default'}) => {
    "changed": false, 
    "item": {
        "key": "default", 
        "value": {
            "desc": "amcdermo-asg311 default", 
            "name": "amcdermo-asg311", 
            "rules": [
                {
                    "cidr_ip": "0.0.0.0/0", 
                    "from_port": 22, 
                    "proto": "tcp", 
                    "to_port": 22
                }, 
                {
                    "from_port": "all", 
                    "group_name": "amcdermo-asg311", 
                    "proto": "all", 
                    "to_port": "all"
                }
            ]
        }
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_a3heeo/ansible_module_ec2_group.py\", line 1021, in <module>\n    main()\n  File \"/tmp/ansible_a3heeo/ansible_module_ec2_group.py\", line 875, in main\n    rules = deduplicate_rules_args(rules_expand_sources(rules_expand_ports(module.params['rules'])))\n  File \"/tmp/ansible_a3heeo/ansible_module_ec2_group.py\", line 607, in rules_expand_ports\n    for rule in rule_expand_ports(rule_complex)]\n  File \"/tmp/ansible_a3heeo/ansible_module_ec2_group.py\", line 584, in rule_expand_ports\n    rule['from_port'] = int(rule.get('from_port'))\nValueError: invalid literal for int() with base 10: 'all'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

##### Version

    $ ansible-playbook --version
        ansible-playbook 2.6.1
        config file = /etc/ansible/ansible.cfg
        configured module search path = [u'/home/aim/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
        ansible python module location = /usr/lib/python2.7/site-packages/ansible
        executable location = /usr/bin/ansible-playbook
        python version = 2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

- inventory:

```console
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
openshift_deployment_type=openshift-enterprise
ansible_ssh_user=root
openshift_clusterid=amcdermo-asg311

[masters]
[etcd]
[nodes]
```

- vars.yaml

```console
openshift_cloudprovider_kind: aws
openshift_cloudprovider_aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
openshift_cloudprovider_aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

openshift_aws_ami: ami-5b767b24
openshift_release: "3.11"

openshift_aws_clusterid: amcdermo-asg311

openshift_aws_create_iam_cert: True
openshift_aws_create_iam_role: True

openshift_aws_create_s3: False

openshift_aws_iam_cert_chain_path: /home/aim/src/aws-cluster/chain.ca.crt
openshift_aws_iam_cert_key_path: /home/aim/src/aws-cluster/wildcard.amcdermo-autoasg.openshift.com.key
openshift_aws_iam_cert_path: /home/aim/src/aws-cluster/wildcard.amcdermo-autoasg.openshift.com.crt

openshift_aws_master_group_desired_size: 1
openshift_aws_master_group_max_size: 1
openshift_aws_master_group_min_size: 1

openshift_aws_infra_group_desired_size: 1
openshift_aws_infra_group_max_size: 1
openshift_aws_infra_group_min_size: 1

openshift_aws_compute_group_desired_size: 1
openshift_aws_compute_group_max_size: 10
openshift_aws_compute_group_min_size: 1

openshift_aws_instance_type: m4.large

openshift_aws_region: us-east-1
openshift_aws_ssh_key_name: libra

openshift_cluster_autoscaler_install: true
openshift_deployment_type: openshift-enterprise

openshift_aws_node_group_config_master_volumes:
- device_name: /dev/sda1
  volume_size: 50
  volume_type: gp2
  delete_on_termination: False
- device_name: /dev/sdb
  volume_size: 200
  volume_type: gp2
  delete_on_termination: False

openshift_aws_node_group_config_node_volumes:
- device_name: /dev/sda1
  volume_size: 50
  volume_type: gp2
  delete_on_termination: True
- device_name: /dev/sdb
  volume_size: 200
  volume_type: gp2
  delete_on_termination: True

openshift_cluster_autoscaler_scale_down_delay_after_failure: 10s
openshift_cluster_autoscaler_scale_down_unneeded_timeout: 10s
openshift_cluster_autoscaler_scale_down_delay_after_add: 10s

openshift_cluster_autoscaler_node_groups:
- name: "{{ openshift_aws_clusterid ~ ' compute group 1' }}"
  min: "{{ openshift_aws_compute_group_min_size }}"
  max: "{{ openshift_aws_compute_group_max_size }}"

openshift_master_bootstrap_auto_approve: True
openshift_aws_autoname_scale_group_instances: True
```

**Comment by svbarilov** [comment]
any luck resolving this?

**Comment by frobware** [comment]
Short and simple answer is 'no' :(

I have been deploying 3.11 using 3.10 playbooks.
