### ISSUE TITLE
Containerized GlusterFS health check fails on upgrade from v3.9 to v3.10

### ISSUE THREAD

**Issue by monotykamary** [openshift/openshift-ansible#9666]
#### Description

```
ansible-playbook -vvv -i host.origin.inventory openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
```
Attempting to upgrade the control plane, or simply running the glusterfs health check playbook `openshift-ansible/playbooks/openshift-glusterfs/cluster_health_check.yml` will fail with all 120 retries resulting in error: 

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_wEm4eW/ansible_module_glusterfs_check_containerized.py", line 187, in <module>
    main()
  File "/tmp/ansible_wEm4eW/ansible_module_glusterfs_check_containerized.py", line 183, in main
    run_module()
  File "/tmp/ansible_wEm4eW/ansible_module_glusterfs_check_containerized.py", line 170, in run_module
    valid_nodes = get_valid_nodes(module, [oc_bin, oc_conf], exclude_node)
  File "/tmp/ansible_wEm4eW/ansible_module_glusterfs_check_containerized.py", line 77, in get_valid_nodes
    res = call_or_fail(module, call_args)
  File "/tmp/ansible_wEm4eW/ansible_module_glusterfs_check_containerized.py", line 68, in call_or_fail
    res = subprocess.check_output(call_args).decode('utf-8')
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

fatal: [master1 -> master1]: FAILED! => changed=false
  attempts: 120
  module_stderr: |-
    Traceback (most recent call last):
      File "/tmp/ansible_wEm4eW/ansible_module_glusterfs_check_containerized.py", line 187, in <module>
        main()
      File "/tmp/ansible_wEm4eW/ansible_module_glusterfs_check_containerized.py", line 183, in main
        run_module()
      File "/tmp/ansible_wEm4eW/ansible_module_glusterfs_check_containerized.py", line 170, in run_module
        valid_nodes = get_valid_nodes(module, [oc_bin, oc_conf], exclude_node)
      File "/tmp/ansible_wEm4eW/ansible_module_glusterfs_check_containerized.py", line 77, in get_valid_nodes
        res = call_or_fail(module, call_args)
      File "/tmp/ansible_wEm4eW/ansible_module_glusterfs_check_containerized.py", line 68, in call_or_fail
        res = subprocess.check_output(call_args).decode('utf-8')
      File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
  module_stdout: ''
  msg: MODULE FAILURE
  rc: 1
```

##### Version

```
$ uname -r
3.10.0-862.9.1.el7.x86_64
```

```
# https://github.com/openshift/openshift-ansible.git

$ printf "`git rev-parse --abbrev-ref HEAD` `git rev-parse HEAD`\n"
release-3.10 dec10a6d6d51bbd4ed8cfe730b92bd91dc5b49df
```

```
$ ansible --version
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/openshift/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

```
$ oc version
oc v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://oso3-master1:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
```

##### Additional Information

Ansible environment variables:

```
export ANSIBLE_NOCOWS=1
export ANSIBLE_STDOUT_CALLBACK=yaml
```

host.origin.inventory: 
```
[OSEv3:children]
masters
etcd
nodes
glusterfs

[OSEv3:vars]
ansible_become=yes
ansible_become_method=sudo
ansible_become_pass=
ansible_ssh_user=
ansible_service_broker_local_registry_whitelist=['.*-apb$']

openshift_deployment_type=origin
openshift_release=v3.10
openshift_image_tag=v3.10.0
openshift_clock_enabled=true
containerized=true

os_sdn_network_plugin_name=redhat/openshift-ovs-networkpolicy
openshift_docker_additional_registries=registry.fedoraproject.org
openshift_disable_check=memory_availability,docker_image_availability
openshift_node_groups=[{'name': 'node-config-master', 'labels': ['node-role.kubernetes.io/master=true']}, {'name': 'node-config-infra', 'labels': ['node-role.kubernetes.io/infra=true',]}, {'name': 'node-config-compute', 'labels': ['node-role.kubernetes.io/compute=true'], 'edits': [{ 'key': 'kubeletArguments.pods-per-core','value': ['20']}]}, {'name': 'node-config-master-infra', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true'], 'edits': [{ 'key': 'kubeletArguments.pods-per-core','value': ['20']}]}, {'name': 'node-config-all-in-one', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true'], 'edits': [{ 'key': 'kubeletArguments.pods-per-core','value': ['20']}]}]

openshift_master_dynamic_provisioning_enabled=true
openshift_storageclass_default=false
openshift_storage_glusterfs_storageclass=true
openshift_storage_glusterfs_block_deploy=true
openshift_storage_glusterfs_block_host_vol_size=20
openshift_storage_glusterfs_block_storageclass=true
openshift_storage_glusterfs_block_storageclass_default=true

[masters]
master1

[etcd]
master1

[nodes]
master1 openshift_schedulable=true openshift_node_group_name='node-config-master-infra'
node1 openshift_schedulable=true openshift_node_group_name='node-config-compute'
node2 openshift_schedulable=true openshift_node_group_name='node-config-compute'
node3 openshift_schedulable=true openshift_node_group_name='node-config-compute'

[glusterfs]
node1 glusterfs_devices='[ "/dev/sdb" ]'
node2 glusterfs_devices='[ "/dev/sdb" ]'
node3 glusterfs_devices='[ "/dev/sdb" ]'
```

**Comment by eudo1111** [comment]
same issue here. Any updates?

**Comment by eudo1111** [comment]
I solved the problem: 
1. Check if "atomic-openshift-clients" is installed on your masters.
2. Check your gluster-Volumes with 
`for vol in 'gluster volume list'; do gluster volume heal $vol info; done` 
if there are any entries that are not  showing "Number of entries: 0", solve this first. Something with your gluster replication is not wright.

**Comment by CelsoSantos** [comment]
@eudo1111  Could you please elaborate on this a bit further?

For instance, atomic-openshift-clients, should it be installed on the masters or not? It's not clear from your response.
Regarding, point 2, is that to be performed from within a glusterfs container or are we talking about a "standard" glusterfs installation?

Best Regards.

**Comment by eudo1111** [comment]
1. Yes atomic-openshift-clients must be installed.
2. Yes run this command inside of one gluster pod
