### ISSUE TITLE
oo_filters error performing HAProxy Install with atomic-openshift-installer

### ISSUE THREAD

**Issue by dgoodwin** [openshift/openshift-ansible#984]
Installation fails with:

````

PLAY [Compute haproxy_backend_servers] **************************************** 

TASK: [set_fact ] ************************************************************* 
fatal: [localhost] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1013, in _executor_internal_inner
    complex_args = template.template(self.basedir, complex_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 140, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 11, in root
  File "/usr/share/ansible_plugins/filter_plugins/oo_filters.py", line 258, in oo_haproxy_backend_masters
    server_port = host_info['openshift']['master']['api_port']
KeyError: 'master'


FATAL: all hosts have already failed -- aborting
````

My atomic-openshift-installer config file:

````
$ cat installer.cfg.yml 
ansible_config: /usr/share/atomic-openshift-utils/ansible.cfg
ansible_log_path: /tmp/ansible.log
ansible_ssh_user: cloud-user
hosts:
- connect_to: 10.3.9.221
  hostname: dgoodwin-aos-master.os1.phx2.redhat.com
  ip: 172.16.4.18
  master: true
  node: true
  public_hostname: dgoodwin-aos-master.os1.phx2.redhat.com
  public_ip: 10.3.9.221
- connect_to: 10.3.12.240
  hostname: dgoodwin-master2.os1.phx2.redhat.com
  ip: 172.16.4.48
  master: true
  node: true
  public_hostname: dgoodwin-master2.os1.phx2.redhat.com
  public_ip: 10.3.12.240
- connect_to: 10.3.12.242
  hostname: dgoodwin-master3.os1.phx2.redhat.com
  ip: 172.16.4.53
  master: true
  node: true
  public_hostname: dgoodwin-master3.os1.phx2.redhat.com
  public_ip: 10.3.12.242
- connect_to: 10.3.9.222
  hostname: dgoodwin-aos-node1.os1.phx2.redhat.com
  ip: 172.16.4.27
  node: true
  public_hostname: dgoodwin-aos-node1.os1.phx2.redhat.com
  public_ip: 10.3.9.222
- connect_to: 10.3.12.244
  hostname: dgooodwin-aos-haproxy.os1.phx2.redhat.com
  ip: 172.16.4.58
  master_lb: true
  public_hostname: dgooodwin-aos-haproxy.os1.phx2.redhat.com
  public_ip: 10.3.12.244
variant: openshift-enterprise
variant_version: '3.1'
version: v1
````

Installer is running on a separate system, not used as one of the install hosts.

**Comment by detiber** [comment]
The installer running on a separate host shouldn't affect the variable being set...
It looks like for some reason openshift_facts wasn't run against the master hosts at the point the filter was called.

As far as I can see though, the playbooks/common/openshift-master/config.yml playbook has a play that applies the openshift_facts role to the master hosts prior to the step that invokes that filter...

@abutcher any ideas?

**Comment by dgoodwin** [comment]
Looks like it was caused by earlier errors due to repos not being available. Likely system didn't have the correct pkgs installed to trigger collection of master facts.
